### ISSUE TITLE
Nullability of reference types does not match target type

### ISSUE THREAD

**Issue by pfeigl** [riok/mapperly#1014]
**Describe the bug**
When mapping lists of object, we see `Nullability of reference types in value of type 'System.Collections.Generic.List<MyProto?>' does not match target type 'System.Collections.Generic.IList<MyProto>?'` warnings.

This started after upgrading form `v2.8.0` to `3.3.0`.

As we have `TreatWarningsAsErrors` enabled, this actually stops us from building the project.

**To Reproduce**
Given the following minimal reproducable
```csharp
[Mapper]
public partial class Mapper
{
    public partial IList<MyTarget> Map(IList<MySource> sources);
    public partial MyTarget Map(MySource source);
}
public class MySource
{
    public string Name { get; set; }
}
public class MyTarget
{
    public string Name { get; set; }
}
```

The generated code earlier looked like this:
```csharp
    public partial global::System.Collections.Generic.IList<global::MyTarget>? Map(global::System.Collections.Generic.IList<global::MySource>? sources)
    {
        return sources == null ? default : global::System.Linq.Enumerable.ToList(global::System.Linq.Enumerable.Select(sources, x => Map(x)));
    }

    public partial global::MyTarget? Map(global::MySource? source)
    {
        if (source == null)
            return default;
        var target = new global::MyTarget();
        target.Name = source.Name;
        return target;
    }
```
It now looks like the following
```csharp
    public partial global::System.Collections.Generic.IList<global::MyTarget>? Map(global::System.Collections.Generic.IList<global::MySource>? sources)
    {
        if (sources == null)
            return default;
        var target = new global::System.Collections.Generic.List<global::MyTarget?>(sources.Count);
        foreach (var item in sources)
        {
            target.Add(Map(item));
        }
        return target;
    }

    public partial global::MyTarget? Map(global::MySource? source)
    {
        if (source == null)
            return default;
        var target = new global::MyTarget();
        target.Name = source.Name;
        return target;
    }
```

The difference is, that how the code actually instantiates the target object as a list of `MyTarget?` (observe the `nullable`).
However in the old code, the type was inferred from the `Map(x)` call in the select, which actually used the signature of the partial method in the mapper class  and therefor did not return nullable objects.

**Expected behavior**
No warnings are thrown from the generated code

**Additional context**
One thing the threw me off a little was, that the generated code did generate nullable code at all.
We have `<Nullable>` disabled for this specific project, though the generated code still uses it.

Ideally the generated code would only apply `?` when the partial method does so too, right?

**Comment by latonz** [comment]
Thank you for opening this issue, definitely looks like a bug. Mapperly always generates code with nullable annotations (mainly to reduce the code generator complexity). If the source project doesn't have nullable reference types enabled, Mapperly treats all types as nullable internally.
