### ISSUE TITLE
Enabling Reference Handler (UseReferenceHandling) cannot handle projects with a dash in the name

### ISSUE THREAD

**Issue by ghhv** [riok/mapperly#1015]
**Describe the bug**
I have (had) project names with dashes and needed to enable UseReferenceHandling for circular references.
When this occurs, the generated mapping code appears like so
```
return MapToGroup3(Group, new global::Riok.Mapperly.Internal.MyProject-SubProject.PreserveReferenceHandler());
```
which returns the error on compile:
```
Error	CS0118	'global::Riok.Mapperly.Internal.MyProject' is a namespace but is used like a type
```

**To Reproduce**
1. Create a project with a dash in the name &/or a leading number. 
2. Declare a mapper with
`[Mapper(UseDeepCloning = true, UseReferenceHandling = true)]`

**Expected behavior**
Visual Studio handles this internally within compilation by changing the dash to underscore. As a double whammy my project name also started with a number.. VS prefixes an underscore to the internal name as well in this case.

**Code snippets**
If applicable, add code snippets to help explain your problem.

**Environment (please complete the following information):**
- Mapperly Version: 3.3.0
- .NET Version: 8.0
- Target Framework: 8.0
- IDE: [Visual Studio v17.8.3]
- OS: [Windows 11 Pro]

**Additional context**
I resolved by renaming my project. 
It also causes VS internal errors for 'Missing Import discovery' and 'Fully Qualify'.
My bad...
Changing the project names is creating so many more problems.. :-(
FYI, I also have `<RootNamespace>` set in the project files which uses the VS friendly name..

**Comment by latonz** [comment]
Thank you for opening this issue. I'm not really happy with the current situation with the generated namespace for the reference handling implementation. This may be reworked with https://github.com/riok/mapperly/issues/881. The main problem here is that if we use a constant namespace (eg. `Riok.Mapperly.Abstractions`), Mapperly cannot be used in two projects with `InternalsVisibleTo` set. Open to ideas on how to address this 😊 We thought about introducing an MSBuild Property to set the namespace of such generated classes (with a constant default namespace), but this would introduce some complexity into Mapperly.

**Comment by ghhv** [comment]
I guess the easy fix is to use the [<RootNamespace> ](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022#:~:text=vbc.exe%20compiler.-,RootNamespace,-All) in CSPROJ if it is available as that should be compile friendly.. if it doesn't exist, then up the user to add..

**Comment by ghhv** [comment]
thanks
