### ISSUE TITLE
Nullable disabled target: An item with the same key has already been added.

### ISSUE THREAD

**Issue by stigrune** [riok/mapperly#102]
First of all, thank you for an awesome mapper! Keep up the good work 😀

**Describe the bug**
`warning CS8785: Generator 'MapperGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'An item with the same key has already been added.`

I’ll try to explain, but its maybe easier to fire up the debugger yourselves with this [repo](https://github.com/stigrune/BugReport.Mapperly), as the bug is a bit complex. 
The code flow ends up trying to add `(string, string)` twice to the mappers dictionary.  

First it adds the mapping `(string, string)` correctly. 

Then, trying to add mapping between the `List<string>`, since the target dto is flagged `#nullable disable`, it correctly calls `FindOrBuildMapping(string, string?)`

This method again runs the `FindMapping(string, string?)`, and correctly returns that there are no existing mappings for `(string, string?)`. 
Then the `BuildDelegateMapping(null, string, string?)` method runs, and results in the `NullableMappingBuilder` returns here: https://github.com/riok/mapperly/blob/fdde1270d5a0d7d0a4c4794509b15a5a956266f8/src/Riok.Mapperly/Descriptors/MappingBuilder/NullableMappingBuilder.cs#L15-L18

This changes the mapping to `(string, string)`. There is not any new check if this mapping already exists, and the `_mappings.Add()` throws the exception. 

**To Reproduce**
Build this repo: https://github.com/stigrune/BugReport.Mapperly
Look at build output.

**Code snippets**
Added personal comments to the code from [DescriptorBuilder.cs](https://github.com/riok/mapperly/blob/e8351f1e31ed4c4b6f602fc9839c5b8bf4ac391a/src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs#L97)
```csharp
    public TypeMapping? FindOrBuildMapping(
         ITypeSymbol sourceType,
         ITypeSymbol targetType)
    {
        // (string, string?) here, and it does not exists.
        if (FindMapping(sourceType, targetType) is { } foundMapping)
            return foundMapping;
        
        // Inside the BuildDelegateMapping, NullableMappingBuilder ends up changing the target from string? to string.
        if (BuildDelegateMapping(null, sourceType, targetType) is not { } mapping)
            return null;

        // mapping is (string, string) here, and this already exists.
        AddMapping(mapping);
        return mapping;
    }
```

**Environment (please complete the following information):**
 - Mapperly Version: 2.3.1
 - .NET Version: 6.0.302
 - Target Framework: net6.0
 - OS: Windows

A quick obvious fix is to recheck if the mapping exists just before trying to add it to the dictionary. This might be the best way to fix it if other MappingBuilders also modify the source or targets? 

Reply with a description of the desired fix, and I'll happily try to help out and submit a PR 😀
Edit: Fixed typo and mix-up between what is _source_ and _target_ types.

**Comment by stigrune** [comment]
I have not had much time to look into this. Used most of the time so far to get to know the codebase better. Here is a test that triggers the issue. Im currently on vacation so very limited time in from of the computer the following weeks. 
```csharp
    [Fact]
    public void NullableDirectiveEnabledTargetWithSameNullableRefTypeAsPropertyAndInEnumerable()
    {
        var source = TestSourceBuilder.Mapping(
            "A",
            "B",
            "class A { public string Value { get; set; } public string[] Descriptions { get; set; } }",
            "#nullable disable\n class B { public string Value { get; set; } public string[] Descriptions { get; set; } }\n#nullable enable");

        TestHelper.GenerateMapperMethodBody(source);
        //TODO assert
    }
```

**Comment by latonz** [comment]
In the meantime I could fix the bug 😊
Enjoy your vacation! 🏝️

**Comment by Nelfstor** [comment]
Hello! It looks like i met same issue. In one of my projects Mapperly creates nullable dublicates of the internal mappings (And ignore settings of my mapper):
![image](https://user-images.githubusercontent.com/104761338/215049505-ddad49d1-4af2-4a32-a2cf-2f3190981843.png)

![image](https://user-images.githubusercontent.com/104761338/215050068-b44f5b26-4f8c-4bbc-b764-cd91bed69e1e.png)

![image](https://user-images.githubusercontent.com/104761338/215050160-acbd91db-6c49-4059-8703-194163c0020d.png)

What is interesting - that it does it one project and it doesn't in other project with same classes. Is there any configuration that allows to control that?

**Comment by latonz** [comment]
@Nelfstor I think this not related to this issue (the bug described in this issue made Mapperly crash and no code was generated at all).
Could you create a new issue providing the following additional infos:
* Are nullable reference types enabled?
* How doe the classes `Portfolio` and `GetPortfolioResponseDto` (especially the properties of the type `Agreement` and `GetAgreementResponseDto`) look like?

**Comment by Nelfstor** [comment]
Thank you for response!

nullables are enabled:
![image](https://user-images.githubusercontent.com/104761338/215059235-7764da7d-41b9-41ed-9225-f2b57291fe91.png)

PortfolioDto:
![image](https://user-images.githubusercontent.com/104761338/215059611-c80c5791-175f-4f31-9ba0-b000820832ef.png)

Portfolio:
![image](https://user-images.githubusercontent.com/104761338/215059791-99af1f51-52e4-42a3-9981-a63d51f8223b.png)

AgreementDto:
![image](https://user-images.githubusercontent.com/104761338/215059986-ac0edf8e-5f66-4d78-ad74-51da22ff18f2.png)


Agreement: 
![image](https://user-images.githubusercontent.com/104761338/215059892-35e5359d-a436-4fff-aa78-003d74f01730.png)

**Comment by latonz** [comment]
Are nullables only enabled for the mapper file or for all files?

**Comment by latonz** [comment]
Since this is unrelated to this issue, could you please open a *new* issue? Thank you!

**Comment by Nelfstor** [comment]
Should i put it in Q&A section. Or as a bug?

**Comment by latonz** [comment]
As a bug.

**Comment by Nelfstor** [comment]
I'll do my best but actually I could not reproduce this bug in other project.
