### ISSUE TITLE
Ignoring a property based on the attribute on the property instead of the mapper attribute

### ISSUE THREAD

**Issue by moxplod** [riok/mapperly#1033]
I am using MapDerivedType extensively. It is much cleaner to specify an attribute on the property that this property is read-only or ignore this property for mapping. 

Potentially use System.Components.ReadOnlyAttribute. 

This should ignore the property on the entity and not map from DTO to entity.

```

    [MapDerivedType<CompanyDto, Company>]
    [MapDerivedType<ContactDto, Contact>]
    [MapDerivedType<UserDto, User>]
    private static partial void MapDtoToEntity(EntityDto dto, IEntity entity);

```
```

[ReadOnly(true)]
    public string ReadOnlyText { get; set; }

```

**Comment by moxplod** [comment]
My use case is for system/calculated fields. That I do not want the users to modify. But I do want to show them those fields.

**Comment by latonz** [comment]
Relates to https://github.com/riok/mapperly/issues/585. I'm not sure about configuring mappings on the entities themselves. With the current approach all configuration of the mapper is visible within its class.

**Comment by moxplod** [comment]
Yea - it is related. But in my scenario, using the current approach leads to compiler warnings as I am using MapDerivedType. 

The ignored fields are only going to be present in one of the child classes. 

For example, I want to ignore Risk property in the Company class. But that does not exist in Contact, that will throw a warning. 

![image](https://github.com/riok/mapperly/assets/4554395/2315e913-bf4c-40c9-84de-7be42de0729f)

**Comment by latonz** [comment]
Currently configuration is not supported on methods using `MapDerivedType` (see also https://github.com/riok/mapperly/issues/910). You would need to configure the ignores on a mapping method for each mapping individually.

**Comment by latonz** [comment]
Also related to #585.
