### ISSUE TITLE
Error CS0757 when mapper is in a project with XAML files 

### ISSUE THREAD

**Issue by CaptTwigg** [riok/mapperly#104]
**Describe the bug**
"CS0757	A partial method may not have multiple implementing declarations" when mapper is in a project with XAML files 

**To Reproduce**
1. Create a WPF project
2. Add mapping class 

**Expected behavior**
Mapper being generated and no errors 

**Code snippets**
```    
[Mapper]
public static partial class DtoMapperClient
{
    public static partial string StringNullSubstitude1233(string src);
}
```

**Environment (please complete the following information):**
 - Mapperly Version:  2.3.1
 - .NET Version: NET 6.0.302
 - Target Framework:  .net6.0
 - OS: Windows

**Comment by CommonGuy** [comment]
This is a bug in the .NET 6.0.302 SDK and affects all WPF projects with source generators: https://github.com/dotnet/wpf/issues/6792.

As a workaround, you could downgrade to SDK 6.0.301 or temporarily include this in the project file:
```
<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
    <!-- Work around https://github.com/dotnet/wpf/issues/6792 -->

    <ItemGroup>
        <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
        <Analyzer Remove="@(Analyzer)" />
        <Analyzer Include="@(FilteredAnalyzer)" />
    </ItemGroup>
</Target>
```

**Comment by CaptTwigg** [comment]
Perfect, the temporarily solution seems to work fine, thanks for fast response.
