### ISSUE TITLE
Partial select based on column names

### ISSUE THREAD

**Issue by svrooij** [riok/mapperly#1098]
**Is your feature request related to a problem? Please describe.**
We seem to be transfering to much unused data to all our clients from the api

**Describe the solution you'd like**
We would like to allow for partial mapping based on column names

```csharp
// Database model
class Post
{
  public string Title {get;set;}
  public string Body {get;set;}
  public DateTimeOffset CreatedAt {get;set;}
}
// DTO
class PostDto
{
  public string? Title {get;set;}
  public string? Body {get;set;}
  public DateTimeOffSet? CreatedAt {get;set;}
}

class Mapper
{
  // colums would be a comma separated list of Properties eg `Title,CreatedAt`
  // or a string array string[] colums
  internal IQueryable<PostDto> MapToDto(IQueryable<Post> posts, string colums)
}
```

**Describe alternatives you've considered**
I did consider writing my own source generator, but I think everybody can profit from this.

**Additional context**
We are using EFCore and if the mapping is applied correctly, that data won't even be pulled from the database. I have no clue how to start with contributing to mapperly, but I'm willing to implement this myself and create a PR for it, if you guys are considering this to be a good addition

**Comment by latonz** [comment]
Thank you for opening this issue and sponsoring the project!

We are always happy to welcome new contributors and to assist them for their contributions.

If everything works correctly EF should only query the data needed for the DTO. If I understand you correctly, you would additionally want to provide a list of column names as strings, which columns should be queried?
Mapperly has no reference to the EF model and does not know how to map between property and column names. This mapping is the job of EF Core not Mapperly. Can you elaborate on your use-case? Why do you want to have properties present in your DTO which you don‘t want to query?

May also be related to https://github.com/riok/mapperly/issues/953 (the mapping generated by Mapperly results in too mich data loaded by EF).

**Comment by svrooij** [comment]
We would make all the properties in the DTO nullable, and then have the client of the api specify which columns it needs, thus having 1 endpoint that can be used for all client.

```csharp
// This fictive code would do the job
var posts = context.Posts.Select(p => new PostDto{
  // Using the condition this way, does not work I guess?
  Id = colums.Contains("Id") ? p.Id : null
});
```

And we are currently using this code (no mapper) that we would like to replace:

```csharp
private static IQueryable<TDto> ApplySelect<TIn, TDto>(this IQueryable<TIn> query, string? select) where TIn : class, new() where TDto : class, new()
{
    if (!string.IsNullOrWhiteSpace(select))
    {
        var inType = typeof(TIn);
        var dtoType = typeof(TDto);
        var properties = select.Split(',');
        var parameter = Expression.Parameter(inType, "p");
        var newExpression = Expression.New(dtoType);
        var bindings = new List<MemberBinding>();
        foreach (var property in properties)
        {
            var inPropertyInfo = inType.GetProperty(property);
            if (inPropertyInfo == null)
            {
                throw new ArgumentException($"The $select parameter contains a property name '{property}' that does not exist on type '{inType.Name}'.");
            }
            var dtoPropertyInfo = dtoType.GetProperty(property);
            if (dtoPropertyInfo == null)
            {
                throw new ArgumentException($"The $select parameter contains a property name '{property}' that does not exist on type '{dtoType.Name}'.");
            }
            var propertyAccess = Expression.MakeMemberAccess(parameter, inPropertyInfo);
            var binding = Expression.Bind(dtoPropertyInfo, propertyAccess);
            bindings.Add(binding);
        }
        var memberInit = Expression.MemberInit(newExpression, bindings);
        var selectExp = Expression.Lambda<Func<TIn, TDto>>(memberInit, parameter);
        return query.Select(selectExp);
    }
    return query.SelectAll<TIn, TDto>();
}
```

**Comment by latonz** [comment]
I see your use-case but I'm afraid this is out of scope of Mapperly.

It is probably not even possible with source generation while not using reflection.
If you can rewrite the code you provided without reflection it is possible using source generation 😉

I'm closing this for now as out of scope.

**Comment by latonz** [comment]
Does it work like this? I didn't try it but just from reading the code I'd think EF Core would try to translate the `columns.Contains` part to SQL too since it is part of the select expression.

**Comment by svrooij** [comment]
The condition is evaluated before sending to the server. So the resulting SQL (with coulmns = `new [] {"Id"}` is:

```sql
SELECT Id, null as Title FROM Posts .....
```

So the expression is evaluated before sending to SQL. Which is at least better then selecting the values and then removing them when sending to the client. This way they are not loaded from the database.

**Comment by svrooij** [comment]
@latonz with these last comments, would it be something that might be accepted in this library? And can you un-close the issue if that is the case?

**Comment by latonz** [comment]
I don't think this should be included in Mapperly as it seems to be very specific and therefore outside the scope of Mapperly.

**Comment by randellhodges** [comment]
I also have a use for something like this. I'm currently using it in Automapper. It is nice because it can also omit joins if I do not pass any columns from a nested class.

@svrooij have you found an alternate way to accomplish this that could be used alongside Mapperly? Off the top of my head, I was thinking of something like System.Linq.Dynamic.Core to generate the "dynamic" selects/joins EF stuff and then just use regular (not projection) mapperly from the entity to the dto.

I haven't tried it yet, so it might not actually work like I'm hoping.

**Comment by randellhodges** [comment]
@svrooij here is something I'm playing with. It is **not** well tested and probably only works for very specific use cases.

The idea here is apply an expression visitor that after the queryable is created, removes columns you do not want. I have verified that the generated SQL does not include the columns and it also does not include joins.

I am using .NET 8 and EF Core 8.

The names of the columns would be those that you are projecting into (your DTO). For nested properties, they should be dotted, specifying the full path.

What is nice is that, even if you `.Include` a bunch of things, if you end up not passing any columns from any of those included tables, EF is smart enough to not generate a join.

I turned on `LogTo` in my DbContext and verified the generated SQL mirrors the columns that I want and not all of them. I do not expect this code to be considered complete, but it seems to work for my use case (prototype code at this point, I haven't tried it yet in a real use situation yet)

```
            var queryable = context.YourTable
                .Include(x => x.Child)
                .ProjectToDto()
                .WithColumns("Column1", "Child.Column2");
```

```
    public static class ColumnRemoverVisitorExtensions
    {
        /// <inheritdoc cref="ColumnRemoverVisitor.CreateQuery{T}"/>
        public static IQueryable<T> WithColumns<T>(this IQueryable<T> source, IEnumerable<string> columnNames)
            => ColumnRemoverVisitor.CreateQuery(source, columnNames);

        /// <inheritdoc cref="ColumnRemoverVisitor.CreateQuery{T}"/>
        public static IQueryable<T> WithColumns<T>(this IQueryable<T> source, params string[] columnNames)
            => ColumnRemoverVisitor.CreateQuery(source, columnNames);
    }

    public class ColumnRemoverVisitor : ExpressionVisitor
    {
        private readonly HashSet<string> _columns;

        public ColumnRemoverVisitor(IEnumerable<string> columns)
        {
            // We will start with the columns we want to include but, we also need to include missing parents
            // For example, if we want to include "Site.SiteCode" we also need to include "Site"
            var hashSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var column in columns)
            {
                hashSet.Add(column);

                var parts = column.Split('.');

                for (var i = 1; i < parts.Length; i++)
                {
                    var parent = string.Join('.', parts.Take(i));
                    hashSet.Add(parent);
                }
            }

            _columns = hashSet;
        }

        /// <summary>
        /// Creates a new queryable that only includes the specified columns. Specifying null or an empty list will return the original queryable.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="source"></param>
        /// <param name="columnNames">Columns should be specified using dot notation for nested properties (e.g. "Name", "Child.Name").</param>
        /// <returns></returns>
        public static IQueryable<T> CreateQuery<T>(IQueryable<T> source, IEnumerable<string> columnNames)
        {
            if (columnNames == null)
                return source;

            var visitor = new ColumnRemoverVisitor(columnNames);
            var newExpression = visitor.Visit(source.Expression);

            return source.Provider.CreateQuery<T>(newExpression);
        }

        protected override Expression VisitMethodCall(MethodCallExpression node)
        {
            if (_columns is {Count: > 0} && node.Method.Name == nameof(Queryable.Select) && node.Arguments.Count > 1 && node.Arguments[1] is UnaryExpression { Operand: LambdaExpression lambdaExpression })
            {
                var newProjection = new ExplicitColumnsVisitor(_columns).Visit(lambdaExpression.Body);
                var newLambda = Expression.Lambda(newProjection, lambdaExpression.Parameters);

                return Expression.Call(node.Method, node.Arguments[0], newLambda);
            }

            return base.VisitMethodCall(node);
        }

        private class ExplicitColumnsVisitor : ExpressionVisitor
        {
            private readonly HashSet<string> _columns;
            private string _currentPath;

            public ExplicitColumnsVisitor(HashSet<string> columns)
            {
                _columns = columns;
            }

            protected override Expression VisitMemberInit(MemberInitExpression node)
            {
                // Recursively visit each member binding
                // Note: We filter out any null bindings returned by VisitMemberAssignment (which is called by VisitMemberBinding)
                var bindings = node.Bindings.Select(VisitMemberBinding).Where(visited => visited != null).ToList();

                if (bindings.Count != node.Bindings.Count)
                    return node.Update(node.NewExpression, bindings);

                return base.VisitMemberInit(node);
            }

            protected override MemberAssignment VisitMemberAssignment(MemberAssignment node)
            {
                var previousPath = _currentPath;
                var currentPath = _currentPath == null ? node.Member.Name : $"{_currentPath}.{node.Member.Name}";

                // If the current path matches the one to remove, return null to exclude it
                // ReSharper disable once AssignNullToNotNullAttribute
                if (!_columns.Contains(currentPath))
                    return null;

                // Add the current member's name to the path before visiting its sub-expressions
                _currentPath = currentPath;

                // Visit the expression of the member assignment
                var visitedExpression = Visit(node.Expression);

                // Remove the current member's name from the path after visiting
                _currentPath = previousPath;

                // If the sub-expression has changed, create a new MemberAssignment
                // Expression.Bind(node.Member, visitedExpression) 
                if (visitedExpression != node.Expression)
                    return node.Update(visitedExpression);

                return base.VisitMemberAssignment(node);
            }
        }
    }
```

Note: Some of this code came from the Google AI summary and I have modified it to fit my use case. I could not find the "source" so I am unable to property attribute it.

**Comment by svrooij** [comment]
@randellhodges I wanted to experiment with source generators myself and ended up with [this solution](https://github.com/svrooij/dotnet-endpoint-mapper?tab=readme-ov-file#-selective-dto-mapping). Not as nice as mapperly, but does the job for my use case. And I got to learn source generators and analyzers in the mean time.
