### ISSUE TITLE
Emit warning when a mapping doesn't use the source value.

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#1111]
Mapperly should emit a warning when a mapping function is generated where the source is not used at any point to generate the target value. I'd argue that this is never intentional and only causes unexpected bugs, see #1107

ie
```C#
private static Protobuf.Timestamp MapToTimestamp(global::System.DateTimeOffset source)
{
    // source is not used, probably a bug.
    var target = new Protobuf.Timestamp();
    return target;
}
```

I'm not sure how it should be configurable be able to be disabled. There might be some scenarios where this is intentional.

**Comment by latonz** [comment]
This would address the same use-case / issue as https://github.com/riok/mapperly/issues/660, wouldn‘t it? But this seems to be a lot more complex to implement 🤔

**Comment by latonz** [comment]
Closing for now in favor of #660
