### ISSUE TITLE
Mapping DateTime to a specific TimeZone on the fly

### ISSUE THREAD

**Issue by stefanMinch3v** [riok/mapperly#1142]
We have a multitenant app where tenants have different time zones stored in their app settings.
For example a CustomerDb object has NextPayingDate which is UTC stored in the database, so whenever we pick the Customer with the NextPayingDate (UTC) from EntityFramework we have to map it to the Settings where the specific time zone is located.
Therefore it comes the need if I can do something similar to AutoMapper with IValueConverter on the fly, whenever there is a map between Dates it uses the Tenant specific TimeZone. Is it possible to do the same with Mapperly?

Example
```csharp
public async Task<CustomerDto> GetCustomerWithTimeZone(Guid customerId) 
{
	var customerSettings = await dbContext.Settings.FirstOrDefaultAsync(x => x.CustomerId == customerId);

	var customerWithTimeZone = await dbContext
		.Customers
		.Where(x => x.Id == customerId)
		.AutoMap<CustomerDto>(customerSettings) // here it maps all DateTime fields to TimeZone specific thanks to IValueConverter on AutoMapper
		.FirstOrDefaultAsync();

	return customerWithTimeZone;
}

public class CustomerDto
{
	public Guid Id { get; set; }
	public DateTime NextPayingDate { get; set; } // with correct TimeZone here set up in AutoMapper
	// other date time properties are also mapped to specific TimeZone
}

public class Customer
{
	public Guid Id { get; set; }
	public DateTime NextPayingDate {get;set;}
}

public class Settings 
{
	public Guid Id { get; set; }
	public Guid CustomerId { get; set; }
	public string TimeZone { get; set; }
}
```

**Comment by latonz** [comment]
This sounds like business logic which should actually not happen in an object mapper.
You should be able to implement this either by using [user-implemented mapping method](https://mapperly.riok.app/docs/configuration/user-implemented-methods/) for the conversion from `DateTime` to `DateTime` or [before-/after-map](https://mapperly.riok.app/docs/configuration/before-after-map/).

**Comment by stefanMinch3v** [comment]
Thank you, will take a look for a custom implementation
