### ISSUE TITLE
Prefer property with no AutoFlattenning

### ISSUE THREAD

**Issue by mzubenko69** [riok/mapperly#116]
class A
      {
          public string ValueId { get; set; }
          public C Value { get; set; }
      }

    class B
    {
        public string ValueId { get; set; }
    }

    class C
    {
        public string Id { get; set; }
    }

A => B

Expected behavior:

    var target = new B();
              target.ValueId = source.ValueId;
              return target;
  
Current behavior:

    var target = new B();
              target.ValueId = source.Value.Id;
              return target;

**Comment by latonz** [comment]
Thank you for the bug report, this should definitely be improved. In the meantime you should be able to fix this by using the `MapProperty` attribute.
