### ISSUE TITLE
Generic mapping method with type constraints results in CS0761 (type constraints are not present on the generated method)

### ISSUE THREAD

**Issue by latonz** [riok/mapperly#1189]
When a [generic mapping method ](https://mapperly.riok.app/docs/configuration/generic-mapping/#type-constraints) declaration contains type constraints these are not present in the generated code which results in `CS0761`.

Declaration:
```csharp
partial TTarget Map<TSource, TTarget>(TSource obj) where TSource : A where TTarget : B;
```

Generated:
```csharp
partial TTarget Map<TSource, TTarget>(TSource obj) // missing the constraints
{
    ...
}
```

**Comment by sommmen** [comment]
@latonz looking at [WithGenericSourceTypeConstraints](https://github.com/riok/mapperly/blob/339076970e33e5e680d5d6db7b7bbc7acd2c10e8/test/Riok.Mapperly.Tests/Mapping/GenericTest.cs#L130) this seems already implemented no?

**Comment by latonz** [comment]
@sommmen yep, that got fixed, thanks for pointing out.
