### ISSUE TITLE
merge-objects not worked

### ISSUE THREAD

**Issue by AmBplus** [riok/mapperly#1192]
Example in 
https://mapperly.riok.app/docs/configuration/existing-target/#merge-objects
not worked, the auto generated code do nothing at all
`
var fruit = new Fruit() { Color = "Green", Name = "Apple" };
var fruitForUpdate = new FruitUpdate("Red","Apple");
fruit.ApplyUpdate(fruitForUpdate);
Console.WriteLine("Name " + fruit.Name + "    ----    fruitColor : " + fruit.Color);
[Mapper(AllowNullPropertyAssignment = false)]
static partial class FruitMapper
{
    public static partial void ApplyUpdate(this Fruit fruit, FruitUpdate update);
}

class Fruit { public required string Name { get; set; } public required string Color { get; set; } }
record FruitUpdate(string? Name, string? Color);
`
and the generated code 
static partial class FruitMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.4.0.0")]
    public static partial void ApplyUpdate(this global::Fruit fruit, global::FruitUpdate update)
    {
    }
}

**Comment by latonz** [comment]
You are correct & thanks for reporting! In the sample the parameters are in the wrong order, the source always needs to be the first parameter.
