### ISSUE TITLE
Show analyzer messages in rider during development

### ISSUE THREAD

**Issue by tjaadvd** [riok/mapperly#1207]
**Describe the bug**
I don't see warning or information messages in Riders 'problems' dialog.

**Declaration code**
When I work in Visual Studio, the mapperly messages are displayed in the Error List immediately. In Rider however, I dont see the messages during programming and also not during build. 

**Actual relevant generated code**
I do not have the .editorconfig settings configured in the project, but the messages work out of the box in Visual Studio. When I add the rules to .editorconfig the messages in Rider only show up for Error levels and during build.

**Expected relevant generated code**
I want to see the relevant analyzer messages in the 'problems' dialog during development.

**Environment (please complete the following information):**
- Mapperly Version: 3.3.0
- Nullable reference types: enabled
- .NET Version: .NET 8.0
- Target Framework: .NET 8.0
- Compiler Version: 34
- C# Language Version: 12
- IDE: Rider 2023.3.4
- OS: Windows 10

**Comment by latonz** [comment]
To me this looks like an issue in Rider, I don‘t think we can do anything to fix this.
