### ISSUE TITLE
Can we map Google.Protobuf.WellKnownTypes to equivalent C# type

### ISSUE THREAD

**Issue by aspmaker** [riok/mapperly#1215]
Hello. I am using gRPC for a project.  Can we map Google.Protobuf.WellKnownTypes to equivalent C# type. When i try to map .proto file dto class to entity class it is giving this error:

![image](https://github.com/riok/mapperly/assets/19711987/70ce04eb-8c2e-450a-adb2-e60c4531a5b2)

Source: https://learn.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-9.0#nullable-types

C# type | Well-Known Type wrapper
-- | --
bool? | google.protobuf.BoolValue
double? | google.protobuf.DoubleValue
float? | google.protobuf.FloatValue
int? | google.protobuf.Int32Value
long? | google.protobuf.Int64Value
uint? | google.protobuf.UInt32Value
ulong? | google.protobuf.UInt64Value
string | google.protobuf.StringValue
ByteString | google.protobuf.BytesValue

Thank you.

**Comment by latonz** [comment]
You can simply use [user implemented methods](https://mapperly.riok.app/docs/configuration/user-implemented-methods/) for this. Mapperly doesn’t natively support 3rd party types.

**Comment by aspmaker** [comment]
This is what i wanted, thank you man.
