### ISSUE TITLE
UseDeepClone for a single level

### ISSUE THREAD

**Issue by Ajay100000** [riok/mapperly#124]
I am trying out Mapperly and am very impressed. Well done. 

I did however find a problem, I do get a stackoverflow error when using the UseDeepClone feature.

What I have done is that I created a MinimalApi using EF Core 6 and the Northwind database, as my test system.

To test complex object mapping, I tried to map Orders to a OrdersDTO.

 I get a StackOverflow error when I am using the 'UseDeepClone' feature to map the Orders and their Orderlines, but is ok if I do not use 'UseDeepClone'.

System.Text.Json had the same problem and introduced 'IgnoreCycles' as the fix. Is it possible to do something like IgnoreCycles or specify the DeepClone level of 1? 

If not, below is a workaround that meant I could map the Orders to a OrdersDTO, successfully.

Workaround:

The workaround for anyone else facing this issue is not to use the 'UseDeepClone' feature, just use [Mapper]. 

Then use System.Text.Json to clone the Mapped object to a DeepCloned object with IgnoreCycles turned on. This means that the object gets deep cloned without the stackoverflow issue (but at the cost of performance).

Here is the code for the deep clone using IgnoreCycles:

    internal static class Extensions
    {
        internal static JsonSerializerOptions jsonOpts = new() { ReferenceHandler = ReferenceHandler.IgnoreCycles };

        internal static T DeepClone<T>(this T? source) where T : class, new()
        {
            return CloneInner(source) ?? new T();
        }

        private static T? CloneInner<T>(this T? source) where T : class
        {
            if (source is null) return null;

            var jsonUtf8Bytes = JsonSerializer.SerializeToUtf8Bytes(source, jsonOpts);
            Utf8JsonReader reader = new(jsonUtf8Bytes);
            using var jsonDoc = JsonDocument.ParseValue(ref reader);
            return JsonSerializer.Deserialize<T>(jsonDoc.RootElement.Clone().GetRawText(), jsonOpts);
        }
    }

Mappings:

        public static CarDto MapToDto(this Car src) => src.ToDto().DeepClone();
        public static Car MapFromDto(this CarDto srcDto) => srcDto.FromDto().DeepClone();

        private static partial CarDto ToDto(this Car src); // this is the source generator
        private static partial Car FromDto(this CarDto srcDto); // this is the source generator

Example of usage:

        CarDto dto = car.MapToDto();
        Car newcar = dto.MapFromDto();

**Comment by latonz** [comment]
Thank you for this feature request, this would definitely be a cool feature for Mapperly. We will look into this, however this seems to need a few changes (currently we don't carry any context around...) and therefore may take a while to be implemented.

**Comment by Ajay100000** [comment]
That is great, I can use my workaround for now, when you have a solution, I will be happy to try it out.

**Comment by latonz** [comment]
Closing in favor of https://github.com/riok/mapperly/issues/172
