### ISSUE TITLE
MapIgnoreAttribute for source

### ISSUE THREAD

**Issue by AJ1000** [riok/mapperly#127]
This is great work.

You have an [MapperIgnoreAttribute] which works great for the target, but what about the source?

The scenario is that I have fields in my entity that I do not want to map to the destination (in my case the view model). I get RMG020 warnings I do not want to appear.

For example:
    
```
     public class Car
     {
        public string FullName { get; set; } = string.Empty;
        public int NumberOfSeats { get; set; }
        public string InCarOnly { get; set; } = string.Empty;
     }

    public class CarInfoVm
    {        
        public string FullName { get; set; } = string.Empty;
        public int NumberOfSeats { get; set; }
        public string InCarinfoVmOnly { get; set; } = string.Empty;
     }

```

Mapping from 'Car to CarInfoVm', and using MapperIgnoreAttribute, I can ignore InCarInfoVmOnly, but I still get the RMG020 warning for InCarOnly, as it is in the Car but not in the CarInfoVm. 

How do I eliminate this warning but keep the InCarOnly field, as that, for example, is a field I am mapping in a different view model?

Thanks.

**Comment by latonz** [comment]
Thank you for your feature request. I think this would be a nice enhancement and we plan to implement this. Would also be happy to accept a PR.

**Comment by Ajay100000** [comment]
Thanks for resolving this issue.

**Comment by Ajay100000** [comment]
Just tested it, worked for me without issue. Thanks again.
