### ISSUE TITLE
Expression bodied mappers

### ISSUE THREAD

**Issue by tcortega** [riok/mapperly#1338]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to use Mapperly with [EntityFrameworkCore.Projectables](https://github.com/koenbeuk/EntityFrameworkCore.Projectables). The current generated mappers in Mapperly use block-bodied methods, which are not compatible with EF.Projectables that require expression-bodied methods for its projectable queries.

**Describe the solution you'd like**
I would like Mapperly to support generating expression-bodied mappers. This feature would enable seamless integration with EF.Projectables, allowing us to write projection queries that are efficiently translated to SQL.

```csharp
[Mapper]
public partial class CarMapper
{
    // name could change, of course.
    [ExpressionBody]
    public partial CarDto CarToCarDto(Car car);
}
```
Would then generate:
```
public partial class CarMapper
{
    public partial CarDto CarToCarDto(Car car)
        => new CarDto {....};
}
```

**Describe alternatives you've considered**
For now I am not using Mapperly for this at all.

**Comment by latonz** [comment]
Unfortunately this won't work until https://github.com/dotnet/roslyn/issues/57239 is implemented (the `EntityFrameworkCore.Projectables` generator cannot see the Mapperly implementation). I'll close this issue for now as this may need a long time until supported by Roslyn).
