### ISSUE TITLE
Supporting `MapPropertyFromSource` for `IQueryable`-projections

### ISSUE THREAD

**Issue by EndOfTheSpline** [riok/mapperly#1375]
**Is your feature request related to a problem? Please describe.**
I often encounter situations where I would like to access a nested property of the mapped object, or need to change the type/name slightly. Currently, this will cause a RMG065 to be thrown for both `MapPropertyFromSource` and `MapProperty`, requiring slightly nasty workarounds.

As an example:

```cs
public class Car
{
    public string Model { get; set; }
    public Manufacturer Manufacturer { get; set; }
}

public class Manufacturer
{
    public string Name { get; set; }
    public Factory Factory { get; set; }
}

public class Factory
{
    public string Location { get; set; }
}

public class CarDto
{
    public string Model { get; set; }
    public string ManufacturerName { get; set; }
    public string FactoryLocation { get; set; }
}
```

which would end up with the following hand-made mapping:

```cs
cars.Select(car => new CarDto
{
    Model = car.Model,
    ManufacturerName = car.Manufacturer.Name,
    FactoryLocation = car.Manufacturer.Factory.Location
})
```

**Describe the solution you'd like**
Ideally, for `[MapPropertyFromSource]`/`[MapProperty]` to work with IQueryables as well, especially when mapping to common or native types.

In the above example, something like:

```cs
[MapPropertyFromSource(nameof(CarDto.ManufacturerName), Use = nameof(MapManufacturerName))]
[MapPropertyFromSource(nameof(CarDto.FactoryLocation), Use = nameof(MapFactoryLocation))]
public static IQueryable<CarDto> ProjectToDto(IQueryable<Car> q);

private static string MapManufacturerName(Car car)
    => car.Manufacturer.Name;

private static string MapFactoryLocation(Car car)
    => car.Manufacturer.Factory.Location;
```

However, I'm more or less open for anything. Hand-writing these mappings and working around it gets annoying quickly when having to deal with dozens of properties at a time.

**Describe alternatives you've considered**
There are some workarounds that can work, albeit they're not pretty:

- In case a property should be renamed or modified in some way, define the property in the DTO the same way it's defined in the source, mark it as `[JsonIgnore]`/similar, and use its setter/getter to populate/read the mapped property (which itself is `[MapperIgnored]`) - effectively making two properties that are somewhat linked together, but effectively for two separate systems (mapping/presentation).
- I've not used it extensively, but I think it might be possible to make "shell-types", which only contain the types I'm interested in, and have Mapperly map those too - for example, defining a `ShellManufacturer` that omits all properties except for `Name` and a `ShellFactory`, which only contains the `Location`. However, this results easily in type cluttering, and writing the properties to wire the data up can get pretty annoying, especially in multiple-nested-scenarios.

**Comment by latonz** [comment]
Instead of
```csharp
[MapPropertyFromSource(nameof(CarDto.ManufacturerName), Use = nameof(MapManufacturerName))]
[MapPropertyFromSource(nameof(CarDto.FactoryLocation), Use = nameof(MapFactoryLocation))]
public static IQueryable<CarDto> ProjectToDto(IQueryable<Car> q);
```
have you tried declaring your mapper like this:
```csharp
Instead of
```csharp
public static IQueryable<CarDto> ProjectToDto(IQueryable<Car> q);

[MapPropertyFromSource(nameof(CarDto.ManufacturerName), Use = nameof(MapManufacturerName))]
[MapPropertyFromSource(nameof(CarDto.FactoryLocation), Use = nameof(MapFactoryLocation))]
private static CarDto MapCar(Car car);
```.

The point here being you cannot apply `MapProperty`/`MapPropertyFromSource` because `IQueryable<T>` does not have these properties...

**Comment by EndOfTheSpline** [comment]
Hm! Kind of. Judging from the docs about IQueryable-projections, I had somehow wrongly assumed that "normal" mappings would not be used/not take effect when projecting. Giving your example a quick try however seems to result in a proper query - Mapperly is happy, EFCore is happy, I'm happy. Thinking about it now, I suppose defining a method using `IQueryable` isn't doing anything too magical, but rather re-using the existing mapping system (with some caveats) - which would make sense.

I think the docs could maybe be a bit clearer on this topic - while the Property configurations section is technically showing this case (although the lack of definitions is throwing me a bit off - i.e. I'm assuming that `Manufacturer` and `Producer` have the same, custom type), it didn't click with me that this could be combined together with user-implemented mapping methods to achieve this kind of result (because that section is implicitly mapping custom types).

Thank you for the quick help! I suppose this is issue can be closed.

**Comment by latonz** [comment]
How Mapperly resolves type mappings is described [here](https://mapperly.riok.app/docs/configuration/user-implemented-methods/). The documentation can always be improved, feel free to contribute 😉
