### ISSUE TITLE
Mapperly won't include renamed collection property

### ISSUE THREAD

**Issue by axelgenus** [riok/mapperly#1379]
**Describe the bug**
I have two classes, each containing a collection property. The name of the property changes so, [according to the documentation](https://mapperly.riok.app/docs/configuration/mapper/#properties--fields), I need to specify a partial method and apply the `MapPropertyAttribute` to it. This causes the property mapping not to be included in the generated class mapping.

**Declaration code**
```csharp
[Mapper]
public static partial class Mapper
{
    public static partial ChildDto MapToChildDto(Child child);

    public static partial ParentDto MapToParentDto(Parent parent);

    [MapProperty(nameof(Parent.Children), nameof(ParentDto.ChildrenList))]
    private static partial ICollection<ChildDto> MapToChildrenList(ICollection<Child> children);
}
```

**Actual relevant generated code**
```csharp
public static partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.6.0.0")]
    public static partial global::MapperlyWithCollectionWrapper.ChildDto MapToChildDto(global::MapperlyWithCollectionWrapper.Child child)
    {
        var target = new global::MapperlyWithCollectionWrapper.ChildDto();
        target.GivenName = child.GivenName;
        target.FamilyName = child.FamilyName;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.6.0.0")]
    public static partial global::MapperlyWithCollectionWrapper.ParentDto MapToParentDto(global::MapperlyWithCollectionWrapper.Parent parent)
    {
        var target = new global::MapperlyWithCollectionWrapper.ParentDto();
        target.GivenName = parent.GivenName;
        target.FamilyName = parent.FamilyName;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.6.0.0")]
    private static partial global::System.Collections.Generic.ICollection<global::MapperlyWithCollectionWrapper.ChildDto> MapToChildrenList(global::System.Collections.Generic.ICollection<global::MapperlyWithCollectionWrapper.Child> children)
    {
        var target = new global::System.Collections.Generic.List<global::MapperlyWithCollectionWrapper.ChildDto>(children.Count);
        foreach (var item in children)
        {
            target.Add(MapToChildDto(item));
        }
        return target;
    }
}
```

**Expected relevant generated code**
```csharp
public static partial class Mapper
{
    [...]

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.6.0.0")]
    public static partial global::MapperlyWithCollectionWrapper.ParentDto MapToParentDto(global::MapperlyWithCollectionWrapper.Parent parent)
    {
        var target = new global::MapperlyWithCollectionWrapper.ParentDto();
        target.GivenName = parent.GivenName;
        target.FamilyName = parent.FamilyName;
        target.ChildrenList = MapToChildrenList(parent.Children); // <--- THIS IS MISSING
        return target;
    }

    [...]
}
```

**Environment (please complete the following information):**
- Mapperly Version: 3.6.0
- Nullable reference types: enabled
- .NET Version: .NET 8.0.302
- Target Framework: .net8.0
- Compiler Version: 3.9.0-6.21124.20 (db94f4cc)
- C# Language Version: 12
- IDE: Rider 2024.1.4
- OS: macOS 14.5 (23F79)

**Additional context**
I created an unit test [here](https://github.com/axelgenus/MapperlyBug).

**Comment by latonz** [comment]
Your trying to map the `Children` property of the `ICollection`, this does not work as the `ICollection` does not have such a property. There should several diagnostics be reported during compilation, are there?
If you apply the `MapProperty` attribute to the `MapToParentDto` method it should work as expected.

**Comment by latonz** [comment]
Also no information? No RMG* diagnostics at all? 🤔

Is the mapping now generated as expected?

**Comment by axelgenus** [comment]
> Also no information? No RMG* diagnostics at all? 🤔
In "additional request", I put the link of a GitHub repository I prepared with a unit test. When building no warnings pop up.

> Is the mapping now generated as expected?
Yes, the mapping is generated correctly as per your explanation. Thank you.
