### ISSUE TITLE
Mapping for existing objects

### ISSUE THREAD

**Issue by alex-jitbit** [riok/mapperly#139]
Say I _already_ have a `Car` and a `CarDto` object instances. How do I map all properties from one object to another?

As far as I can tell, this feature is not implemented, or am I missing something?

**Is your feature request related to a problem? Please describe.**
Useful when creating a derived object from a base one. At the moment everyone uses AutoMapper and similar (non-source generated) solutions for this

**Comment by alex-jitbit** [comment]
Please disregard, I think I found it here https://riok.github.io/mapperly/docs/configuration/void-mapping-methods

**Comment by latonz** [comment]
Closing as it seems to be resolved.
