### ISSUE TITLE
Computed read-only properties causing RMG066 warning

### ISSUE THREAD

**Issue by RichardD2** [riok/mapperly#1402]
**Describe the bug**
Creating a mapping between two entities, both of which contain the same read-only computed property of a nullable value type, produces an erroneous `RMG066` warning.

**Declaration code**
```csharp
namespace Db
{
    public class Foo
    {
        public int? CategoryId { get; set; }
        public bool? IsSpecialCategory => CategoryId == 42;
    }
}

namespace Dto
{
    public class Foo
    {
        public int? CategoryId { get; set; }
        public bool? IsSpecialCategory => CategoryId == 42;
    }
}

namespace Mapping
{
    [Mapper]
    public static partial class FooMapping
    {
        public static partial Dto.Foo MapToDto(this Db.Foo source);
    }
}
```

**Actual relevant generated code**
```csharp
namespace Mapping
{
    public static partial class FooMapping
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.6.0.0")]
        public static partial global::Dto.Foo MapToDto(global::Db.Foo source)
        {
            var target = new global::Dto.Foo();
            target.CategoryId = source.CategoryId;
            return target;
        }
    }
}
```

**Expected relevant generated code**
The actual generated code is correct. However, the mapping is flagged with:

> RMG066 No members are mapped in the object mapping from bool? to bool?

**Environment (please complete the following information):**
- Mapperly Version: 3.6.0
- Nullable reference types: enabled
- .NET Version: .NET 8.0.303
- Target Framework: .net8.0
- Compiler Version: 4.10.0-3.24324.8 (04fb3916)
- C# Language Version: 12.0
- IDE: Visual Studio v17.10.4
- OS: Windows 11 23H2

**Additional context**
Explicitly adding a `MapperIgnoreSource` for the computed property makes the warning go away:

```csharp
[Mapper]
public static partial class FooMapping
{
    [MapperIgnoreSource(nameof(Db.Foo.IsSpecialCategory))]
    public static partial Dto.Foo MapToDto(this Db.Foo source);
}
```

**Comment by latonz** [comment]
Thanks for reporting. I cannot reproduce the RMG066, I always get RMG020 for `Value` and `HasValue` of the `bool?`. Do you have any properties set on the `MapperAttribute` or do you have a `MapperDefaultsAttribute` for your assembly?

**Comment by RichardD2** [comment]
No additional settings. I'm getting the two `RMG020` hints and the `RMG066` warning with just the code shown.

![image](https://github.com/user-attachments/assets/2c0cea61-5958-45eb-8a3c-28960b4abaea)

![image](https://github.com/user-attachments/assets/ead15c33-1a8f-497e-922f-6e3068846c91)

I've attached the sample project I'm using:
[Mapperly1402.zip](https://github.com/user-attachments/files/16329304/Mapperly1402.zip)
