### ISSUE TITLE
Guid and Timespan causing warning on maps

### ISSUE THREAD

**Issue by jhancock-taxa** [riok/mapperly#1454]
**Describe the bug**
On Guid and Timespan fields I'm getting these warnings on build:

 [RMG066] No members are mapped in the object mapping from System.Guid to System.Guid (https://mapperly.riok.app/docs/configuration/analyzer-diagnostics/RMG066)

[RMG066] No members are mapped in the object mapping from System.TimeSpan to System.TimeSpan (https://mapperly.riok.app/docs/configuration/analyzer-diagnostics/RMG066)

**Declaration code**
```csharp
    [MapProperty(nameof(FieldInstructionDto.Id), nameof(FieldInstruction.Id), Use = nameof(MapId))]
    public static partial void UpdateEntity(
        this FieldInstructionDto dto,
        FieldInstruction entity);
```

**Actual relevant generated code**
```
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.6.0.0")]
        public static partial void UpdateEntity(this global::Contracts.Forms.Field.FieldInstructionDto dto, global::Data.Ontologies.Forms.Fields.FieldInstruction entity)
        {
            entity.DocumentId = dto.DocumentId;
            entity.UpdatedOn = dto.UpdatedOn;
            entity.GeneratedBy = dto.GeneratedBy;
            entity.GeneratedByUserId = dto.GeneratedByUserId;
        }
```

**Expected relevant generated code**
```csharp
// The generated code how you expect it to look like
```

**Environment (please complete the following information):**
- Mapperly Version: 3.6.0
- Nullable reference types: enabled
- .NET Version: NET 8.0.303
- Target Framework: .net8.0
- Compiler Version: [e.g. 4.8.0-3.23524.11 (f43cd10b), obtain with `#error version` in any `.cs` file]
- C# Language Version: 12.0
- IDE: Rider 2024.1 (Also VS.net 2022)
- OS: macOS 14.6.1 and Windows 11 2024.04

**Comment by latonz** [comment]
We made some changes recently in this area, does this still happen with `4.0.0-next.2`?

**Comment by jhancock-taxa** [comment]
This appears to fix it. Thanks!
