### ISSUE TITLE
Support for mapping enums with different string naming conventions

### ISSUE THREAD

**Issue by BeeTwin** [riok/mapperly#1470]
**Is your feature request related to a problem? Please describe.**
I want to map snake_case string to PascalCase enum. 
E.g "first_value" => MyEnum.FirstValue, "second_value" => MyEnum.SecondValue

Currently, Mapperly supports mapping from strings to enums only if the string exactly matches the enum value's name (with an option to ignore case). This can be problematic for codebases where enum values are represented as strings in snake_case or kebab-case, as the standard naming convention for enums is PascalCase. Supporting additional naming conventions would enhance flexibility and improve integration with diverse coding standards.

**Describe the solution you'd like**
Perfect solution: add support for StringNamingConvention in MapEnumAttribute (or add separate attribute)
```csharp
[MapEnum(EnumMappingStrategy.ByName, StringNamingConvention = StringNamingConvention.SnakeCase)]
public partial MyEnum ToMyEnum(string str);

// Source generated:

var first_value = ToSnakeCase(nameof(MyEnum.FirstValue));
var second_value = ToSnakeCase(nameof(MyEnum.SecondValue));

return str switch
{
    {} s when s.Equals(first_value) => MyEnum.FirstValue,
    {} s when s.Equals(second_value) => MyEnum.SecondValue,
    _ => Enum.Parse<MyEnum>(str, false)
};

string ToSnakeCase(string enumName)
{
    // only works for PascalCase/lowerCamelCase enums
    return Regex.Replace(enumName, @"([a-z0-9])([A-Z])", "$1_$2")
        .Replace("__", "_")
        .ToLower();
}

```
Other solution: add support for strings in MapEnumValueAttribute
```csharp
[MapEnumValue("first_value", MyEnum.FirstValue)]
[MapEnumValue("second_value", MyEnum.SecondValue)]
public partial MyEnum ToMyEnum(string str);

// Source generated:

return str switch
{
    "first_value" => MyEnum.FirstValue,
    "second_value" => MyEnum.SecondValue,
    _ => Enum.Parse<MyEnum>(str, false)
};

```

**Describe alternatives you've considered**
Alternatives are user-defined mappings:
```csharp
[UserMapping]
public MyEnum StringToMyEnum(string str) =>
    str switch
    {
        "first_value" => MyEnum.FirstValue,
        "second_value" => MyEnum.SecondValue,
        _ => throw new UnreachableException()
    };
```
Or naming enum values in snake_case:
```csharp
enum MyEnum
{
    first_value,
    second_value
}
```

**Comment by latonz** [comment]
This would be a nice addition to Mapperly 😊
The enum naming strategy could also include options for the `EnumMemberAttribute` (#1079) and the `DescriptionAttribute` (#1235)).
Created #1476 to allow constant string mappings with `MapEnumValueAttribute`.

Note: in your generated code sample it looks like `ToSnakeCase` would be called at runtime, instead this should happen at compile time and the generated code would look like this:
```csharp
return str switch
{
    "first_value" => MyEnum.FirstValue,
    "second_value" => MyEnum.SecondValue,
    _ => Enum.Parse<MyEnum>(str, false)
};
```

Feel free to contribute 😉
