### ISSUE TITLE
Issue with Mapping `ICollection` Between .NET 8.0 and .NET Standard 2.0: Unexpected `null` Handling

### ISSUE THREAD

**Issue by Fpippi** [riok/mapperly#1491]
Hi everyone,

I'm encountering an issue with the generated mapping code using Riok.Mapperly in a .NET 8.0 project, while my NuGet package targets .NET Standard 2.0. I have a collection of type ICollection<Oggetto> in my project, and I’ve noticed that the code auto-generated by Mapperly treats the collection source as if it could be null, even though the collection is always initialized and should never be null.

**Problem Details**

**In my .NET 8.0 project, I have the following definition:**
`public ICollection<Test> Tests { get; set; } = new List<Test>();`

**In the .NET Standard 2.0 NuGet package, I have a similar definition:**
`public ICollection<Test> Tests { get; set; } = new List<Test>();`

**Generated Code Behavior**
The mapping code generated by Riok.Mapperly looks like this:
```csharp
public ICollection<Oggetto> Map(ICollection<Oggetto>? source)
{
    if (source == null)
        throw new System.ArgumentNullException(nameof(source));
        
    var target = new List<Oggetto>();
    
    foreach (var item in source)
    {
        target.Add(Map(item)); // Mapping method for individual items
    }

    return target;
}
```

**Issue**
Unexpected null Handling: The generated code handles the source (source) as if it could be null, throwing an ArgumentNullException if it is null. However, in my case, the collection is always initialized and should not be null. This check seems redundant and might not be necessary.
Mapping Method Signature: The mapping method signature uses ICollection<Oggetto>?, suggesting that source could be null, whereas in my case, null is not accepted and therefore should not be handled.

**Assistance Requested**
Expected Behavior: Is it a known behavior that Mapperly generates mapping code considering null values for collections even when it is not necessary?
Mapper Configuration: Is there a configuration or option in Mapperly that allows avoiding the generation of code that handles null for already initialized collections?

Thanks in advance for your help!

**Comment by latonz** [comment]
Mapperly treats all unannotated types as nullable but always generates code with enabled nullable reference types.

**Comment by Fpippi** [comment]
The issue is that I'm using the mapper with type T, but the child class for the mapping inserts a null value. In all previous method declarations, there was no need to specify the source parameter as nullable (?). However, in this case, it seems that if I don't declare the source parameter as nullable, the method doesn't match correctly with the one without the ?. I'm not sure if this behavior is intentional or not.

**Comment by Fpippi** [comment]
Look, this is the code generated by the mapper. I've had to censor the classes for various reasons. However, I don’t understand why I need to add `?` in the method signature for the second method, while for the others it's not necessary.

By type `T`, I mean something like this:

```csharp
public static partial TTarget Map<TTarget>(object source);
```

And here’s the censored code:

```csharp
private static global::System.Collections.Generic.List<global::[CENSORED].Models.[CENSORED]> MapToListOf[CENSORED](global::System.Collections.Generic.ICollection<global::[CENSORED].Models.[CENSORED]?> source)
{
    var target = new global::System.Collections.Generic.List<global::[CENSORED].Models.[CENSORED]>(source.Count);
    foreach (var item in source)
    {
        target.Add(Map(item));
    }
    return target;
}

[global::System.CodeDom.Compiler.GeneratedCode("[CENSORED]", "[CENSORED]")]
private static partial global::[CENSORED].Models.[CENSORED] Map(global::[CENSORED].Models.[CENSORED]? model)
{
    if (model == null)
        throw new System.ArgumentNullException(nameof(model));
    var target = new global::[CENSORED].Models.[CENSORED]();
}
```

--- 

Let me know if any changes are needed!

**Comment by latonz** [comment]
The generic mapping method picks up the defined mapping methods exactly as they are defined including their nullability with non-nullable annotated code treated as nullable. If you want to include a nullable (or not-annotated) type in a generic mapping there needs to be a declared mapping method for the given types with the same nullability. I hope this explains the behaviour of Mapperly.

**Comment by Fpippi** [comment]
When one of my classes contains another class (for example, a parent class with a child class), mapping the parent class automatically generates the mapping for the child class, and this works fine. However, if I need to add specific configuration to the child (e.g., set a property to null), I am forced to define a separate mapping method for the child with the source set to null. This happens because the custom configuration is not applied to the automatic mapping generated from the parent. While this doesn’t change much in practice, I still need to implement both mappings manually. What I don’t understand is why it’s necessary to set the source to null, given that the parent class must instantiate the child class, seemingly making the null unnecessary.

**Comment by latonz** [comment]
I don't fully get the points. If you think there is a bug in the behaviour of Mapperly, could you create a minimal reproducible project on GitHub showing the problem?

**Comment by Fpippi** [comment]
Hi,

The situation is a bit complex, but I’ll explain what I’ve encountered. It seems like the mapper automatically recognizes the .NET version being used (can you confirm this?), as I mentioned, I’m working with two classes from different .NET versions: my project is in .NET 8, while a NuGet package uses .NET Standard 2.0.

I’ve noticed that when I try to map a source class from .NET Standard 2.0 to .NET 8, all the parameters in the source are treated as nullable. I’d like to understand if this behavior is intentional or not. I know that null handling changed between .NET Standard 2.0 and .NET 8, but I’d like confirmation that this is causing the issue.

Specifically, when I take a non-nullable property in .NET 8 and map it from a non-nullable property in .NET Standard 2.0, the generated mapping method still treats the source (.NET Standard 2.0) as nullable. I don’t understand why this is happening.

Thanks for the clarification.
