### ISSUE TITLE
CS8795 Partial method '' must have an implementation part because it has accessibility modifiers

### ISSUE THREAD

**Issue by Carpentweet** [riok/mapperly#1513]
**Describe the bug**

**Declaration code**
```csharp
[Mapper]
public partial class AddProductCommandMapper
{
    public partial AddProductCommand MapAddProduct(AddProduct addProduct);
}
```

**Actual relevant generated code**
No generated code

**Expected relevant generated code**
Any generated code

**Environment (please complete the following information):**
- Mapperly Version: 3.6.0
- Nullable reference types: enabled
- .NET Version: .Net 8.0.400
- Target Framework: .net8.0
- Compiler Version: 4.11.0-3.24460.3 (5649376e)
- C# Language Version: 12.0
- IDE: Visual Studio Professional 17.11.4
- OS: Windows 11

**Additional context**
I have read about this issue having been reported before and I tried the suggested solutions. I have tried downgrading the version to 3.5.1, 3.5.0 and 3.4.0. After changing the version each time, I tried restarting the IDE. I also tried updating the IDE to the latest version. 

In the build output I did find this warning:
3>CSC : warning CS8785: Generator 'MapperGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'An item with the same key has already been added.'.

I checked to see if there are any classes with the same names, with different namespaces, or anything like that but they're all different so I'm out of guesses as to what the key might be.

**Comment by Carpentweet** [comment]
> Does it work with the latest 4.* version of Mapperly?

Yes, it does appear that using pre-release version 4.0.0-next.4 does resolve this issue. When will that likely be promoted to a stable version?

**Comment by latonz** [comment]
We plan to release the stable version in the next 2 weeks.
