### ISSUE TITLE
Attributes are not preserved the at runtime

### ISSUE THREAD

**Issue by ikopytko** [riok/mapperly#1537]
**Describe the bug**
I'm using data from mapperly attributes at runtime and by default these attributes are stripped from compiled assembly. It is possible to include them as [per documentation](https://mapperly.riok.app/docs/getting-started/installation/#preserving-the-attributes-at-runtime) by setting `MapperlyAbstractionsScope` to `runtime`. But this doesn't seems to work as attributes are not preserved. I've also tried to do the [constant declarations explicitly](https://github.com/riok/mapperly/blob/c2fc50a1fc17ac3a892406ffabfba1389cbc339b/src/Riok.Mapperly/Riok.Mapperly.targets#L3C36-L3C61) and it worked.

My solution structure is the next:

Core with Mapperly reference <- Services with mappers <- Host project

By including constant in services csproj, attributes are preserved:
```xml
<DefineConstants>$(DefineConstants);MAPPERLY_ABSTRACTIONS_SCOPE_RUNTIME</DefineConstants>
```

Adding `MapperlyAbstractionsScope` to any or all projects is not doing anything.

`ExcludeAssets` is not used in `PackageReference`.

**Environment:**
- Mapperly Version: 4.0.0
- Nullable reference types: enabled
- .NET Version: .NET 8.0.8
- Target Framework: .net8.0
- C# Language Version: 10.0
- IDE: Visual Studio v17.11.4
- OS: Windows 10

**Comment by latonz** [comment]
`MapperlyAbstractionsScope` only works in the same project as the mapperly reference is present (AFAIK the targets only get imported in the project which references the package directly...). Therefore I think the constant is a good solution here. I improved the docs with #1539.

Out of interest: why do you need the attributes at runtime?

**Comment by ikopytko** [comment]
I made couple more tests with Directory.Build.props and `MapperlyAbstractionsScope` doesn't seem to work either.
Moving `DefineConstants` from csproj to .props works, attributes are preserved. I think I'll do with this solution.

The idea was that to allow user to filter on any field from dto (there is a lot of crud pages). I have a generic filter builder in the project, which is able to prepare db query based on user input. In most cases table columns match dto, but in some specific cases I'm using MapProperty. So keeping this property in runtime I'm able to do 'reverse'-mapping of user filters to model names.
This is definitely overusing mapper library, but it allows to no worry for keeping parallel dictionary for the same thing already used to configure mappings.

**Comment by latonz** [comment]
Have you also moved the Mapperly package reference to the dir props file? `MapperlyAbstractionsScope` should work in every file, very the Mapperly package reference is present.

Okay, got it. I don't think Mapperly is the best fit for your use-case...
