### ISSUE TITLE
Allow mapping directly from properties/fields of DTO objects

### ISSUE THREAD

**Issue by Muchaszewski** [riok/mapperly#1540]
**Is your feature request related to a problem? Please describe.**
Currently you need quite verbose mapping for nester properties on the mapped method it'self
```csharp
[MapProperty([nameof(Car.Engine), nameof(Car.Engine.Horsepower)], nameof(CarDto.Horsepower))]
[MapProperty([nameof(Car.Engine), nameof(Car.Engine.FuelType)], nameof(CarDto.FuelType))]
[MapProperty([nameof(Car.Engine), nameof(Car.Engine.Cylinders)], nameof(CarDto.Cylinders))]
// or equivalent
[MapNestedProperties(nameof(Car.Engine))]
partial CarDto Map(Car car);
```

For complex objects, this configuration for the mapper get's complex and it is hard to see what was mapped and what still needs my attention at a glance. Especialy because we are duplicating part of the data.

**Describe the solution you'd like**
Given that it could be easily added without changing any existing functionality to map properties directly we could attribute objects like this in DTO.

```csharp
public CarDTO
{
   [MapProperty(nameof(Car.Engine.Horsepower))]
   public float Horsepower { get; set; }
   
   [MapProperty(nameof(Car.Engine.FuelType))]
   public string FuelType { get; set; }
   
   [MapProperty(nameof(Car.Engine.Cylinders))]
   public int Cylinders{ get; set; }
}
```

An approach like this would be more verbose, with the possibility to adjust configuration on the field directly without needing to write any conversion code. `[MapNestedProperties(nameof(Car.Engine))]`

**Describe alternatives you've considered**
Trust that mapping will be done properly with general `MapNestedProperties` when provided at the top level or wishing wildcard would work like `[MapNestedProperties(*)]` <- idc, what you do, just map the thing :D 

Other alternatives would be either runtime or build-time exceptions via `[ValidateMappingExists]` to make sure that mapping exists on specified properties without decompiling the code and proper tests are in place.

**Additional context**
In ASP.NET where we would attribute the code we already put attribute validations and documentation markers for swagger. Additional property here won't hurt :)
```csharp
public record LoginResult
{
    /// <summary>
    ///     Id of the user
    /// </summary>
    public string UserId { get; set; }

    /// <summary>
    ///     Email address of the user
    /// </summary>
    [DefaultValue("myemail@example.com")]
    [EmailAddress]
    public string Email { get; init; }

    /// <summary>
    ///     UserName of the user
    /// </summary>
    [DefaultValue("myUserName")]
    [DataMember(EmitDefaultValue = false)]
    [Required]
    public string? UserName { get; init; }
```

vs

```csharp
public record LoginResult
{
    /// <summary>
    ///     Id of the user
    /// </summary>
    [MapProperty(nameof(DbUser.Id))]
    public string UserId { get; set; }

    /// <summary>
    ///     Email address of the user
    /// </summary>
    [DefaultValue("myemail@example.com")]
    [EmailAddress]
    public string Email { get; init; }

    /// <summary>
    ///     UserName of the user
    /// </summary>
    [MapProperty(nameof(DbUser.PersonalData.UserName))]
    [DefaultValue("myUserName")]
    [DataMember(EmitDefaultValue = false)]
    [Required]
    public string? UserName { get; init; }
```

**Comment by latonz** [comment]
The only Mapperly configuration we currently allow is ignoring a member with `MapperIgnore`. This then applies to all mappings. We try to keep mapper's configurations within the mapper class. This makes troubleshooting and analyzing configurations a lot easier. If we would allow `MapProperty` to be applied on the members declaration, it wouldn't be clear to which mappings it gets applied. Often one has multiple mappings for the same type. It is also questionable what diagnostics are reported and how (e.g. unmapped members, unknown members, ...).

I'm closing this for now as we try to keep Mapperly's API surface limited and I don't see much benefit in allowing MapProperty on the member's declaration. We are open for alternative configuration API approaches (e.g. https://github.com/riok/mapperly/discussions/1365), but so far there hasn't been a proposal for a much improved configuration API, that wouldn't explode the complexity of Mapperly's source code.
