### ISSUE TITLE
Automatic proxy object conversion instead `LoginDTO` to `IResult<LoginDTO>`

### ISSUE THREAD

**Issue by Muchaszewski** [riok/mapperly#1541]
**Is your feature request related to a problem? Please describe.**
Currently, my code regarding DTO is pretty straightforward. It could be simplified as I need to manually cast the result into IResult type for proper annotation of data and error handling.

```csharp
[Mapper]
public static partial class LoginResultMapper
{
    public static partial LoginResult ToLoginResult(this DbUser dbUser, string sessionToken);
}
```

And then I call it like this
```csharp
// Explicit conversion to IResult<T>
return user.ToLoginResult().ToResult();
```

And as you can see it changes nothing with the actual implementation of the ToLoginResult but needs to be cast or the Result type must be manually created at the request time.

**Describe the solution you'd like**
To fix this I wish for a manual conversion method via Mapper annotation that would understand how to treat all generic composition types.

```csharp
public interface IResult<T> { ... }

// allow multiple types here eg: IResult, IResult<>, Result, ConcreteResult etc...
// Or map via return type without specification
[MapperGenericProxy(typeof(IResult<>))]
public partial class ResultProxyMapper
{
   // Mapper knows now that ToResultProxy can be used when T is mapped concrete type
   public IResult<T> ToResultProxy(this T data) {
       return new Result<T>(result);
   }
}
```

Now mapper will use this proxy automatically
```csharp
//Mapper autogenerated code
public partial IResult<ILoginResult> ToLoginResult(this DbUser dbUser, string sessionToken);
{
   // autogenerated code as before
   return concreteType.ToResultProxy();
}
```

**Describe alternatives you've considered**
1. Keep the snake case
```csharp
// Explicit conversion to IResult<T>
return user.ToLoginResult().ToResult();
```

2. Boilerplate via Before/After map
```csharp
[Mapper]
public static partial class LoginResultMapper
{
    private static partial LoginResult ToLoginResultImpl(this DbUser dbUser, string sessionToken);
    
    // Unnecessary boilerplate for all mapped types
    public static IResult<LoginResult> ToLoginResult(this DbUser dbUser, string sessionToken)
    {
        return dbUser.ToLoginResultImpl().ToResult();
    }
}
```

**Comment by latonz** [comment]
Why don't you just use an extension method for this?

Overall I don't think this should really be the job of an object-to-object mapper. This seems to be more of wrapping an object than mapping it. It may get possible with generic mappings https://github.com/riok/mapperly/issues/1285.

**Comment by latonz** [comment]
I don‘t fully understand the use-case and i dont’t get the benefits you would get… Why would‘t you simply create an extension method which converts a given type to the result type? I don‘t think that it should be the job of the Mapper to wrap one object in another.
