### ISSUE TITLE
Different nullable states on models for mapping cause error

### ISSUE THREAD

**Issue by TonEnfer** [riok/mapperly#1553]
In some cases, different nullable states (on or off) cause mapper generation to fail.
I noticed this for the following case:

**Declaration code**
```csharp
#nullable disable
public abstract record BaseModel
{
    public List<BaseModel> Objects { get; init; } = [];
}

public record DerivedModel: BaseModel;

#nullable enable
public abstract record BaseDto
{
    public List<BaseDto> Objects { get; init; } = [];
}

public record DerivedDto: BaseDto;

[Mapper]
public partial class Mapper
{
    [MapDerivedType<DerivedDto, DerivedModel>]
    public partial BaseModel Map(BaseDto dto);
}
```
Actual result:
CS8795	Partial method 'Mapper.Map(BaseDto)' must have an implementation part because it has accessibility modifiers.	
CS8785	Generator 'MapperGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'.

Expected result:
Mapper is generated without errors, as in the case of the same nullable state for source and target models

**Environment (please complete the following information):**
- Mapperly Version: 4.1.0-next.1
- Nullable reference types: see issue
- .NET Version: 8.0.403
- Target Framework: net8.0
- Compiler Version: 4.11.0-3.24460.3 (5649376e)	

- C# Language Version: 12
- IDE: Visual Studio 17.11.5
- OS: Windows 11 (10.0.22631.0)

**Comment by latonz** [comment]
Thanks for reporting.
As a workaround adding a method `private partial BaseModel? MapToNullable(BaseDto dto);` to your mapper declaration should work.
