### ISSUE TITLE
Rider: Partial method must have an implementation part because it has accessibility modifiers.

### ISSUE THREAD

**Issue by Versure** [riok/mapperly#1574]
**Describe the bug**
We've recently upgraded Mapperly from version `4.0.0` to `4.1.0` and now we run into the following error in Rider:
`Partial method 'UpdateDataSheetCommand ToCommand(this UpdateDataSheetRequestApiModel, int)' must have an implementation part because it has accessibility modifiers`

This error does not occur when reverting back to version `4.0.0`.

**Declaration code**
```csharp
public sealed record UpdateDataSheetRequestApiModel
{
    public required ICollection<UpdateDataSheetTranslationApiModel> Translations { get; set; }

    public sealed record UpdateDataSheetTranslationApiModel
    {
        public required int Id { get; init; }

        public int? DocumentFileId { get; init; }
    }
}
```

```csharp
public sealed record UpdateDataSheetCommand
    : ICommand<OneOf<Success, NotFound<DataSheet>, CustomError<DataSheetTranslationNotFound>>>
{
    public int DataSheetId { get; set; }

    public required ICollection<UpdateDataSheetTranslationModel> Translations { get; init; }

    public sealed record UpdateDataSheetTranslationModel
    {
        public required int Id { get; init; }

        public int? DocumentFileId { get; init; }
    }
}
```

```csharp
[Mapper]
internal static partial class UpdateDataSheetRequestApiModelExtensions
{
    internal static partial UpdateDataSheetCommand ToCommand(this UpdateDataSheetRequestApiModel model, int dataSheetId);
}
```

**Environment (please complete the following information):**
- Mapperly Version: 4.1.0
- Nullable reference types: Enabled
- .NET Version: 8.0.0
- Target Framework: .NET 8.0
- Compiler Version:  4.11.0-3.24468.6 (b4e5d1dd)
- C# Language Version: 12.0
- IDE: Rider 2024.1.2
- OS: Windows 11

**Additional context**
Rider does seem to build the project without issues and Visual Studio does not seem to be affected by this issue.

**Comment by TadijaBagaric** [comment]
Same thing with us, issue started popping up with upgrade 4.0.0 -> 4.1.0. Looks like an unexpected breaking change or a bug.

Target Framework .NET 8.0
C# Language Version: 12.0
OS: Win 11 WSL (22.04.2 LTS (Jammy Jellyfish))
dotnet cli: 8.0.103

**Comment by latonz** [comment]
Could you create a minimal reproducible on GitHub, that would be very helpful, thank you!

**Comment by Versure** [comment]
> Could you create a minimal reproducible on GitHub, that would be very helpful, thank you!

You could use the example from your docs:
https://mapperly.riok.app/docs/configuration/additional-mapping-parameters/

![image](https://github.com/user-attachments/assets/5413f15e-a2df-42bc-b4a9-983407640291)

I've created a minimal reproducible for you just in case:
https://github.com/Versure/Mapperly

**Comment by latonz** [comment]
Unfortunately I cannot reproduce this...
The repro you provided is actually not a valid c# project due to `CS5001: Program does not contain a static 'Main' method suitable for an entry point`. If I just add a console writeline to the program cs file, it works perfectly fine. Does it work for you if you add an executable line (fix CS5001)?

**Comment by Versure** [comment]
> Unfortunately I cannot reproduce this... The repro you provided is actually not a valid c# project due to `CS5001: Program does not contain a static 'Main' method suitable for an entry point`. If I just add a console writeline to the program cs file, it works perfectly fine. Does it work for you if you add an executable line (fix CS5001)?

No it does not. I've pushed some changes to make it run. The IDE gives you an error (show in the screenshot above) but the app builds en runs without any issues.

I'll let some colleagues dubble check if they have the same issues and let you know the results.

**Comment by latonz** [comment]
I tried the following and it works just fine 🤔 
* Checked out the projoect you provided
* run `dotnet build` with .NET 9.0 => works as expected
* clean and run `dotnet build` with .NET 8.0 => works as expected
* clean again and build in docker using `docker run --rm -v $(PWD):/data -w /data mcr.microsoft.com/dotnet/sdk:9.0 dotnet build` => works as expected
* clean again and build in docker using `docker run --rm -v $(PWD):/data -w /data mcr.microsoft.com/dotnet/sdk:8.0 dotnet build` => works as expected

Maybe it is related to the sdk build or OS. I'll run more tests later today. Let me know the results after checking with your colleagues 😊

**Comment by Versure** [comment]
> I tried the following and it works just fine 🤔
> 
> * Checked out the projoect you provided
> * run `dotnet build` with .NET 9.0 => works as expected
> * clean and run `dotnet build` with .NET 8.0 => works as expected
> * clean again and build in docker using `docker run --rm -v $(PWD):/data -w /data mcr.microsoft.com/dotnet/sdk:9.0 dotnet build` => works as expected
> * clean again and build in docker using `docker run --rm -v $(PWD):/data -w /data mcr.microsoft.com/dotnet/sdk:8.0 dotnet build` => works as expected
> 
> Maybe it is related to the sdk build or OS. I'll run more tests later today. Let me know the results after checking with your colleagues 😊

Ok, I think the mystery has been solved. 2 of my colleagues didn't have the same issue, but were running on a newer version of Rider. So I've updated my Rider version to `2024.2.7` and this seems to solve my issue.

Sorry for wasting your time @latonz. But kinda strange that this issue didn't occur with version `4.0.0`.

**Comment by latonz** [comment]
👍

**Comment by joel122002** [comment]
For me the problem was that the project already had an analyser which prevented the source generator from running. 
I had to global search `<Analyzer` and comment out all instances of it.
