### ISSUE TITLE
Source generated class not mapped

### ISSUE THREAD

**Issue by MatteoZampariniDev** [riok/mapperly#1582]
**Describe the bug**
Inherited properties of source objects are ignored if the inheritance is defined in a source generated file.

**Declaration code**

```csharp
// Base class
public abstract class AuditableEntity
{
    public int Id { get; set; }
}

// Partial DB model (handwritten)
public partial class Foo {}

// Partial DB model (generated using source generation)
public partial class Foo : AuditableEntity {} // <---------------------- here is the problem

// Dto
public partial class FooDto
{
    public int Id { get; set; }
}

// Mapperly configuration
[Mapper(RequiredMappingStrategy = RequiredMappingStrategy.Target)]
public static partial class DtoMap
{
    public static partial FooDto MapToDto(this Foo source); // <---------------------- throws error: 'Id' property is missing from `Foo`
}
```
In the case presented above Mapperly throws an error saying that 'Id' property is missing from `Foo`. This is not true because it is added by the source generated partial class that inherits from `AuditableEntity` (and you could write a mapping method with it).

The error is _NOT_ thrown when the inheritance is defined in the handwritten `Foo` class as shown below; in this case it maps the 'Id' property correctly.

```csharp
// Base class
public abstract class AuditableEntity
{
    public int Id { get; set; }
}

// Partial DB model (handwritten)
public partial class Foo  : AuditableEntity {} // <---------------------- no problem here

// Partial DB model (generated using source generation)
public partial class Foo {}

// Dto
public partial class FooDto
{
    public int Id { get; set; }
}

// Mapperly configuration
[Mapper(RequiredMappingStrategy = RequiredMappingStrategy.Target)]
public static partial class DtoMap
{
    public static partial FooDto MapToDto(this Foo source); // <----------------------  does not throw error
}
```

Is there any fix for this? Thank you.

**Environment (please complete the following information):**
- Mapperly Version: 4.1.0
- Nullable reference types: enabled
- .NET Version: .NET 8.0.1
- Target Framework: .net8.0
- Compiler Version: 4.12.0-3.24510.2
- C# Language Version: 13.0 latest
- IDE: Visual Studio 2022 v17.12.0 Preview 4.0

**Comment by latonz** [comment]
Chaining source generators is not supported and I don't know any workarounds despite implementing the generated code by hand.
See [FAQ](https://mapperly.riok.app/docs/getting-started/faq/#mapperly-does-not-work-when-i-use-source-generator-x) and https://github.com/dotnet/roslyn/issues/57239

**Comment by MatteoZampariniDev** [comment]
Uhm you're right... well I guess that moving the db models to another project could fix the problem since mapperly would receive them as compiled

Thank you
