### ISSUE TITLE
RMG013 with property's using base types

### ISSUE THREAD

**Issue by jacob7395** [riok/mapperly#1585]
**Please do the checklist before filing an issue:**
- [x] I have read the [documentation](https://mapperly.riok.app), including the [FAQ](https://mapperly.riok.app/docs/getting-started/faq/)
- [x] I can reproduce the bug using the latest prerelease version
- [x] I have searched existing [discussion](https://github.com/riok/mapperly/discussions) and [issue](https://github.com/riok/mapperly/issues) to avoid duplicates

**Describe the bug**
When building a type where one of the properties is a base type, it throws an RMG013 since it can't access the constructer. For the example bellow ExampleDto may have a ExampleDtoBase? Nested value, since the ExampleDtoBase can't be constructed it gives a compile error.

```csharp
public record ExampleDto(string Value, ExampleDtoBase? Nested) : ExampleDtoBase(Value);
public abstract record ExampleDtoBase(string Value);

public record Example(string Value, ExampleBase? Nested) : ExampleBase(Value);
public abstract record ExampleBase(string Value);

[Mapper(AutoUserMappings = true)]
public static partial class ExampleDtoMappers
{
    internal static partial Example ToDomain(this ExampleDto source);
}
```
After some head scratching I do understand why but and found a fix by adding the bellow to my mapper class;

```csharp
    [UserMapping(Default = true)]
    public static ExampleBase? ToDomain(ExampleDtoBase? source)
    {
        return source switch
        {
            null                  => throw new NotImplementedException(),
            ExampleDto exampleDto => throw new NotImplementedException(),
            _                     => throw new ArgumentOutOfRangeException(nameof(source))
        };
    }
```

This is not quite a bug but maybe there could be some detail added to the docs, or possible a feature to support this kind of mapping. I am happy to add a PR to update the docs but I don't know if I am just missing a feature.

The example above is a bit simplified but I hope it explains the issue.

**Comment by TonEnfer** [comment]
Hi @jacob7395
I asked something similar yesterday - https://github.com/riok/mapperly/discussions/1583
Perhaps your problem is also caused by the lack of init properties support mentioned in the answer (#643)?
