### ISSUE TITLE
Separate RequiredMappingStrategy configuration for enums

### ISSUE THREAD

**Issue by jorisBarkema** [riok/mapperly#1590]
**Is your feature request related to a problem? Please describe.**
When there are multiple properties on the Source you want to ignore because they are not present (and relevant on the target) setting RequiredMappingStrategy = RequiredMappingStrategy.Target is super convenient. However, setting this property also removes the warnings when the source has Enum values that are not present on the Target, which can cause runtime exceptions.

**Describe the solution you'd like**
I would like the RequiredMappingStrategy.Target to still give warnings when the source has enum values which are not present in the target.

**Describe alternatives you've considered**
The alternative is not using RequiredMappingStrategy.Target and ignoring the members not present on the source manually using [MapperIgnoreSource] but that is much less convenient in many cases.

**Additional context**
N/A

**Comment by jacob-buckaroo** [comment]
I submitted a PR that removes the constraints on "RequiredMappingStrategy.Target" and "RequiredMappingStrategy.Source" related to missing target/source enum members.

My reasoning is that RequiredMappingStrategy should only affect missing properties or fields, rather than limiting the possible values within an enum.

**Comment by latonz** [comment]
I don't think it's a good idea to disable this for all enum mappings. This would also be a breaking change and cannot be implemented in a minor release. You can already overwrite the required mapping strategy for each mapping, including enum mappings.

**Comment by jacob-buckaroo** [comment]
I'm not sure if we're on the same page. My PR does not break any tests.

**Comment by latonz** [comment]
Unfortunately, the test coverage is insufficient in this case. I have added a test #1593 that fails with the proposed changes.

**Comment by latonz** [comment]
Sorry if I wasn't clear on my first comment. I totally understand where you are coming from. What you are describing is more or less what i meant. Idea on how the current situation could be improved without a breaking change:
* Add `MapperAttribute.RequiredEnumMappingStrategy` / `MapperDefaultsAttribute.RequiredEnumMappingStrategy`
* Resolve  `RequiredMappingStrategy` for each enum mapping in the following order, fall back to the next one if the previous one is not set:
  1.`MapperRequiredMappingAttribute` on the mapping method
  2. `MapperAttribute.RequiredEnumMappingStrategy`
  3. `MapperDefaultsAttribute.RequiredEnumMappingStrategy`
  4. `MapperAttribute.RequiredMappingStrategy`
  5. `MapperDefaultsAttribute.RequiredMappingStrategy`

With the next breaking change it would then be possible to decouple the enum strategy and remove 4 and 5 in the list.
Would be happy to review a PR implementing this 😊

**Comment by jacob-buckaroo** [comment]
I updated my PR according to your specification.

**Comment by jacob-buckaroo** [comment]
Did you have a change to review my PR @latonz?
