### ISSUE TITLE
Unflattening does not create an instance of the property

### ISSUE THREAD

**Issue by keithmifsud17** [riok/mapperly#182]
**Describe the bug**
When unflattening the entire source into a property of target, that property is not initialized before setting the values resulting in a runtime `NullReferenceException`

**To Reproduce**
1. Declare a mapper as an interface
2. Add a wrapper around CarDto
3. Add a mapping method `CarWrapper CarToWrapper(Car car);`
4. Execute mapper

**Expected behavior**
target object and inner property created and initialized

**Code snippets**

```
public record Car
{
    public string Make { get; set; } = null!;
}

public record CarDto 
{
    public string Make { get; set; } = null!;
}

public record CarWrapper
{
    public CarDto Dto { get; set; } = null!;
}

[Mapper]
public partial class CarMapper
{
    [MapProperty(source: "Make", target: "Dto.Make")]
    public partial CarWrapper CarToWrapper(Car car);
}

var mapper = new CarMapper();
var car = new Car { Make = "CoolCar" };
var wrapper = mapper.CarToWrapper(car);
wrapper.Dto.Should().NotBeNull();
wrapper.Dto.Make.Should().Be("CoolCar");
```

**Environment (please complete the following information):**
 - Mapperly Version: 2.5.0
 - .NET Version: .NET 6.0.102
 - Target Framework: .net6.0
 - OS: windows / docker mcr.microsoft.com/dotnet/aspnet:6.0-alpine

**Additional context**

**Comment by CommonGuy** [comment]
This is because you marked your properties as non-nullable, but still assigned `null` to them. Mapperly does not create and assign new instances to non-nullable properties, as they should already contain a value (given that they are non-nullable).

Either mark your properties as nullable or assign a value to them, then it will work as expected.
