### ISSUE TITLE
how to get the different fields/properies when before/after mapped ? 

### ISSUE THREAD

**Issue by sgf** [riok/mapperly#183]
how to get the different fields/properies when before/after mapped ? 

how to got the mapped result is that update some   fields/properies ?

same question mark in https://github.com/agileobjects/AgileMapper/issues/229

**Comment by CommonGuy** [comment]
We have no plans to implement such a feature.

**Comment by sgf** [comment]
> We have no plans to implement such a feature.

ok,tks
