### ISSUE TITLE
Mapping of properties with camelCase naming

### ISSUE THREAD

**Issue by zsolt3991** [riok/mapperly#186]
**Is your feature request related to a problem? Please describe.**

I have an external set of models which are provided as by an external library which are using camelCase notation for their property names, the application models being PascalCase. While this is not ideal and not the recommended convention, there is always the possibility of legacy/generated code that does not adhere to best practices in naming. Mapping is provided by a different library right now, which is able to map these items, but using runtime reflection.

While looking into lightweight replacements for the current library, I have come across Mapperly. Sketching up a quick example it seems that, in case of the properties that are not both named using PascalCase, the mapping relation is unable to be created, instead there will be only an analyzer message for both the source and target properties not having a mapping relation defined. 

Adding the attribute [MapProperty] for the specific property to map from source to target correctly applies the mapping, however in this case it would be required to have to explicit mapping for every property. 

I am not sure if this is actually by design that the library is looking only for a case sensitive match for property names, based on the documentation not mentioning I would assume so. If it is supported then it might be a bug that is triggered by the specific use case.

**Describe the solution you'd like**
It would be a great addition to support mapping across objects which use different naming conventions. For the case mentioned above most likely providing just the possibility to do a case-insensitive comparison of property names would satisfy the requirements, either by having it out of box, or as a setting, similar on how Enum mappings can be already configured to value or name comparison.

More involved options might also be possible, using a dedicated attribute, for example to support underscore word separators instead of capitalization.

**Describe alternatives you've considered**
The alternative options would be explicit mapping for every single property, effectively writing the mapping by hand in the form of [MapProperty] attributes.

**Additional context**
```
public class A 
{
  public int MyProperty {get; set;} 
}

public class B 
{
  public int myProperty {get; set;} 
}

[Mapper]
public partial class Mapper
{
  public partial B AToB(A) // this gives message for both A.MyProperty and B.myProperty not being mapped to each other

  [MapProperty(nameof(A.MyProperty),nameof(B.myProperty))]
  public partial B AToBExplicit(A) // this maps correctly by defining the relation manually
}

```

**Comment by latonz** [comment]
Adding a case insensitive fallback match seems to be a good option to me. I think it should be added before trying the flattened/unflattened variants.
Feel free to create a PR (hint: `Riok.Mapperly.Descriptors.Mappings.PropertyMappings.PropertyPath.TryFind`)

**Comment by latonz** [comment]
Closed by https://github.com/riok/mapperly/pull/189
