### ISSUE TITLE
User implemented mapping methods ignored when return type is string?

### ISSUE THREAD

**Issue by mshgh** [riok/mapperly#193]
I am curious why it was decided to always make the conversion to string using `.ToString()` rather then using the custom mapping method, if provided? I would expect the custom method to have the highest priority ever.

Here is the method which I tried and which seems to be ignored
```csharp
private static string IntToStringSpecial(int id) => (id + 5).ToString();
```

This is just easiest way how to reproduce it, not meaningful situation. But, if you have a look e.g. here https://thomaslevesque.com/2020/10/30/using-csharp-9-records-as-strongly-typed-ids/ they have decided to override `.ToString()` like
```csharp
 public override string ToString() => $"ProductId {Value}";
```
which is cool for debugging, but not very useful for type conversion. In this case I am not sure how to use your mapper.

**Comment by mshgh** [comment]
Disregard my comment, please. I have realized
- none of my custom mapping methods were actually used.
  The generated implementation was identical to the one I provided. Lesson learned - I don't need custom method in case target class has constructor accepting source type. Pretty cool!
  ```csharp
  private EntityId StringToEntityId(string id) => new EntityId(id); // not needed!
  ```
- the custom mapping methods cannot be static
  It's a bit of surprise as mapper class can be static, but not a big deal. Fixed

note: I have realized as well the type match takes into consideration nullability, I guess this is intentional
this method is used (according to my classes definition)
```csharp
private string? EntityIdToString(EntityId? id) => id?.Value;
```
but this one is ignored and `.ToString()` is used instead
```csharp
private string EntityIdToString(EntityId id) => id.Value;
```

**Comment by latonz** [comment]
Thanks for creating this issue. The documentation of Mapperly in those areas (matching and priority of mappings) definitely needs some improvements (I created https://github.com/riok/mapperly/issues/196 to track this).
As the original matter of this issue seems to be resolved, I'll close this for now.
