### ISSUE TITLE
Default mapper configuration per assembly

### ISSUE THREAD

**Issue by latonz** [riok/mapperly#201]
Allow to set an attribute on the assembly level to set default configurations applied to all mappers.
These should be overwritable by configurations via a `MapperAttribute` on a mapper class. A mapper class still needs the `MapperAttribute` to mark the class to be taken into account by Mapperly.

The attribute for the assembly level configurations may use another name, since probably (now or in the future) not all and/or different options may be configurable on an assembly level.

**Comment by latonz** [comment]
Rel. https://github.com/riok/mapperly/discussions/199 1

**Comment by Chimaine** [comment]
I would like to support the general idea of global or sharable configurations es well. For our scenario, we would like to ignore properties on a base class, so we don't need to repeat something like `[MapperIgnoreSource("Id")]` on every Mapper.
