### ISSUE TITLE
Mappers using 2.6.0-next-1 do not build against the .NET6 SDK

### ISSUE THREAD

**Issue by zsolt3991** [riok/mapperly#204]
**Describe the bug**
Project using 2.6.0-next-1 does not build against the .NET6 SDK

**To Reproduce**
Add mapperly 2.6.0-next-1 to a project targering netstandard2.0, on a system where the .NET6 SDK is installed.

Error during build time:
The analyzer assembly ... references version '4.4.0.0' of the compiler, which is newer than the currently running version '4.3.0.0'. 

**Expected behavior**
Projects are able to be built using the .NET6 SDK. Currently it seems like it is only able to build with the .NET 7 SDK installed, which indeed includes the 4.4.0.0 version of the compiler, which is not the LTS branch.

This seems to be the result of #179 which bumped the required version from 4.0.1 to 4.4.0

**Environment (please complete the following information):**
 - Mapperly Version: 2.6.0-next-1
 - .NET Version: NET 6.0.4xx
 - Target Framework: netstandard2.0
 - OS: ubuntu 20.04 on Azure DevOps

**Comment by latonz** [comment]
@zsolt3991 Mapperly v2.6.0-next.2 should work with .NET 6.0. Could you validate this?

**Comment by zsolt3991** [comment]
Just seen the update. Will try to validate tomorrow

**Comment by zsolt3991** [comment]
Just tested: 2.6.0-next.2 works using .NET 6 SDK to build
