### ISSUE TITLE
Setup mapping method for each property

### ISSUE THREAD

**Issue by heggi** [riok/mapperly#217]
**Is your feature request related to a problem? Please describe.**

An example. I have enum that I want to map to string, but not using ToString() but by my own method.
```csharp
public enum TestEnum
{
    A,
    B,
    C,
}

public static class TestEnumExtentions
{
    public static string Name(this TestEnum source)
    {
        return source switch
        {
            TestEnum.A => "Enum A",
            TestEnum.B => "Enum B",
            TestEnum.C => "Enum C",
            _ => "No Enum",
        };
    }
}

public class Source
{
    public TestEnum Ee { get; set; }
}

public class Dest
{
    public string Ee { get; set; } = string.Empty;
}

[Mapper]
public static partial class Mapper
{
    public static partial Dest MapToDest(Source source);

    private static string enumToName(TestEnum source) => source.Name();
}

// I got generated code 
public static partial class Mapper
  {
      public static partial mapperly_test.Dest MapToDest(mapperly_test.Source source)
      {
          var target = new mapperly_test.Dest();
          target.Ee = enumToName(source.Ee);
          return target;
      }
  }
```

But if I want to convert enum to string via any different methods at the same time (.Name() and .ToString() for example), there is no way to do it.
`[MapProperty(nameof(Source.Ee.Name()), nameof(Dest.Ee))]` got compile error

Where can be many situations when we need to convert from one to other type using via different methods.

**Comment by latonz** [comment]
Thank you for your feature request. However, this is not on our roadmap for the foreseeable future.
What you could do is ignore these properties and map them manually with [after map](https://mapperly.riok.app/docs/configuration/before-after-map).
