### ISSUE TITLE
Mapping to readonly array

### ISSUE THREAD

**Issue by heggi** [riok/mapperly#226]
**Is your feature request related to a problem? Please describe.**
Protobuf compiler (protoc) generate class with fields which has only getter for arrays.
Example
```proto
syntax = "proto3";
option csharp_namespace = "Test";

message TestMessage {
    repeated int32 repeatedField = 1;
}
```
generate to 
```csharp
public sealed partial class TestMessage : pb::IMessage<TestMessage>
{
// skip many code
    private readonly pbc::RepeatedField<int> repeatedField_ = new pbc::RepeatedField<int>();
    public pbc::RepeatedField<int> RepeatedField {
      get { return repeatedField_; }
    }
// skip many code
}
```
Usualy this used as
```csharp
var test = new TestMessage();
test.RepeatedField.Add(111);
test.RepeatedField.AddRange(new[] { 111, 222, 333 });
```

Now Mapperly ignore properties like that.

**Describe the solution you'd like**
Add to generated code construction like
```csharp
if (target.RepeatedField != null)
{
    target.RepeatedField.AddRange(source.RepeatedField);
}
```
or 
```csharp
target.RepeatedField?.AddRange(source.RepeatedField);
```

**Additional context**
Tested with latest version 2.6.0-next.3
Google.Protobuf version 3.21.12
Grpc.Tools version 2.50.0

**Comment by latonz** [comment]
Thank you for this report. This is definitely something which needs improvement.

**Comment by jamescarterbellMSFT** [comment]
I was trying to find a stop gap solution for this same exact problem (also doing gRPC mappings) and found the following generate code that *seems* right, but sadly the parent generator doesn't seem to find the void mapping methods:
`private partial void MapToFooBars(List<FooBarModel>? source, RepeatedField<FooBarMessage> target)`

Generates:
```
if (source == null)
    return;
target.Capacity = source.Capacity;
target.this[] = MapToFooBar(source.this[]);
```

**Comment by Blackclaws** [comment]
Its similar for dictionaries in generated grpc code. Those are MapFields which also only have a getter. Basically you have to copy the contents from one to the other.

**Comment by jamescarterbellMSFT** [comment]
Hoping to open a PR for this asap, but it looks like right now mapperly won't map any readonly properties, but I think it would be fairly safe to default to a model of mapping readonly properties for reference types via existing ref mappers (map(source, target)) and leave open the possibility of doing the same for value types in the future via (map(source, ref target)), which means we may as well do both types using ref.  Trying my hand at it to see how complex this is.

**Comment by latonz** [comment]
Mapperly currently only supports object to object mappings in void mapping methods (thats why the implementation for `private partial void MapToFooBars(List<FooBarModel>? source, RepeatedField<FooBarMessage> target)` is generated as it is. For such cases the diagnostics should definitely be improved and indexed properties should not be mapped.). Mapperly only generates an implementation for void mapping methods, but does not consider them when looking for / generating a mapping for one type to another.
The main problem here is that Mapperly maps to a property by calling the setter of a property and therefore only takes target properties with an accessible setter into account. As described by @heggi, for collection properties this needs to be adjusted to map to read only collection properties by calling Add/AddRange.
