### ISSUE TITLE
List interfaces cannot be mapped to

### ISSUE THREAD

**Issue by zsolt3991** [riok/mapperly#247]
**Describe the bug**
Generic interfaces for `List<T>`, namely `IList<T>, IReadonlyList<T>` cannot be mapped to. Attempting to map to a property of interface type will throw an analyzer that the type has no constructor, which is true as these are interfaces.

**To Reproduce**
1. Declare a class with mapper attribute 
2. Declare two objects which require the mapper to implement` List<TSource> -> IList<TResult>` or` List<TSource> -> IReadonlyList<TResult>` mapping
3. Define a partial method for mapping between the object types in 2.

**Expected behavior**
Mapping is generated by ToList, similarly to `List<TSource> -> List<TResult>` mappings when the argument needs mapping, or by casting in case where attribution can be directly made. Also any other `IEnumerable<TSource> -> IList<TResult>/IReadOnlyList<TResult>` should work with ToList mapping.

Mapping from the Interface types works, just not to Interface types. Looking at the code, these relations are implemented for Dictionary interfaces, but not for the List types.

**Environment (please complete the following information):**
- Mapperly Version: up to 2.6.0
- .NET Version: .NET 6
- Target Framework: net6.0
- OS: crossplatform

**Comment by zsolt3991** [comment]
Looking at the PR #234, it sounds similar, however it looks like the PR is targeting the `readonly` Property of `IList/IList<T>` cannot be written issue rather than a writable property of the` IReadOnlyList<T>` type.

**Comment by latonz** [comment]
Thank you for your PR. I'll look into it.

**Comment by zsolt3991** [comment]
I can provide a PR with code changes later today. Just need to fix up the tests

**Comment by latonz** [comment]
Oh thank you, but I implemented it already...
If you want to contribute, similar issues are https://github.com/riok/mapperly/issues/249 and https://github.com/riok/mapperly/issues/250 😉

**Comment by latonz** [comment]
This is now released in Mapperly `2.7.0-next.1`
