### ISSUE TITLE
Dictionary and Enumerable Mappings: Call `EnsureCapacity` if source count is known and target has a `EnsureCapacity(int)` method

### ISSUE THREAD

**Issue by latonz** [riok/mapperly#251]
If Mapperly generates a `foreach` / `Add` mapping the capacity of the target is increased as needed.
If the source/target count is known (type does have a `Count`/ `Length` property or `Enumerable.TryGetNonEnumeratedCount()` returns true) and the target type does have a Method `EnsureCapacity(int)`, `EnsureCapacity(source.Count + target.Count)` can be called to ensure the target collection has a big enough capacity for all source objects plus the existing target objects and does not need to resize as mapped objects are added.

**Comment by Blackclaws** [comment]
This is already done via constructor arguments for dictionaries and lists I think. Calling EnsureCapacity there would be redundant

**Comment by latonz** [comment]
You are correct, if the target is created by Mapperly via `new` and the target type is a List or Dictionary. But if the target instance already exists, it is created via an object factory or is any type implementig `IDictionary<,>` or `IList<>` but is not Dictionary/List (eg. a custom List implementation), the capacity is not ensured.
