### ISSUE TITLE
record support

### ISSUE THREAD

**Issue by schmitch** [riok/mapperly#258]
**Is your feature request related to a problem? Please describe.**
Support of Record Types

**Describe the solution you'd like**
currently at the moment records are not supported and instead mapperly treats records as dto classes, which does not work

records are created like:
```
            if (view == null)
                return default;
            var target = new AdditionalApiData()
            {Id = view.Id, Guid = view.Guid, Identifier = view.Identifier ?? default};
            return target;
```

this will fail of course since records don't support object initalizers like that instead everything needs to put into the constructor:
```
            var target = new AdditionalApiData(
                view.Id, view.Guid, view.Identifier ?? default)
```

However even that would make problems, because there is another nullable part inside the constructor so a solution for that would need to be found aswell.

(Not sure if it is even possible, maybe with a empty default constructor and the with syntax? which probably would defeat the purpose of the records)

**Comment by latonz** [comment]
Thank you for your bug report.
Records should be supported by Mapperly.
Could you provide the contents of the record `AdditionalApiData`, the source type as well as of the mapper? or even better a minimal repro? Thank you!

**Comment by latonz** [comment]
Closing as no new information is provided. Feel free to reopen if the issue consists.

**Comment by srgloureiro** [comment]
Records are being recommended left and right on Linkedin as the adequate structure for middle layer DTOs, and I agree.

So I support and upvote this request.
