### ISSUE TITLE
Support fields

### ISSUE THREAD

**Issue by Blackclaws** [riok/mapperly#262]
**Describe the bug**
Mapping from for example System.Numerics.Quaternion is broken. I get the feeling that this might be something that's either not spelled out enough in the documentation or something that is an oversight because people mostly deal with Properties anyway. Anyway mapping from/to fields does not work. They are completely ignored. Which is a shame because I do tend to need such mapping from time to time and I currently have to do them manually.

**To Reproduce**
```
public class Quat
{
    public float X;
    public float Y;
    public float Z;
    public float W;
}

[Mapper]
public static partial class Map
{
    public static partial Quat ToQuat(Quaternion quaternion);
}
```

Generated code:
```
    public static partial class Map
    {
        public static partial ClassLibrary1.Quat ToQuat(System.Numerics.Quaternion quaternion)
        {
            var target = new ClassLibrary1.Quat();
            return target;
        }
    }
```

***

**Environment (please complete the following information):**
- Mapperly Version: 2.6.0
- .NET Version:  7
- Target Framework: 7
- OS: Linux

**Additional context**

**Comment by latonz** [comment]
Thank you for opening this issue. Currently, Mapperly does not support fields, but this seems like a nice enhancement.

**Comment by softlion** [comment]
> Thank you for opening this issue. Currently, Mapperly does not support fields, but this seems like a nice enhancement. For now, fields need to be mapped manually.

Personally I prefer that fields don't map. So if this is implemented, it should be an option :)

**Comment by Blackclaws** [comment]
> > Thank you for opening this issue. Currently, Mapperly does not support fields, but this seems like a nice enhancement. For now, fields need to be mapped manually.
> 
> Personally I prefer that fields don't map. So if this is implemented, it should be an option :)

It might make sense to have it optional, but it should be enabled by default. In which cases would you _not_ want to map public fields?

**Comment by softlion** [comment]
> It might make sense to have it optional, but it should be enabled by default. In which cases would you _not_ want to map public fields?

Even if that looks like a good idea to you, it’s not.
In well architectured apps there is no public field only properties, so the object is fully isolated and can be changed without breaking anything and even maintaining backward compatibility if that is desired through the get/set interceptors.

Most of the time the remaining public fields are storing some kind of temporary state that you don’t want to propagate.

**Comment by Blackclaws** [comment]
> > It might make sense to have it optional, but it should be enabled by default. In which cases would you _not_ want to map public fields?
> 
> Even if that looks like a good idea to you, it’s not. In well architectured apps there is no public field only properties, so the object is fully isolated and can be changed without breaking anything and even maintaining backward compatibility if that is desired through the get/set interceptors.
> 
> Most of the time the remaining public fields are storing some kind of temporary state that you don’t want to propagate.

I don't have any objects with public fields and if I had them they would be storing state I want to map.

My example was from the System.Numerics library which is part of the standard library so you can say what you want about that being well or not well engineered its not something I have any control over.

Seeing as how mapperly only maps things that name match anyway having those public fields mapped by default makes total sense. I would expect that if I have a target field/property that has the same name that it gets mapped, excluding things like temporary state should be done by either not naming it that way in the first place in the mapped to object or just running custom mapping code after.

**Comment by softlion** [comment]
Mapping from system.numerics does not make sense as it mostly contains structs and not classes: and mapping struct to struct does not make sense, as you can simply use an assignment (=) to copy a struct.

for other libs like entity framework copying “internal” public fields will trigger a lot of issues.

**Comment by latonz** [comment]
As this seems to be a rare use case, off by default seems reasonable to me. Also for example System.Text.Json doesn't serialize public fields by default. In a first iteration, a `IncludeFields` option on the `MapperlyAttribute` which enables mapping public fields should do the job.

**Comment by Blackclaws** [comment]
> Mapping from system.numerics does not make sense as it mostly contains structs and not classes: and mapping struct to struct does not make sense, as you can simply use an assignment (=) to copy a struct.

Of course it makes sense. I'm not sure what you use mapperly for, but I use it mostly to map between incoming DTOs and my domain objects. The incoming DTOs coming from gRPC do _not_ use the System.Numerics classes directly so you can't just assign them. In other cases where you have to map between different Vector3 implementations (such as when working with Unity) you also can't just assign them. Its a bit weird to just assume that you would not want to map structs.

> for other libs like entity framework copying “internal” public fields will trigger a lot of issues.

This will not happen, Mapperly would not generate mapping code for the inherited classes that EFCore generates during runtime, but would instead generate mapping code for your entities as they are defined. Therefore public fields that EF adds for its own use would _not_ be mapped by the created code anyway. 



> As this seems to be a rare use case, off by default seems reasonable to me. Also for example System.Text.Json doesn't serialize public fields by default. In a first iteration, a `IncludeFields` option on the `MapperlyAttribute` which enables mapping public fields should do the job.

Well fair enough. I think its a different use case so on by default would have made more sense to me (it confused me that the option wasn't there to begin with) but its fine by me if you want to keep the current behavior. 

I really think that identifying which fields should be mapped by name is enough and I don't foresee a real use case where a field would be mapped by accident.

**Comment by latonz** [comment]
On a second thought and after reading @Blackclaws's comment I think enabling field mappings by default should be fine and even expected by most of users. #346 adds support for fields. Field mappings are enabled by default and the only currently implemented way to disable them is by using `MapperIgnoreTarget` / `MapperIgnoreSource`.
A next release should be published in the upcoming days including this feature.

**Comment by softlion** [comment]
A lot of devs expect consistent behaviors between different .NET features. So having a feature that behaves like Fody.PropertyChanged or System.Text.Json makes more sense in my vision of things.

The new "record" type for example is a compact syntax to create a class or struct with only properties.

I understand what you mean with mapping those structs.
