### ISSUE TITLE
The new list-copier tries to set readonly indexers

### ISSUE THREAD

**Issue by alex-jitbit** [riok/mapperly#283]
**Describe the bug**
If a class has a get-only indexer, generated code throws exception.

**To Reproduce**

```
using System.Net.Http;
using Riok.Mapperly.Abstractions;

[Mapper]
public static partial class PropertyMapper
{
	public static partial void CopyTo(HttpRequestMessage source, HttpRequestMessage dest);
}
```

HttpRequestMessage is a class that has some properties with get-only indexers that your library tries to clone.

**Environment:**
- Mapperly Version: 2.7.0
- .NET 6
- Target Framework: .net6.0

**Comment by alex-jitbit** [comment]
Some actual code to provoke this exception:

```
using System.Net.Http;

[Mapper]
public static partial class PropertyMapper
{
	public static partial void CopyTo(HttpRequestMessage source, HttpRequestMessage dest);
}
```

`HttpRequestMessage` is a class has some properties with get-only indexers that your library tries to clone.

**Comment by latonz** [comment]
Thank you for reporting this, I'll look into it.

**Comment by latonz** [comment]
#286 implements that no mapping is generated if the target does not implement `IDictionary<,>` and therefore Mapperly should not write to read only dictionaries anymore. However, while testing this fix with `HttpRequestMessage` I encountered another Bug which isn't that easy to fix: https://github.com/riok/mapperly/issues/286. I'll look into that one as soon as I have the time.
