### ISSUE TITLE
Add configuration option to exclude deprecated members 

### ISSUE THREAD

**Issue by latonz** [riok/mapperly#284]
Currently deprecated members are included unless ignored by a `MapperIgnore*Attribute`.
It would be nice to have an attribute `[MapperIgnoreObsoleteMembers]` and a configuration property `IgnoreObsoleteMembers` on the `MapperAttribute` to ignore all obsolete properties.

**Comment by TimothyMakkison** [comment]
Should there be an option to configure whether the attribute applies to the source, target or both?

`[MapperIgnoreObsoleteMembers(source: false, target: true)]`
public static partial CarDto MapCarToDto(Car car);

How should it interact with expliicit property mapping? ie should there be the option to blanket ignore all obsolete members except when `[MapProperty]` is used?

**Comment by latonz** [comment]
I think I'd implement it with a flags enum `[Flags] enum MappingSourceTarget {  None = 0, Both = ~None, Source = 1 << 0, Target = 1 << 1 }` and an attribute `MapperIgnoreObsoleteMembers` accepting a single enum value as ctor parameter. Additionally add a property `IgnoreObsoleteMembers = MappingSourceTarget.Both` on the `MapperAttribute`.

IMO that would be a good approach, ignore the obsolete members unless an explicit mapping is specified by `MapProperty`.

**Comment by TimothyMakkison** [comment]
👍 this is basically what I've doing. 

> Additionally add a property IgnoreObsoleteMembers = MappingSourceTarget.Both on the MapperAttribute.

So I should make ingoring Obsolete member the default then.

> IMO that would be a good approach, ignore the obsolete members unless an explicit mapping is specified by MapProperty.

This part might be harder than I thought 😄

**Comment by latonz** [comment]
Whoops, I meant the default to be `IgnoreObsoleteMembers = MappingSourceTarget.None`, my bad.
