### ISSUE TITLE
Consider using nameof to access property paths

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#317]
### Problem
Currently when declaring a `PropertyIngore` or `MapProperty` in order to target nested properties you must use an array of `nameof` calls or a raw string. Neither are appealing, both are cumbersome with minimal checking, and in the case of a raw string will be broken by renaming a property.

In an ideal world `fullnameof` would exist letting you cleanly write a chain of member accessing and get the corresponding string.
```C#
Console.WriteLine(nameof(Car.Make.Id)) // prints "Id"

Console.WriteLine(fullnameof(Car.Make.Id)) // prints "Car.Make.Id"
```

### Solution
`CallerArgumentExpression` was added in .NET 6, together with nameof it can be used to get the full name. This can be used in the constructors for `MapPropertyAttribute`, `MapperIgnoreSourceAttribute` and `MapperIgnoreTargetAttribute`.
```C# 
// New
[MapProperty(nameof(Car.Make.Id), nameof(CarDto.MakeId")]
public static partial CarDto MapCarToDto(Car car);

// Old
[MapProperty(Source = "Car.Make.Id", Target = "CarDto.MakeId")]
public static partial CarDto MapCarToDto(Car car);

[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public class TargetAttribute : Attribute
{
    public MapPropertyAttribute(string target, [CallerArgumentExpression(nameof(target))] string fullpath = default!)
    {
        // Do some validation here...

        // Strip "nameof(" and ")"
        FullPath = fullpath.Substring(fullpath.IndexOf("(") + 1, fullpath.IndexOf(")") - fullpath.IndexOf("(") - 1);
    }

    // Use for reflection or source generator
    public string FullPath { get; set; }
}
```

#### Example `CallerArgumentExpression` usage
```C#
using System.Runtime.CompilerServices;

var fullString = StringOf(nameof(HttpResponseMessage.Content.Headers));

// Prints: HttpResponseMessage.Content.Headers
Console.WriteLine(fullString);

static string StringOf(string value, [CallerArgumentExpression(nameof(value))] string fullpath = default!)
{
    // value is: "value"
    // fullpath is: "nameof(HttpResponseMessage.Content.Headers)"
    // Do some validation here...

    // Strip "nameof(", ... ")"
    string outputString = fullpath.Substring(fullpath.IndexOf("(") + 1, fullpath.IndexOf(")") - fullpath.IndexOf("(") - 1);

    return outputString;
}
```

### Alternative proposal - Roslyn
While the attribute can [work with .Net Standard 2.0](https://stackoverflow.com/a/70034587/11522147), it relies on using a recent version of roslyn (I think) and could break. Instead `AttributeDataAccessor.Access` could be modified to use roslyn to read the nameof expression. This can be done with minimal changes.

The downsides of both approaches are that it uses `nameof` in a new way and that any benefits could be outweighed by the users confusion.
 Note that these changes perhaps would not be "breaking" as due to how nameof currently works, it is unlikely that a chain greater than one member access is in use.
```C#
// It is unlikely that `nameof(Car.Make.Id)` is currently ever written instead of `nameof(Make.Id)`
[MapProperty(nameof(Car.Make.Id), nameof(CarDto.MakeId")]
public static partial CarDto MapCarToDto(Car car);
```

**Comment by latonz** [comment]
Thank you for this proposal. Such a simplification on how Mapperly is configured would improve the DX a lot. However, I think Mapperly shouldn't change the behaviour of a c# built in expression.
Also stripping the `nameof(` prefix and the `)` suffix usually isn't enough (eg. `Car.Make.Id`  usually means `Make.Id` is the value to be used).
