### ISSUE TITLE
Analyzer should ignore readonly properties in target

### ISSUE THREAD

**Issue by marcoatribeiro** [riok/mapperly#329]
When creating a mapping method from `Source` to `Target` classes, where `Target` has a readonly property, analyzer shows the **RMG012** warning, which doesn't make sense, as it would not be possible to map to a readonly property anyway.

**To Reproduce**
1. Create `Source` class with any set of properties (e.g. `FirstName` and `LastName`)
2. Create `Target` class with all the properties from `Source` plus a readonly property (e.g. `FullName => FirstName + LastName`)
3. Create a `Mapper` class and a method to map from `Source` to `Target`
4. Check the analyzer displays _RMG012_ warning

**Expected behavior**
As the target property is readonly (and, thus, cannot be assigned to), the aforementioned warning should not be displayed.

**Environment**
- Mapperly Version: 2.7.0
- .NET Version: .NET 7
- IDE: Visual Studio v17.5.4
- OS: Windows 11

**Comment by marcoatribeiro** [comment]
Hi, @latonz !

I just upgraded Mapperly to version 2.8.0 and, although issue #345 is part of this release, this problem still occurs, as can be seen below:

![image](https://github.com/riok/mapperly/assets/35035369/332a64f6-0dd4-4a85-8ac7-2396eda2b944)

Classes `PersonEntity` and `PersonDto` have settings just like I described above, with both having `FirstName` and `LastName` properties and `PersonEntity` only having `FullName` (readonly) property:

```csharp
public class PersonEntity
{
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public string FullName => $"{FirstName} {LastName}";
}
```

```csharp
public class PersonDto
{
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
}
```

Can you please advise?

**Comment by TimothyMakkison** [comment]
Hey @marcoatribeiro, is this problem present in the prerelease version?

**Comment by marcoatribeiro** [comment]
Hi, @TimothyMakkison and @latonz!

Please disregard my previous comment. I just check it again (with version 2.8.0) and it is working as expected now.
Yesterday I tested right after I updated the package, so, most likely the alert was still showing because VS was still referencing the previous version (even though I had built the whole solution).
