### ISSUE TITLE
ImmutableDictionary mapper bug

### ISSUE THREAD

**Issue by czmirek** [riok/mapperly#359]
I want to map between `Dictionary<int,string>?` and `ImmutableDictionary<int,string>` but the following code fails on `ImmutableDictionary<int, string> has no accessible parameterless constructor`

Please note:
- the `DictModel` is nullable with getter and setter
- the `ImmutableDictModel` has `required`, getter and initializer

Tested in `2.7.0` and `2.8.0-next.1`

```csharp
public class DictModel
{
    public Dictionary<int, string>? Test { get; set; }
}

public sealed class ImmutableDictModel
{
    public required ImmutableDictionary<int, string> Test { get; init; }
}

[Mapper]
public static partial class TestMapper
{
    public static partial DictModel ToDictModel(this ImmutableDictModel model);
    public static partial ImmutableDictModel ToImmutableModel(this DictModel model);
}
```

**Comment by latonz** [comment]
The PR to support immutable dictionaries just landed yesterday (https://github.com/riok/mapperly/pull/351) and is not yet released. You can subscribe to https://github.com/riok/mapperly/issues/250 to receive an update once a preview release which includes this feature is released.
