### ISSUE TITLE
When using IEnumerable warnings appear that should not

### ISSUE THREAD

**Issue by Ajay100000** [riok/mapperly#360]
When using IEnumerable, warnings appear that should not appear. This is the code:

[Mapper]
public static partial class EntityToResponse
{
    [MapperIgnoreSource(nameof(TestEntity.EntityOnly))]
    [MapperIgnoreTarget(nameof(TestResponse.ResponseOnly))]
    public static partial IEnumerable<TestResponse> ToResponse(this IEnumerable<TestEntity> src);    
}

I get the following warnings (but the mapping works ok, I think):

RMG012	Property ResponseOnly on source type MapperlyTest.TestEntity was not found

RMG020	The property EntityOnly on the mapping source type MapperlyTest.TestEntity is not mapped to any property on the mapping target type MapperlyTest.TestResponse

Without IEnumerable, it is all fine, and no warnings appear

[Mapper]
public static partial class EntityToResponse
{
    [MapperIgnoreSource(nameof(TestEntity.EntityOnly))]
    [MapperIgnoreTarget(nameof(TestResponse.ResponseOnly))]
    public static partial TestResponse ToResponse(this TestEntity src);
}

These are the classes:

public class TestEntity
{
    public int Id { get; set; } = default;
    public string Name { get; set; } = String.Empty;
    public string EntityOnly { get; set; } = String.Empty;
    
}

public class TestResponse
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string ResponseOnly { get; set; } = string.Empty;
}

Is this an issue or have I implemented IEnumerable incorrectly?

**Comment by latonz** [comment]
Mapperly does only work with generic collection types, therefore you need to use `IEnumerable<TestEntity>` and ` `IEnumerable< TestResponse >`

**Comment by Ajay100000** [comment]
Ok, Thanks
