### ISSUE TITLE
throw error in build time when target type has not mapped all properties.

### ISSUE THREAD

**Issue by Dejv98** [riok/mapperly#363]
for example;
source type => CarDto {
 int Id;
 Color Color;
}
target type => Car{
 int Id;
 Color Color;
 decimal Price;
}

And i want to throw a error in build time because Price was not mapped. I can only do it now via property on Mapper Attribute (ThrowOnPropertyMappingNullMismatch = true) but sadly it's in runtime.
Or i can use MapPropertyAttribute but now i need to do it for all target properties which is pain in ass.

**Comment by latonz** [comment]
Probably what you are looking for are [strict mappings](https://mapperly.riok.app/docs/configuration/analyzer-diagnostics).

**Comment by Dejv98** [comment]
thanks, solved. Im blind :D
