### ISSUE TITLE
Docs for UseDeepCloning appear to be wrong

### ISSUE THREAD

**Issue by jamesfoster** [riok/mapperly#369]
I would have thought if `UseDeepCloning` was true that it **would** use deep cloning?

https://github.com/riok/mapperly/blob/0a489aebdd1b302586bdeb9ad03475d9e20a5716/src/Riok.Mapperly.Abstractions/MapperAttribute.cs#L44-L50

**Comment by latonz** [comment]
It seems that the documentation is the wrong way around and your assumption is correct. Thank you for reporting!
