### ISSUE TITLE
Explicit Mapping Method

### ISSUE THREAD

**Issue by slang25** [riok/mapperly#371]
First; I love this library!

Currently in Mapperly there is the ability to specify mappings between source and destination types, which will be discovered and used. There is also the ability to map between different explicitly named members, using the `MapProperty` attribute.

The problem I have is I have a `string => string` mapping, and I just want to use it for one pair of members, not for all string to string mappings.

My feature suggestion is to extend `MapProperty` to accept an optional `mapMethod` parameter (naming is hard), which you could use `nameof` to reference your own ad-hoc method.

So for a minimal example:

```csharp
public class Model
{
    public string Price { get; set; } // "5.99"
}

public class ViewModel
{
   pubic string DisplayPrice { get; set; } // "£5.99"
}

public static class Mappings
{
    [MapProperty(source: nameof(Model.Price), target: nameof(ViewModel.DisplayPrice), mapMethod: nameof(this.FormatPrice)]
    public static partial ViewModel ToViewModel(this Model mode);

    public static string FormatPrice(string sourcePrice)
    {
        return $"£{sourcePrice}";
    }
}
```

I suspect there are many other approaches that would solve this too, so would love to hear your take on this @latonz

**Comment by latonz** [comment]
There is a discussion around this topic: https://github.com/riok/mapperly/discussions/162.
This is not supported by Mapperly and will probably never be supported as there are other options and a mapper should implement as little logic as required to map the types.
Other options you can consider:
* Use [before/aftermap](https://mapperly.riok.app/docs/configuration/before-after-map)
* Use a getter on the source object (eg. on the class Model `public string DisplayPrice => $"£{Price}"`

**Comment by latonz** [comment]
Closing as am implementation is not planned in the foreseeable future and there is an open discussion on this topic.
