### ISSUE TITLE
Mapping lookup generation

### ISSUE THREAD

**Issue by jamescarterbellMSFT** [riok/mapperly#372]
Mapping from one data type to another is very powerful and useful, however, when reporting errors that occur on a non user facing data type, sometimes the field name of the internal type is not useful to the user.

It would be incredibly useful if Mapperly could generate some table that would allow you to transform the full path name of some property to the full path name of the property that the first maps to.  I'm not sure exactly how this would work when user overrides are present in a mapping, but it could still be very helpful.

**Comment by latonz** [comment]
This could really help troubleshooting in some scenarios. I think if a user override is present, the tree could be reset at the level of the user mapping implementation.
