### ISSUE TITLE
Mapperly generates mapping to static property.

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#379]
**Explain the bug**
Mapperly will generate a broken mapping to a targets static property.

**To Repoduce**

**Expected behavior**
Mapperly should not attempt to set a static property via its instance. It should instead not generate a mapping and issue a warning.

**Code snippets**
```C#
public record Model
{
    public int Value { get; set; }
}

public record ModelDto
{
    public static int Value { get; set; }
}

[Mapper]
public partial class MyMapper
{
    public partial ModelDto MapModel(Model model);
}

```
#### Generated code
```C#
public partial ModelDto MapModel(Model model)
{
    var target = new ModelDto();
    target.Value = model.Value; // Member 'ModelDto.Value' cannot be accessed with an instance reference; qualify it with a type name instead.

    return target;
}
```

**Environment (please complete the following information):**
- Mapperly Version: 2.8.0 - 2.6.0
- .NET Version: .NET 7
- Target Framework: .NET 7.0
- IDE: Visual Studio 2022
- OS: Windows 10

**Additional context**
I discovered this bug when trying to replicate #376 I think these are different problems.

**Comment by latonz** [comment]
This seems to be a bug introduced in https://github.com/riok/mapperly/pull/346
