### ISSUE TITLE
Derived types single configuration for base type configurations

### ISSUE THREAD

**Issue by latonz** [riok/mapperly#386]
https://github.com/riok/mapperly/issues/330 / https://github.com/riok/mapperly/pull/366 added support for derived type mappings. As of now, if a property needs a configuration on the base type (eg. `MapProperty`) it needs to be done for each individual type. The configuration could be simplified a lot, when the configuration could happen on the base type method.

Classes:
```c#
abstract class Car { public int Age { get; set; } }
class Audi : Car {}
class Porsche : Car {}

abstract class CarDto {  public int Age2 { get; set; } }
class AudiDto : CarDto {}
class PorscheDto : CarDto {}
```

Configuration on base type mapping method:
```c#
[Mapper]
public static partial class ModelMapper
{
    [MapDerivedType<Audi, AudiDto>]
    [MapDerivedType<Porsche, PorscheDto>]
    [MapProperty("Age", "Age2")] // this does not work here...
    public static partial CarDto MapCar(Car source);
}
```

Current required configuration:
```c#
[Mapper]
public static partial class ModelMapper
{
    [MapDerivedType<Audi, AudiDto>]
    [MapDerivedType<Porsche, PorscheDto>]
    public static partial CarDto MapCar(Car source);
    
    [MapProperty("Age", "Age2")]
    private static partial PorscheDto MapPorsche(Porsche source);
    
    [MapProperty("Age", "Age2")]
    private static partial AudiDto MapPorsche(Audi source);
}
```

**Comment by latonz** [comment]
@onionhammer I think this is an important feature, however I think it does not block a stable release of Mapperly as it is backward compatible. It could just be a little annoying to use derived type mappings without this.

**Comment by onionhammer** [comment]
@latonz Yeah I just bumped into it naturally using the 'next' release, so I imagine anyone using derived mappings will run into it pretty quickly

**Comment by InspiringCode** [comment]
I would really much need support for specifying mappings for a base class. I have the following base classes with LOTS of subclasses:

```csharp
      public partial PositionDTO Map(Position source);

      [MapProperty(nameof(MassPosition.Mass), nameof(MassPositionDTO.MassInInputUnit))]
      public partial MassPositionDTO Map(MassPosition source);

      [MapProperty(nameof(@DurationPosition.Duration.Hours), nameof(DurationPositionDTO.DurationInH))]
      public partial DurationPositionDTO Map(DurationPosition source);

      // ShaftSealingPosition derives from MassPosition and I need to duplicate this mapping on every subtype
      [MapProperty(nameof(MassPosition.Mass), nameof(MassPositionDTO.MassInInputUnit))]
      public partial ShaftSealingPositionDTO Map(ShaftSealingPosition source);
```

@latonz What the status of #513 (Include mapping configuration)? This could also solve my situation, although the best solution would be if Mapperly automatically recognizes that there is already a mapping defined for the base class and pick it up automatically.
