### ISSUE TITLE
Converting `Nullable<T>` to `T` generates warning message.

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#416]
Generated code for #413, generates a `null reference warning`. I'd guess this is because .NET treats each call to the same array index as a potentially different value. I've found two refactors that will suppress this.

```C#
private static string[] MapToStringArray(string?[] source)
{
    var target = new string[source.Length];
    for (var i = 0; i < source.Length; i++)
    {
        // below has the `null reference warning`
        target[i] = source[i] == null ? throw new System.NullReferenceException($"Sequence {nameof(source)}, contained a null value.") : source[i];

        // Reolved with
        // var placeholder = source[i];
        // target[i] = placeholder == null ? throw new System.NullReferenceException($"Sequence {nameof(source)}, contained a null value.") : placeholder;

        // or
        // target[i] = source[i] ?? throw new System.NullReferenceException($"Sequence {nameof(source)}, contained a null value.");
    }

    return target;
}
```

**Comment by latonz** [comment]
I think here it would also be safe to add a `!` to `source[i]`. This could simply be done in `NullDelegateMapping` by adding a `PostfixUnaryExpression` to the `sourceValue` if it is a `ElementAccessExpressionSyntax`: https://github.com/riok/mapperly/blob/e933f36e5a5b96f41b7e386c21897f3a1ef1e7c2/src/Riok.Mapperly/Descriptors/Mappings/NullDelegateMapping.cs#L61
