### ISSUE TITLE
Create an FAQ

### ISSUE THREAD

**Issue by CommonGuy** [riok/mapperly#441]
Some questions pop up repeatedly. We should put them in an FAQ in the documentation.

Frequently asked questions:

- Q: I updated the Mapperly version, but the generated code still looks the same. A: Restart the IDE to make it load the new version of Mapperly. This is a bug of the IDE.
- Q: Everything is configured correctly and `dotnet build` works, but the IDE shows the error "[Mapper method] must have an implementation part because it has accessibility modifiers". A: Try to rebuild the solution or restart the IDE. This is a bug of the IDE.
- Q: My advanced use case isn't supported by Mapperly or needs lots of configuration. What should I do? A: Write the mapping for that class manually. You can mix automatically generated mappings and [user implemented mappings](https://mapperly.riok.app/docs/configuration/user-implemented-methods) without problems.

**Comment by latonz** [comment]
For improved SEO results, FAQ's should use schema.org structured faq data (see [here](https://schema.org/FAQPage)).

**Comment by latonz** [comment]
Additional question:
* Q: Mapperly does not work when I use source generator X. A: Chaining source generators is not supported by Roslyn. (eg. https://github.com/riok/mapperly/issues/533)
