### ISSUE TITLE
MappingConversionType should support ExistingEnumerable and ExistingDictionary

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#443]
Related to #429.

**Describe the solution you'd like**
Similarly to Enumerable and Dictionary mapperly should support disabling `ExistingEnumerable` and `ExistingDictionary` mapping.

I've created a [branch](https://github.com/TimothyMakkison/mapperly/tree/collection_clone_429) with these changes. I've tried to outright disable mapping for a member if it is an enumerable or dictionary, otherwise Mapperly will attempt to map the objects pproperties like, capacity which probably isn't desrired. I don't think Mapperly has a way for a `MappingBuilder` to emit no mapping, so I added `BlankExistingMapping` with a check in `ExistingTargetMappingBuilder` to skip the member. There is probably a better way of doing this hence why it isn't a PR.

**Comment by latonz** [comment]
I don't think it makes sense to separate the `ConversionType` for existing targets and new targets as the mapping itself is still from enumerable to enumerable. But there is a Bug that `EnumerableMappingBuilder.TryBuildExistingTargetMapping` and `DictionaryMappingBuilder.TryBuildExistingTargetMapping` should check `ctx.IsConversionEnabled(MappingConversionType.Enumerable)` / `ctx.IsConversionEnabled(MappingConversionType.Dictionary)`.

**Comment by TimothyMakkison** [comment]
> FYI: if a MappingBuilder cannot create a mapping, it can just return null

Mapperly will try to copy the collections properties if it returns null.

```C#
[Mapper(EnabledConversions = MappingConversionType.All & ~MappingConversionType.ReadOnlyEnumerable)]
public static partial class Mapper
{
    public static partial void Map(A s, A t);
}
public record A
{
    public List<int> Values { get; }
}
// Generated code
public static partial void Map(global::Riok.Mapperly.Sample.A s, global::Riok.Mapperly.Sample.A t)
{
    t.Values.Capacity = s.Values.Capacity;
}
```
