### ISSUE TITLE
Name Mapping

### ISSUE THREAD

**Issue by jamescarterbellMSFT** [riok/mapperly#446]
Often times, errors that occur on one layer of a system will have to be reported back to the user, after an underlying model has been mapped from the user message to the internal message.  When this occurs, it's helpful to be able to pinpoint which user input was at issue, however, if the names or message structure changes through the system, mapping from an internal property name back to a user property name can be tedious.

Since mapperly already maps properties to properties based on property names, it should be straight forward to also allow it to output some sort of property name map or look up method on a mapper that allows you to enter one fully qualified property name and the type it was mapped from (or will map to) that outputs the corresponding property name on the given type.

```
// Write this
[MapProperty(nameof(Bar.Cookie), nameof(Foo.Biscuit))]
[MapProperty(nameof(Bar.Cookie), "Foo.Propertise.Height")]
public partial Foo MapToFoo(Bar bar);

// Something like this gets generated along with the mapping method
public string MapToFooPropertyMappings(string barPropertyName) => barPropertName switch {
   "Name" => "Name",
   "Cookie" => "Biscuit"
   "Height" => "Properties.Height"
}
```

I'm not saying this is how I think it should look, just trying to illustrate what I'd want it to do.

**Comment by latonz** [comment]
Thank you for opening this issue and for the proposal. We want to keep the scope of Mapperly limited to object to object mappings. This seems to be related but does not directly contribute to the goal of Mapperly. Therefore we think this is out of scope of Mapperly for now.
