### ISSUE TITLE
Mapping Enumerable with Flattening

### ISSUE THREAD

**Issue by mikewojtkiewicz** [riok/mapperly#462]
I have a mapping scenario where both the source and destination are mapped into an enumerable, but the properties are flattened. A simple example of my setup:

```c#
public class Car
{
    IEnumerable<Tires> Tires { get; set; }
}

public class Tires
{
    public int Id { get; set; }
    public Make Make { get; set; }
}

public class Make
{
    public string Description { get; set; }
}

public class CarDto
{
    IEnumerable<TireDto> Tires { get; set; }
}
public class TireDto
{
    public int Id { get; set; }
    public string Make { get; set; }
}
```

I don't see a way where I can enter a MapProperty attribute on a list of objects that can map downward:
`[MapProperty(new [] { nameof(Car.Tires), nameof(Car.Tires.Make), nameof(Car.Tires.Make.Description) }, new[] { nameof(CarDto.Tires), nameof(CarDto.Tires.Make) })`

I know this is a simple example, but my setup is a little more complex. Is there a way I can map enumerables in this manner?

**Comment by latonz** [comment]
In your mapper just create another mapping method for the object you want to map on which you add the `MapProperty` attribute:
```c#
[Mapper]
partial class MyMapper
{
    public partial IEnumerable<CarDto> Map(IEnumerable<Car> cars);

    [MapProperty(new[]{nameof(Tire.Make), nameof(Tire.Make.Description)}, new[]{nameof(TireDto.Description)}]
    private partial TireDto Map(Tire tire);
}
```
