### ISSUE TITLE
Add `// <auto-generated/>` to generated source

### ISSUE THREAD

**Issue by zbecknell** [riok/mapperly#494]
**Is your feature request related to a problem? Please describe.**

Generated source can report warnings due to a lack of an `// <auto-generated/>` comment at the top of the file.

**Describe the solution you'd like**

Add the comment to mark the source as auto-generated thus preventing warnings from appearing from generated code.

**Comment by latonz** [comment]
Mapperly uses the `.g.cs` filename suffix which should mark the file as auto generated. Did you experience an IDE reporting warnings for the Mapperly generated code?

**Comment by zbecknell** [comment]
I do have some warnings showing up in JetBrains Rider:

```
Riok.Mapperly/Riok.Mapperly.MapperGenerator/Mapper.g.cs(493,76): warning CS8714: The type 'string?' cannot be used as type parameter 'TKey' in the generic type or method 'Dictionary<TKey, TValue>'. Nullability of type argument 'string?' doesn't match 'notnull' constraint.
```

I see the `// <auto-generated />` comment added from other source generators (including Microsoft's `RazorSourceGenerator`) -- is there is a reason not to add the comment?

**Comment by latonz** [comment]
I thought adding `.g.cs` as suffix should have the same effect as the `// <auto-generated />` comment. But as the [MS docs](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) also use both, Mapperly should probably use both too.

Feel free to open a PR 😉
Implementation hints: Add a `Comment()` leading trivia in `Riok.Mapperly.Emit.SourceEmitter.Build`.
