### ISSUE TITLE
Get-only `HashSet` doesn't map correctly

### ISSUE THREAD

**Issue by danbluhmhansen** [riok/mapperly#498]
**Describe the bug**
Mapping from an `IEnumerable<T>` to a `HashSet<T>` no longer works.

**To Reproduce**
1. Declare a class `A` with a get-only `HashSet<T>` property.
2. Declare another class `B` with an enumerable property (`IEnumerable<T>`, `ICollection<T>`, ...).
3. Add a mapping method `A Map(B source);`

**Code snippets**
```csharp
using Riok.Mapperly.Abstractions;

FooBarMapper mapper = new();

Foo foo = new();
var bar = mapper.Map(foo);

Console.WriteLine(foo.Ints.SequenceEqual(bar.Ints));

class Foo
{
    public IEnumerable<int> Ints { get; } = new List<int>() { 1, 2, 3, };
}
class Bar
{
    public HashSet<int> Ints { get; } = new();
}

[Mapper]
partial class FooBarMapper
{
    public partial Bar Map(Foo foo);
}
```

**Expected behavior**
Before Mapperly version `2.8.0-next.2` the above code snippet would generate:
```csharp
#nullable enable
partial class FooBarMapper
{
    public partial Bar Map(Foo foo)
    {
        var target = new Bar();
        foreach (var item in foo.Ints)
        {
            target.Ints.Add(item);
        }

        return target;
    }
}
```

**Actual behavior**
Now (after `2.8.0-next.1`) it generates:
```csharp
#nullable enable
partial class FooBarMapper
{
    public partial global::Bar Map(global::Foo foo)
    {
        var target = new global::Bar();
        return target;
    }
}
```

**Environment (please complete the following information):**
- Mapperly Version: 2.8.0
- .NET Version: 7.0.304
- Target Framework: net7.0
- IDE: dotnet CLI
- OS: Windows 11

**Comment by latonz** [comment]
Thank you for opening this issue, we'll look into it.

**Comment by latonz** [comment]
Rel. https://github.com/riok/mapperly/issues/499
