### ISSUE TITLE
Mapping `init` or `required` properties does not use `PropertyNameMappingStrategy`

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#505]
**Describe the bug**
Mapping to `required` or `init` properties doesn't use the `PropertyNameMappingStrategy`.

**Expected behavior**
Mapping should use `PropertyNameMappingStrategy`

**Code snippets**
```C#
[Mapper(PropertyNameMappingStrategy = PropertyNameMappingStrategy.CaseInsensitive)]
public static partial class Mapper
{
    public static partial B Map(A src);
}
public class A
{
    public int Value { get; set; }
}
public class B
{
    // can also be required
    public int value { get; init; }
}
```
**Generated code**
```C#
public static partial global::Riok.Mapperly.Sample.B Map(global::Riok.Mapperly.Sample.A src)
{
    var target = new global::Riok.Mapperly.Sample.B();
    return target;
}
```

**Comment by latonz** [comment]
@cristianUrbina sure, go for it! Thank you for your interest in contributing to Mapperly 😊 You can find some hints on how to contribute [here](https://next.mapperly.pages.dev/docs/contributing/). Don't hesitate to ask here, if anything is unclear 😊

**Comment by cristianUrbina** [comment]
Would you recommend making a specific unit test case for this bug or should I modify the existing one? (Sorry, I'm kinda new)
![image](https://github.com/riok/mapperly/assets/57534097/37e433f6-2682-4f92-b383-aa80b7ae67d6)

**Comment by cristianUrbina** [comment]
Thanks, I'm on it.

**Comment by cristianUrbina** [comment]
Hello, sorry for the delay, I'll hurry up and I hope I got something by Saturday. Thanks for being comprehensive

**Comment by cristianUrbina** [comment]
@latonz I don't really know if this this is the correct way to request a review. Can you check my PR? Thanks for the patience 😄

**Comment by latonz** [comment]
@cristianUrbina thank you very much for the contribution 😊  Well done! 🚀

**Comment by latonz** [comment]
@cristianUrbina FYI here is a guide on how to request a review: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review. However, I just noted this may only be possible for accounts having write access to the repository...
