### ISSUE TITLE
Deep clone of a `record` uses a non-existing constructor

### ISSUE THREAD

**Issue by jhorodecki** [riok/mapperly#506]
I'm trying to create methods for deep cloning a bunch of objects. Everything works fine except the case where I want to clone a `record`. The generated code uses non-existing constructor.

**To Reproduce**
1. Declare a record `SampleRecord`.
2. Use `UseDeepCloning = true`
3. Declare a mapping method `SampleRecord Clone(this SampleRecord record)`

**Code snippets**
```CS
public record SampleRecord(string Name, string Value);

[Mapper(UseDeepCloning = true)]
public static partial class CloneExtensions
{
   public static partial SampleRecord Clone(this SampleRecord record);
}
```
The generated code is
```CS
#nullable enable
public static partial class CloneExtensions
{
    public static partial global::SampleRecord Clone(this global::SampleRecord record)
    {
        return new global::SampleRecord(record);
    }
}
```
Note the `new global::SampleRecord(record)`. The `SampleRecord` does not have such constructor, therefore the code does not compile.
> 'SampleRecord.SampleRecord(SampleRecord)' is inaccessible due to its protection level

What's interesting  everything works fine if I declare another `record` type with the same properties and try to map one `record` to another.

Expected behavior is obviously to use existing `(string, string)` constructor of `SampleRecord` (or an appropriate constructor in other cases, e.g. when the `record` declares parameterless constructor).

**Environment:**
- Mapperly Version: 2.8.0
- .NET Version: .NET 7.0.5
- Target Framework: net7.0
- IDE: Visual Studio 2022 v17.6.0
- OS: Win10 10.0.19045 Build 19045

**Comment by latonz** [comment]
This should have been fixed with https://github.com/riok/mapperly/pull/456 which was released in [v2.9.0-next.2](https://github.com/riok/mapperly/releases/tag/v2.9.0-next.2). Can you verify this? You may need to restart your IDE and perform a fresh build after upgrading the Mapperly package.
