### ISSUE TITLE
Add a diagnostic if an explicitly ignored member is mapped explicitly

### ISSUE THREAD

**Issue by latonz** [riok/mapperly#512]
Add a diagnostic with a default level of warning if an explicitly ignored member (`MapperIgnoreSourceAttribute` or `MapperIgnoreTargetAttribute`) is mapped explicitly (`MapPropertyAttribute`): `The member {0} on {1} is ignored but is also mapped by the MapPropertyAttribute`.

Hints: In `MembersMappingBuilderContext.ctor`, everything removed by `ignoredTargetMemberNames.ExceptWith(MemberConfigsByRootTargetName.Keys);` should be stored into a list and reported as diagnostics when `AddDiagnostics()` is called.

**Comment by latonz** [comment]
Depends on #392

**Comment by mikeguta** [comment]
Hi @latonz, I added PR #708 as my first contribution to Mapperly. Let me know if that's not what you expected.
