### ISSUE TITLE
`MapProperty` modifies temporary struct members

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#516]
**Describe the bug**
`MapProperty` will try to modify struct members, this is invalid because a temporary object is returned and modified, not altering the original member.

**To Reproduce**
```C#
public struct MyStruct
{
    public int Value { get; set; }
}
public class Destination
{
    public MyStruct Nested { get; set; }
}
public record Source(int Value);

[Mapper]
public static partial class Mapper
{
    [MapProperty(nameof(Source.Value), "Nested.Value")]
    public static partial Destination Map(Source req);
}
```

```C#
public static partial global::Riok.Mapperly.Sample.Destination Map(global::Riok.Mapperly.Sample.Source req)
{
    var target = new global::Riok.Mapperly.Sample.Destination();
    // Property 'Nested' access returns temporary value. Cannot modify struct member when accessed struct is not classified as a variable
    target.Nested.Value = req.Value;
    return target;
}
```
**Expected behavior**
Determine if `MapProperty` is mutating a struct member. Note that if `MapProperty` is mutating something with even more nesting where a sub member is a class it will be valid again.
ie
```C#
[MapProperty(nameof(Source.Value), "Nested.MyClass.Value")] // valid if MyClass if a class
```

**Comment by latonz** [comment]
Isn't this already ensured by [CS1612](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1612)?

**Comment by TimothyMakkison** [comment]
Tbh it's not required.

This way it detects the error, emits a warning and doesn't create the mapping. Without this invalid code would be generated.

Should mapperly emit a warning or generate invalid code?

**Comment by latonz** [comment]
Ah true, makes sense to not generate this mapping at all.
