### ISSUE TITLE
IQueryable projections doesn't use PropertyNameMappingStrategy

### ISSUE THREAD

**Issue by LouisUrker** [riok/mapperly#522]
**Describe the bug**
When using PropertyNameMappingStrategy.Caseinsensitive the generated IQueryable projection does not include the properties where the casing doesn't match.

**To Reproduce**
1. Declare a mapper with PropertyNameMappingStrategy.CaseInsensitive.
2. Add a mapping method `IQueryable<Dto> EntityToDto(this IQueryable<Entity> entities);`
3. Let the Entity and the Dot have a property that only differs in casing.
4. Look at the generated code.

**Expected behavior**
The generated code should map the property using the provided PropertyNameMappingStrategy, i.e. ignore the case difference.

**Code snippets**
If applicable, add code snippets to help explain your problem.

**Environment (please complete the following information):**
- Mapperly Version: 2.8.0
- .NET Version: .Net Framework 4.8
- Target Framework: net48
- IDE: Visual Studio v17.6.4
- OS: Windows 11

**Additional context**
Providing the proper name using a [MapProperty] attribute on the 'normal' mapper function (i.e. Entity -> Dot) allows the IQueryableProjection to pick it up.

**Comment by TimothyMakkison** [comment]
Thanks for the bug report, this is hsa the same cause problem as

**Comment by LouisUrker** [comment]
Thanks for the quick response!

**Comment by latonz** [comment]
Fixed by #556 / #505
