### ISSUE TITLE
Flattening a nullable property causes a build error (Expression does not have a name)

### ISSUE THREAD

**Issue by boydcl** [riok/mapperly#528]
**Describe the bug**
When you try to flatten a nullable object in a mapping, it will cause a build error because `nameof` doesn't support null. It will cause a `Expression does not have a name` error on the `nameof` method because of `nameof(Car.Radio?.Brand)`.

**To Reproduce**
1. Declare a mapper as such:

```csharp
public record Radio(string Brand);

public record Car(Guid Id, Radio? Radio);

public record CarDto(Guid Id, string RadioBrand);

[Mapper]
public partial class ExampleMapper
{
    public partial CarDto CarToCarDto(Car car);
}
```

2. Build; you will get the error

**Expected behavior**
I would expect the build to succeed and throw an exception that isn't relying on `nameof` so it can support nullable objects. Maybe a `NullReferenceException` would be more appropriate.

**Code snippets**

The generated mapper containing the problematic `nameof` method:

```csharp
public partial class ExampleMapper
{
    public partial global::MapperlyExample.Mappers.CarDto CarToCarDto(global::MapperlyExample.Mappers.Car car)
    {
        var target = new global::MapperlyExample.Mappers.CarDto(car.Id, car.Radio?.Brand ?? throw new System.ArgumentNullException(nameof(car.Radio?.Brand)));
        return target;
    }
}
```

**Environment (please complete the following information):**
- Mapperly Version: 2.8.0, 2.9.0-next2
- .NET Version: 7.0
- Target Framework: .net7.0
- IDE: Rider 2023.1
- OS: MacOS 13

**Additional context:**

- I stumbled upon this because I was mapping objects from an external contracts library which has nullable reference types **disabled**, while my own project has nullable references types **enabled**.
- I would happily like to submit a PR for this but wouldn't really know where to start as I have no experience writing source generators.

**Comment by latonz** [comment]
Nameof doesn't work with null safe property access, it is not needed for nameof.
The flattening in your case should work automatically without any manual configuration (due to the matching pascal case convention name). An `ArgumentNullException` is thrown if the source value is null and the target value cannot be null.

**Comment by latonz** [comment]
@TimothyMakkison thank you for the PR, I completely misunderstood this issue 🙄
