### ISSUE TITLE
Working with Mapperly and MS Community Toolkit

### ISSUE THREAD

**Issue by michaeltagmose** [riok/mapperly#533]
It seems that using Mapperly together with Microsoft Community Toolkit is not possible, unless somebody can give me some good advice.

I have a number of uses of MSCT like this:
[ObservableProperty]
private ArtifactTypeEnum m_ArtifactType;

The aim is to get a property named
public ArtifactTypeEnum ArtifactType { get ... set ... }
generated by the Toolkit generator in a partial class. 

When I Map this property using Mapperly, it is not found.
I get this error 
RMG012	Property ArtifactType on source type ...Clients.Models.ArtifactMdl was not found

The setup of the mapping is like this
public static partial ArtifactDto ToDto(this ArtifactMdl src);

I expect the mapper to find the property and map it, even though it is found in 
a partial class generated by some generator.

My guess is that the two generators need to run in a different sequence. 
Are there any workarounds to this behaviour?

- Mapperly Version: 2.7.0
- .NET Version: 6.0
- Target Framework: .net6.0
- IDE: Visual Studio v17.6.4
- OS: Win 10

**Comment by latonz** [comment]
AFAIK chaining source generators is not supported by Roslyn and I don't know any workarounds despite implementing the generated code by hand.
