### ISSUE TITLE
Multiple properties mapping

### ISSUE THREAD

**Issue by ToxaAnton** [riok/mapperly#577]
Hi, I have a question about the possibility to map multiple fields in one.
I've read previously opened questions and surprisingly didn't find a similar one
(however I still could just miss it)

What do I looking for is functionality like in AutoMapper, where you can define your destination field to be mapped from multiple source fields, like in the example below.

```c#
public record User(string FirstName, string LastName);
public record UserDto(string FullName);

UserDto Map(User source)
{
    FullName => $"{source.FirstName} {source.LastName}";
}
``` 
Is there any functionality like that present in Mapperly?

Thank you!

**Comment by latonz** [comment]
For this you can either add a computed get only property to `User`, or you can use [after map](https://mapperly.riok.app/docs/configuration/before-after-map):

Get only property:
```c#
public record User(string FirstName, string LastName)
{
    public string FullName => $"{source.FirstName} {source.LastName}";
}
public record UserDto(string FullName);

[Mapper]
public static partial MyMapper
{
    public static partial MapToDto(this User user);
}
```

After map:
```c#
public record User(string FirstName, string LastName);
public record UserDto(string FullName);

[Mapper]
public static partial MyMapper
{
    public static partial UserDto MapToDto(this User user)
    {
        var dto = user.MapToDtoInternal();
        dto.FullName = $"{user.FirstName} {user.LastName}";
        return dto;
    }

    private static partial UserDto MapToDtoInternal(this User user);
}
```
