### ISSUE TITLE
[MapperIgnore] on properties of classes

### ISSUE THREAD

**Issue by mutzl** [riok/mapperly#585]
A common usecase is, that entities have properties that never need to be mapped to any DTO.
Some of these metadata properties might even be defined in a base class.
For example:

``` c#
public abstract class BaseEntity
{
    public DateTime CreatedDate { get; set; }
    public string CreatedBy { get; set; } = default!;
    public DateTime? UpdatedDate { get; set; }
    public string? UpdatedBy { get; set; }
}

public class MyEntity : BaseEntity 
{
    public string Foo { get; set; }
}

public class MyDto 
{
    public string Foo { get; set; }
}
```

So the mapper configuration is always pretty verbose:
``` c#
    [MapperIgnoreTarget(nameof(BaseEntity.CreatedDate))]
    [MapperIgnoreTarget(nameof(BaseEntity.CreatedBy))]
    [MapperIgnoreTarget(nameof(BaseEntity.UpdatedDate))]
    [MapperIgnoreTarget(nameof(BaseEntity.UpdatedBy))]
    public static partial MyEntity ToEntity(this MyDto dto);

    [MapperIgnoreSource(nameof(BaseEntity.CreatedDate))]
    [MapperIgnoreSource(nameof(BaseEntity.CreatedBy))]
    [MapperIgnoreSource(nameof(BaseEntity.UpdatedDate))]
    [MapperIgnoreSource(nameof(BaseEntity.UpdatedBy))]
    public static partial MyDto ToDto(this MyEntity entity);
```

A MapperIgnoreAttribute - similar to the well known `[JsonIgnore]` - directly on the property would make code way cleaner.

``` c#
public abstract class BaseEntity
{
    [MapperIgnore] public DateTime CreatedDate { get; set; }
    [MapperIgnore] public string CreatedBy { get; set; } = default!;
    [MapperIgnore] public DateTime? UpdatedDate { get; set; }
    [MapperIgnore] public string? UpdatedBy { get; set; }
}
```

**Comment by TimothyMakkison** [comment]
Would #513 and #201 help?

**Comment by mutzl** [comment]
> Would #513 and #201 help?

#201 would help, I suppose.

The `[MapperIgnore]` looks way more intuitive to me, though. 
(at least for the use case I described above - for this kind of metadata, I know upfront, that it's never gonna be mapped).


BTW: Und vielen Dank für diese großartige Idee und Umsetzung von mapperly!

**Comment by TimothyMakkison** [comment]
Good point with 513. If #201 supports adding ignores then it will be perfect for you.

Failing that it would be pretty easy to modify the `IgnoreObsolete` code to support `[MapperIgnore]` 👍

**Comment by latonz** [comment]
https://github.com/riok/mapperly/pull/611 removes the `MapperIgnoreAttribute`, it may in a later release be reused to ignore properties/fields.
