### ISSUE TITLE
Add `Initialization` strategy.

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#586]
**Is your feature request related to a problem? Please describe.**
When using `[MapProperty]` to map nested properties it is possible to set the field of an uninitialized member. This results in a `NullReferenceException`.

The following example occurs because Mapperly sees that `B.Nested` is not marked as nullable and infers that it was initialized by the constructor.

```C#
[Mapper]
public static partial class Mapper
{
    [MapProperty("Value", "Nested.Value")]
    public static partial B Map(A src);
}

public class A { public int Value { get; set; } }

public class B { public C Nested { get; set; } } // Non-nullable property 'Nested' is uninitialized. Consider declaring the property as nullable.

public class C { public int Value { get; set; } }
```

### Generated code
```C#
public static partial global::Riok.Mapperly.Sample.B Map(global::Riok.Mapperly.Sample.A src)
{
    var target = new global::Riok.Mapperly.Sample.B();
    target.Nested.Value = src.Value;
    return target;
}
```

Note that if  `B.Nested` is marked as nullable, then Mapperly will generate a null initializer:

```C#
public static partial global::Riok.Mapperly.Sample.B Map(global::Riok.Mapperly.Sample.A src)
{
    var target = new global::Riok.Mapperly.Sample.B();
    target.Nested ??= new();
    target.Nested.Value = src.Value;
    return target;
}
```
 
Related to #581

**Describe the solution you'd like**
I'm not sure about the name but `[InitializationStrategy()]` could be used to tell mapperly to generate conditional initializers for nested mappings. This could be extended to all fields not just members affected by `MapProperty`. i.e. `InitializationStrategy.Default`, `InitializationStrategy.AsNeeded`, `InitializationStrategy.All`

**Describe alternatives you've considered**
This could be prevented by changing the constructor or by marking the member as nullable. Unfortunately this isn't always possible as this could be a breaking change or the object is auto generated.

**Comment by latonz** [comment]
IMO in this case Mapperly behaves as designed. I don't think Mapperly should handle wrong null annotations. A user may fix this in the object constructor or with an object factory.

**Comment by TimothyMakkison** [comment]
> I don't think Mapperly should handle wrong null annotations. A user may fix this in the object constructor or with an object factory.

I understand this, but in many cases people can't change model ie #581

**Comment by latonz** [comment]
If the models are not adjustable, one can always use an object factory to initialise the object correctly.
If Mapperly tries to fix wrongly annotated code, this would need handling of a lot more complex situations (eg. what happens if the source property is marked as non-nullable, is actually nullable, but the target isn't...). As there is an easy workaround, I don't think Mapperly should adjust in this regard until there would be very big demand.
