### ISSUE TITLE
Map Tuple To Object

### ISSUE THREAD

**Issue by RHaughton** [riok/mapperly#590]
I'm trying to map a tuple to an object.

It seems that mapperly won't do it automatically and I can live with that. But even if I specify the method mapperly should use it doesn't use it.

Input property. (A tuple of 3 values)
![image](https://github.com/riok/mapperly/assets/24850599/c53202b7-2980-4686-ac92-c80f71facced)

Target Property Object: 
![image](https://github.com/riok/mapperly/assets/24850599/5ee28a18-6ca9-4c3f-8e16-73157a124f97)

The method I would like Mapperly to use:
![image](https://github.com/riok/mapperly/assets/24850599/b031d897-341d-4f2e-b7f1-60e14ab18132)

The method mapperly is using:
![image](https://github.com/riok/mapperly/assets/24850599/94ae41f6-c7db-4423-ab17-0ed667e8c521)

How can I enforce Mapperly to use my method like in the example "User implemented mapping methods"?

**Comment by TimothyMakkison** [comment]
Hey, I think you are very close to making it work. It looks like you named the tuple elements incorrectly on your user implemented mapping method.

> The method I would like Mapperly to use: ![image](https://user-images.githubusercontent.com/24850599/255530572-b031d897-341d-4f2e-b7f1-60e14ab18132.png)

Here your tuple parameter uses the names`days20`, `days50` and `days100`, when it should be `days9`, `days14` and `days14`.

> It seems that mapperly won't do it automatically and I can live with that. 

Yeah, sorry about that, #467 should fix this, its the final item in the 2.9 release milestone.

**Comment by latonz** [comment]
Closing this as #467 is merged and 2.9.0 should be released soon.
