### ISSUE TITLE
Add support for mapping inner class

### ISSUE THREAD

**Issue by isarhoo** [riok/mapperly#599]
**Is your feature request related to a problem? Please describe.**
The internal class can correspond to properties declared as private set.

**Describe the solution you'd like**
```
record CarDto(string? Id);
partial class Car
{
    public string? Id { get; private set; }

    public void Update(CarDto dto)
    {
        Mapper1 mapper = new Mapper1();
        mapper.MergeCarDto(dto, this);
    }

    [Mapper(UseDeepCloning = true)]
    internal partial class Mapper1
    {
        public partial void MergeCarDto(CarDto source, Car target);
    }
}
```

**Describe alternatives you've considered**
Currently using Automapper, but the performance is not optimal.

**Additional context**
N.A.

**Comment by latonz** [comment]
This should already work with `2.9.0-next.4` shouldn't it?

With https://github.com/riok/mapperly/pull/597 even private fields are mapped. https://github.com/riok/mapperly/pull/597 has not yet landed in a next release and probably won't make it into 2.9.0. However, it will be included in 2.10.0-next.1. https://github.com/riok/mapperly/pull/601 adds an explicit test case for exact this use case.

**Comment by isarhoo** [comment]
#597 seems not to be in 2.9.0-next.4. I tested the example from #601 using 'main,' but it didn't work. Did I do something wrong
Thank you for your help

Example 
```
public partial class A
{
    private string _value;

    [Riok.Mapperly.Abstractions.Mapper(UseDeepCloning = true)]
    internal partial class Mapper
    {
        public partial A Clone(A source);
    }
}
```
Current generation
```
public partial class A
{
    internal partial class Mapper
    {
        public partial global::ConsoleApp2.A Clone(global::ConsoleApp2.A source)
        {
            var target = new global::ConsoleApp2.A();
            return target;
        }
    }
```

**Comment by latonz** [comment]
https://github.com/riok/mapperly/pull/597 is not included in a next release, thats correct. It will probably only land in `2.10.0-next.1`. However, mappers inside other classes will already work with `2.9.0-next.4`, but without mapping private fields (only mapping public fields/properties). With #597 all accessible fields are mapped.

**Comment by isarhoo** [comment]
If declared as "private set," the following issues will arise. 
Thank you for your help

Example
```
public partial class A
{
    private string _value;
    public string Name { get; private set; }

    [Riok.Mapperly.Abstractions.Mapper(UseDeepCloning = true)]
    internal partial class Mapper
    {
        public partial A Clone(A source);
    }
}
```

A.Mapper.g.cs
```
public partial class A
{
    internal partial class Mapper
    {
        public partial global::ConsoleApp2.A Clone(global::ConsoleApp2.A source)
        {
            var target = new global::ConsoleApp2.A();
            target._value = source._value;
            target.<Name> k__BackingField = source.<Name> k__BackingField;
            target.Name = source.Name;
            return target;
        }
    }
}
```

**Comment by isarhoo** [comment]
If declared as "private set," the following issues will arise.
Thank you for your help

Example
```
public partial class B
{
    public string Id { get; private set; }

    [Riok.Mapperly.Abstractions.Mapper(UseDeepCloning = true)]
    internal partial class Mapper
    {
        public partial B Clone(B source);

        public partial B Update(C source);
    }

   public record C(string Id);

}
```

B.Mapper.g.cs
```
public partial class B
{
    internal partial class Mapper
    {
        public partial global::ConsoleApp2.B Clone(global::ConsoleApp2.B source)
        {
            var target = new global::ConsoleApp2.B();
            target.<Id>k__BackingField = source.<Id>k__BackingField; //?
            target.Id = source.Id;
            return target;
        }

        public partial global::ConsoleApp2.B Update(global::ConsoleApp2.B.C source)
        {
            var target = new global::ConsoleApp2.B();
            target.Id = source.Id;
            return target;
        }
    }
}
```

**Comment by TimothyMakkison** [comment]
Good find. C# properties are two methods that mutate a private field ie `<Id>k__BackingField`. Mapperly is trying to map the two fields together. Not sure if this only happens with private set. 

Ill see if I can fix it later
