### ISSUE TITLE
Private mapper do not work when the parent class implement an interface.

### ISSUE THREAD

**Issue by SebastianStehle** [riok/mapperly#606]
**Describe the bug**

 I have the basic setup:
 
 ```c#
internal sealed class UserWithClaims : IUser
{
    private readonly IdentityUser snapshot;

    public UserWithClaims(IdentityUser user, IReadOnlyList<Claim> claims, IReadOnlySet<string> roles)
    {
        // Clone the user so that we capture the previous values, even when the user is updated.
        snapshot = Mapper.IdentityUserToIdentityUser(user);
    }

    [Mapper(UseDeepCloning = true)]
    private static partial class Mapper
    {
        public static partial IdentityUser IdentityUserToIdentityUser(IdentityUser source);
    }
}
```

But the generated code does not add the namespace to the `IUser` interface, which is defined in another namespace. So the follow code is generated:

```c#
#nullable enable
namespace Notifo.Identity
{
    internal sealed class UserWithClaims : IUser
    {
        private static partial class Mapper
        {
            public static partial global::Microsoft.AspNetCore.Identity.IdentityUser IdentityUserToIdentityUser(global::Microsoft.AspNetCore.Identity.IdentityUser source)
            {
                var target = new global::Microsoft.AspNetCore.Identity.IdentityUser();
                target.Id = source.Id;
                ...
                return target;
            }
        }
    }
}
```

**Expected behavior**
The implementing or base classes do not need to be copied to the generated code. if you want to copy that, add the namespaces.

**Environment (please complete the following information):**
- Mapperly Version: 2.8.0
- .NET Version: 7.0

**Additional context**

**Comment by SebastianStehle** [comment]
Sorry, I just realized that private mappers do not work anyway.

**Comment by TimothyMakkison** [comment]
Hey, thanks for the bug report. I think I can fix fix this issue

> Sorry, I just realized that private mappers do not work anyway.

Private mappers should be supported, just make the containg class partial.
You didn't mean something like #599 did you?

**Comment by TimothyMakkison** [comment]
This bug has been fixed in `[2.9.0-next.4](https://www.nuget.org/packages/Riok.Mapperly/2.9.0-next.4)`. See #548 for details.

**Comment by juanyacovino77** [comment]
Does Mapperly works with records?

**Comment by TimothyMakkison** [comment]
> Does Mapperly works with records?

Mapperly can map classes, structs, records and tuple records. Tuple mapping will be added to the next version.

Mappers must be a `partial class`, so you can't have `record` or a `struct` mapper 


#### Example record mapping
```C#
[Mapper]
public static partial class Mapper
{
    public static partial TupleRecord MapToTupleRecord(Source src);
    public static partial ClassRecord MapToClassRecord(Source src);
}

public class Source { public int Id { get; set; } public string Name { get; set; } }

public record TupleRecord(int Id, string Name);
public record ClassRecord { public int Id { get; init; } public string Name { get; init; } }
```

**Comment by juanyacovino77** [comment]
Thanks for answering..

Is it valid to map records defined like this?

public record Person(int Id, string Name, string Address);
public record PersonDTO(int Id, string Name);

**Comment by TimothyMakkison** [comment]
> Thanks for answering..
> 
> Is it valid to map records defined like this?
> 
> public record Person(int Id, string Name, string Address); public record PersonDTO(int Id, string Name);

Yes! Afaik Mapperly can map most types.

```C#
[Mapper]
public static partial class Mapper
{
    // MapperIgnoreSource isn't required but because `Address` is not mapped to the target Mapperly will generate a warning: "Source member "Address" not mapped".
    [MapperIgnoreSource(nameof(Person.Address))]
    public static partial PersonDTO Map(Person src);
}
```
#### Generated code
```C#
public static partial global::Riok.Mapperly.Sample.PersonDTO Map(global::Riok.Mapperly.Sample.Person src)
{
    var target = new global::Riok.Mapperly.Sample.PersonDTO(src.Id, src.Name);
    return target;
}
```

**Comment by latonz** [comment]
@juanyacovino77 please open a discussion for a question and don't take over other issues.

**Comment by latonz** [comment]
@SebastianStehle can you reproduce your issue with `2.9.0-next.4`?
