### ISSUE TITLE
Mapping from double? to complex type generates wrong code

### ISSUE THREAD

**Issue by ran-lc** [riok/mapperly#63]
**Describe the bug**
When attempting to map from a class that has a property of type `double?` to a class with the same named property, it generates incorrect code. We expect the code that is generated, to either have a null check on the property before passing it or just passing the value fully, instead of calling `.Value` on it. It will generate warnings/errors depending on the csproj setup when nullable is enabled for that. However, calling `.Value` does not make sense since a method has been provided on the mapper that should be able to cope with the `double?` type.

In the following snippet you can see the DtoMapper that has been declared where the above scenario is being attempted.

```csharp
[Mapper]
public partial class DtoMapper
{
    public partial NotNullableType To(TypeWithNullableProperty y);

    public Wrapper Map(double? source)
    {
        if (!source.HasValue) return null;
        return new Wrapper()
        {
            Test = source.Value
        };
    }
}

public class Wrapper
{
    public double Test { get; set; }
}

public class TypeWithNullableProperty
{
    public double? Test { get; set; }
}

public class NotNullableType
{
    public Wrapper Test { get; set; }
}
```

**Generated code**
This is the code that has been generated 
```csharp
public partial NotNullableType? To(TypeWithNullableProperty? y)
{
    if (y == null)
        return default;
    var target = new NotNullableType();
    target.Test = Map(y.Test.Value);
    return target;
}
```

**Expected behavior**¨

I guess the following code is what we actually expected that would happen in this case.

```csharp
public partial NotNullableType? To(TypeWithNullableProperty? y)
{
    if (y == null)
        return default;
    var target = new NotNullableType();
    target.Test = Map(y.Test);
    return target;
}
```
**Environment (please complete the following information):**
 - Mapperly Version: [2.2.0]
 - .NET Version: [6.0.102]
 - Target Framework: [.net6.0]
 - OS: [Windows 11 22000.556]

**Comment by latonz** [comment]
Thank you for the report. We will look into it.

**Comment by ran-lc** [comment]
Thanks for the quick fix. Will check it out!

**Comment by ran-lc** [comment]
Could you make either a pre release or normal release on this so that it is possible to download through nuget?

**Comment by latonz** [comment]
Currently we release pre-releases only to the github nuget server. [This document](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry) describes, how you can add the nuget server. The owner is riok, the pre-release package is available here: [Riok.Mapper-v2.2.1-next.1](https://github.com/riok/mapperly/packages/1252995).
