### ISSUE TITLE
Virtual/override mapper methods cause compile errors

### ISSUE THREAD

**Issue by cremor** [riok/mapperly#639]
**Describe the bug**
If the partial mapper method declaration has the `virtual`, `override`, `sealed` or `new` modifier then Mapperly generates invalid code. The generated code then has the compiler error CS8800 ("Both partial method declarations must have identical combinations of 'virtual', 'override', 'sealed', and 'new' modifiers.")

**To Reproduce**
1. Create mapper classes like shown below.
2. Try to comple the code.

**Expected behavior**
Valid code should be generated.

**Code snippets**
```cs
[Mapper]
internal partial class TestDtoMapper
{
    public virtual partial TestDto MapToDto(TestEntity entity);

    public partial TestEntity MapToEntity(TestDto dto);
}

[Mapper]
internal partial class TestDtoMapper2 : TestDtoMapper
{
    public override partial TestDto MapToDto(TestEntity entity);
}

[Mapper]
internal partial class TestDtoMapper3 : TestDtoMapper
{
    public sealed override partial TestDto MapToDto(TestEntity entity);

    public new partial TestEntity MapToEntity(TestDto dto);
}
```

**Environment (please complete the following information):**
- Mapperly Version: 3.0.0
- .NET Version: 7.0.307
- Target Framework: net7.0
- IDE: Visual Studio v17.6.6
- OS: Windows 10

**Comment by TimothyMakkison** [comment]
Also found that the following causes the error `Both partial method declarations must have identical combinations of 'virtual', 'override', 'sealed', and 'new' modifiers`
```
[Mapper]
public static partial class Mapper
{
    static partial B Map(A source);
}

// generates
private static partial global::Riok.Mapperly.Sample.Mapper.B Map(global::Riok.Mapperly.Sample.Mapper.A source)
```

**Comment by cremor** [comment]
> ```cs
>     static partial B Map(A source);
> ```

That shouldn't be valid code. When I try this I get CS8796 ("Partial method 'Mapper.Map(A)' must have accessibility modifiers because it has a non-void return type.") in the non-generated code.

When I test it with a `void` return type (and a target parameter) I get a compiler error in the generated code. But I'd say this is fine because you should never use a partial method declaration without accessibility modifier for a mapper (those are only used for methods that might be completely removed by the compiler if they have no implementation).
