### ISSUE TITLE
Mapperly fails to initiate nested properties with init setters

### ISSUE THREAD

**Issue by senal** [riok/mapperly#676]
**Describe the bug**
Not sure if this is a bug or by design of the library or my limitation of knowledge of the concepts being used in this lib.

The issue I'm facing.
I have a domain object `Car` is an immutable object. I want to instantiate a new object of a `Car` by mapping props from an external dto call `CarDto` ( which is a mutable object).

**Car class**
```c#
public class Car
{
    public string Modal { get; init; } = default!;
    public Gearbox Gearbox { get; init; } = default!;
}

public class Gearbox
{
    public int Number { get; init; }
}
```
**CarDto Class**
```c#
public class CarDto
{
    public string Modal { get; set; } = default!;
    public TransmissionUnit TransmissionUnit { get; set; } = default!;
}

public class TransmissionUnit
{
    public int Unit_Number { get; set; }
}
```

**To Reproduce**
I've done the mapper as below and it throws a design-time error as per the attached screenshot.
```c#
[Mapper]
public static partial class CarMapper
{
    [MapProperty("TransmissionUnit.Unit_Number", "Gearbox.Number")]
    public static partial Car MapCarDtoToCar(CarDto dto);
}
```
Mapper throws design time error
![image](https://github.com/riok/mapperly/assets/2841066/c6420b0e-8b5a-45cb-9381-d0c1bb4c25d0)

**Expected behavior**
Mapper should return an instance of `Car` by initiating nested properties and filling their values from the provided source.

**Environment (please complete the following information):**
- Mapperly Version: 3.1.0
- .NET Version: net7.0
- IDE:  Visual Studio v17.7.1 
- OS: Windows 11 Business

**Comment by latonz** [comment]
Mapperly does not support nested property paths on both sides (source and target). Instead you can define another mapping method:
```c#
[Mapper]
public static partial class CarMapper
{
    public static partial Car MapCarDtoToCar(CarDto dto);
    
    [MapProperty(nameof(TransmissionUnit.Unit_Number), nameof(GearBox.Number)]
    private static partial GearBox Map(TransmissionUnit tu);
}
```

**Comment by senal** [comment]
@latonz , Thanks for the feedback. Closing this ticket.
