### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by WeUseBc** [riok/mapperly#68]
Hi and thank you for making this :)

One of the reasons why I'm not keen on using runtime mappers, is that by refactoring and various changes in the codebase, I might rename properties in my domain model, which silently breaks mapping to e.g. dto's.

I would really like a "strict mode" where all the properties of the target is required which should fail if something is missing. Then I would have to explicitly have to add either [Ignore] or [MapProperty] to handle those cases. A bit like we get an compiler error if mapping between types isn't possible.

Is this something that you would consider adding?

**Comment by latonz** [comment]
Currently there is a diagnostic `RMG012: Mapping source property not found` which is emitted when a source property is not found with the severity of info. However, you can set its severity to  `error` by adding `dotnet_diagnostic.RMG012.severity = error` to your editorconfig. Currently the message of `RMG012` is not optimal (it doesn't note what the target class is. Also there is no diagnostic if a property does only exist on source but not on target.

A diagnostic for unmapped source properties sounds like a good idea to implement. Feel free if you want to contribute a PR.

**Comment by WeUseBc** [comment]
Thanks for your answer :)

I haven't worked with source generators at all, so could you give some pointers on how you would implement such a thing?

**Comment by latonz** [comment]
To add the target type to the message of `RMG012`: Look up usages of `MappingSourcePropertyNotFound` in `Riok.Mapperly.Diagnostics.DiagnosticDescriptors`, extend its message format and add the target type message argument on the callers side.

To add a new diagnostic when there is an unmapped source property add a new entry in `Riok.Mapperly.Diagnostics.DiagnosticDescriptors` and `AnalyzerReleases.Shipped.md`.
In `Riok.Mapperly.Descriptors.MappingBuilder.ObjectPropertyMappingBuilderContext`, track a set of source properties and remove  them as they are used in a mapping (eg. in `Riok.Mapperly.Descriptors.MappingBuilder.ObjectPropertyMappingBuilder.BuildMappingBody`, `Riok.Mapperly.Descriptors.MappingBuilder.NewInstanceObjectPropertyMappingBuilder.TryBuildConstructorMapping`, `Riok.Mapperly.Descriptors.MappingBuilder.NewInstanceObjectPropertyMappingBuilder.BuildInitOnlyPropertyMappings`). Finally report the diagnostics as needed in `Riok.Mapperly.Descriptors.MappingBuilder.ObjectPropertyMappingBuilder.BuildMappingBody` (similar how RMG004 is reported).

Add tests in `Riok.Mapperly.IntegrationTests` and `Riok.Mapperly.Tests`. You can use the tests in `Riok.Mapperly.Tests` to debug Mapperly.

**Comment by latonz** [comment]
Released in Mapperly 2.3.0. Check the [readme](https://github.com/riok/mapperly#strict-mappings) on how to use it and let me know if you have any feedback.

**Comment by E021ntox** [comment]
@latonz Is there a setting to configure all analyzers to 'error' by default? Something like what's shown here: https://josefpihrt.github.io/docs/roslynator/configuration/. Right now, I have to manually set each one to 'error', which is a terrible experience.

```
dotnet_diagnostic.RMG000.severity = error
dotnet_diagnostic.RMG001.severity = error
dotnet_diagnostic.RMG002.severity = error
dotnet_diagnostic.RMG003.severity = error
dotnet_diagnostic.RMG004.severity = error
dotnet_diagnostic.RMG005.severity = error
dotnet_diagnostic.RMG006.severity = error
dotnet_diagnostic.RMG007.severity = error
dotnet_diagnostic.RMG008.severity = error
dotnet_diagnostic.RMG009.severity = error
dotnet_diagnostic.RMG010.severity = error
dotnet_diagnostic.RMG011.severity = error
dotnet_diagnostic.RMG012.severity = error
dotnet_diagnostic.RMG013.severity = error
dotnet_diagnostic.RMG014.severity = error
dotnet_diagnostic.RMG015.severity = error
dotnet_diagnostic.RMG016.severity = error
dotnet_diagnostic.RMG017.severity = error
dotnet_diagnostic.RMG018.severity = error
dotnet_diagnostic.RMG019.severity = error
dotnet_diagnostic.RMG020.severity = error
dotnet_diagnostic.RMG021.severity = error
dotnet_diagnostic.RMG022.severity = error
dotnet_diagnostic.RMG023.severity = error
dotnet_diagnostic.RMG024.severity = error
dotnet_diagnostic.RMG025.severity = error
dotnet_diagnostic.RMG026.severity = error
dotnet_diagnostic.RMG027.severity = error
dotnet_diagnostic.RMG028.severity = error
dotnet_diagnostic.RMG029.severity = error
dotnet_diagnostic.RMG030.severity = error
dotnet_diagnostic.RMG031.severity = error
dotnet_diagnostic.RMG032.severity = error
dotnet_diagnostic.RMG033.severity = error
dotnet_diagnostic.RMG034.severity = error
dotnet_diagnostic.RMG035.severity = error
dotnet_diagnostic.RMG036.severity = error
dotnet_diagnostic.RMG037.severity = error
dotnet_diagnostic.RMG038.severity = error
dotnet_diagnostic.RMG039.severity = error
dotnet_diagnostic.RMG040.severity = error
dotnet_diagnostic.RMG041.severity = error
dotnet_diagnostic.RMG042.severity = error
dotnet_diagnostic.RMG043.severity = error
dotnet_diagnostic.RMG044.severity = error
dotnet_diagnostic.RMG045.severity = error
dotnet_diagnostic.RMG046.severity = error
dotnet_diagnostic.RMG047.severity = error
dotnet_diagnostic.RMG048.severity = error
dotnet_diagnostic.RMG049.severity = error
dotnet_diagnostic.RMG050.severity = error
dotnet_diagnostic.RMG051.severity = error
dotnet_diagnostic.RMG052.severity = error
dotnet_diagnostic.RMG053.severity = error
dotnet_diagnostic.RMG054.severity = error
dotnet_diagnostic.RMG055.severity = error
dotnet_diagnostic.RMG056.severity = error
dotnet_diagnostic.RMG057.severity = error
dotnet_diagnostic.RMG058.severity = error
dotnet_diagnostic.RMG059.severity = error
dotnet_diagnostic.RMG060.severity = error
dotnet_diagnostic.RMG061.severity = error
dotnet_diagnostic.RMG062.severity = error
dotnet_diagnostic.RMG063.severity = error
dotnet_diagnostic.RMG064.severity = error
dotnet_diagnostic.RMG065.severity = error
dotnet_diagnostic.RMG066.severity = error
dotnet_diagnostic.RMG067.severity = error
dotnet_diagnostic.RMG068.severity = error
dotnet_diagnostic.RMG069.severity = error
dotnet_diagnostic.RMG070.severity = error
dotnet_diagnostic.RMG071.severity = error
dotnet_diagnostic.RMG072.severity = error
dotnet_diagnostic.RMG073.severity = error
dotnet_diagnostic.RMG074.severity = error
dotnet_diagnostic.RMG075.severity = error
dotnet_diagnostic.RMG076.severity = error
dotnet_diagnostic.RMG077.severity = error
dotnet_diagnostic.RMG078.severity = error
dotnet_diagnostic.RMG079.severity = error
dotnet_diagnostic.RMG080.severity = error
dotnet_diagnostic.RMG081.severity = error
dotnet_diagnostic.RMG082.severity = error
dotnet_diagnostic.RMG083.severity = error
dotnet_diagnostic.RMG084.severity = error
dotnet_diagnostic.RMG085.severity = error
dotnet_diagnostic.RMG086.severity = error
dotnet_diagnostic.RMG087.severity = error
dotnet_diagnostic.RMG088.severity = error
dotnet_diagnostic.RMG089.severity = error
dotnet_diagnostic.RMG090.severity = error
dotnet_diagnostic.RMG091.severity = error
dotnet_diagnostic.RMG092.severity = error
dotnet_diagnostic.RMG093.severity = error
dotnet_diagnostic.RMG094.severity = error
dotnet_diagnostic.RMG095.severity = error
dotnet_diagnostic.RMG096.severity = error
dotnet_diagnostic.RMG097.severity = error
dotnet_diagnostic.RMG098.severity = error
dotnet_diagnostic.RMG099.severity = error
dotnet_diagnostic.RMG100.severity = error
```

**Comment by latonz** [comment]
@E021ntox https://josefpihrt.github.io/docs/roslynator/configuration/ specifies that one can use `dotnet_analyzer_diagnostic.category-{category}.severity` to configure the severity for the entire category. Mapperly reports all diagnostics with the category `Mapper`. However, I couldn't get it to work easily. Does this work for you? Does this approach work for you for for roslynator?

**Comment by E021ntox** [comment]
`dotnet_analyzer_diagnostic.category-mapper.severity = error` (or `category-Mapper` with a capital M) wasn't working or taking effect. I wasn't entirely sure if Roslynator itself was actually working either. However, after adding the configurations from the Roslynator documentation, the number of warnings in the editor did increase, though I don't know the exact details. Anyway, I've already removed Roslynator and switched to other analyzers.

```
All rules
To set the default rule severity for all analyzer rules, use the following syntax. However, this severity setting only affects rules that are enabled by default.
```
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#scope

**Comment by latonz** [comment]
I came across that MS docs too, however, I couldn't get it to work. I'm not sure whether it only works with the built-in categories.

**Comment by E021ntox** [comment]
Alright, then please implement it this way. I originally hoped that everything could be done in `editorconfig`, but after looking closer, I found that `editorconfig` isn't what I imagined. It seems we'll just have to settle for configuring it in `csproj`.

https://github.com/meziantou/Meziantou.Analyzer/blob/main/src/Meziantou.Analyzer.Pack/build/Meziantou.Analyzer.props
