### ISSUE TITLE
Nullable error when target type comes from external reference

### ISSUE THREAD

**Issue by PaulVrugt** [riok/mapperly#690]
**Describe the bug**
Nullable error when target type comes from external reference

**To Reproduce**
Download the sample project from #679

**Expected behavior**
No nullable erros

**Code snippets**
source:
```c#
public class Source
{
    public SubSource[]? Property1 { get; set; }
}

public class SubSource
{
    public Guid Id { get; set; }
}
```

and a mapper:

```c#
[Mapper]
internal static partial class EntityMapper
{
    internal static partial Target ToMutationIssue(Source issueDto);
}
```

and the target, but this target is included via a references project:
```c#
public class Target
{
    public SubTarget[]? Property1 { get; set; }
}

public class SubTarget
{
    public Guid Id { get; set; }
}
```

**Environment (please complete the following information):**
- Mapperly Version: 3.1.0
- .NET Version: .net 7
- Target Framework: .net 7
- IDE: Visual Studio v17.6.6
- OS: windows 11

**Additional context**
It only happens when the target class is in a references project

**Comment by PaulVrugt** [comment]
Yeah my brain also crashed investigating what was going wrong. But the problem in our case is that ALL dto's are coming from a referenced project, and we treat all warnings as errors in our project, so this issue is preventing our code base to build.

As far as I could find mapperly doesn't have an option to disable nullable context in the generated code does it? Because that would be a workaround for us for the time being

**Comment by latonz** [comment]
@PaulVrugt nope Mapperly doesn't have such an option. The problem only exiss on arrays, correct?

Sorry that you can't use Mapperly for now 🙄

**Comment by TimothyMakkison** [comment]
The nullability being on the array element threw me + the difference between VS and rider.

Perhaps in external references, arrays don't correctly annotate array element/generic types, so they all annotated with `None`. This is then upgraded to `Annotated` by mapperly.

I'm strugglng t debug this. I can recreate the issue if I look at the generated code. If I then try and use the debugger I generate the correct expected code with nullability issues 😭 

```C#
public static partial global::Lib.ContainerDto MapTo(global::Riok.Mapperly.Sample.Container src)
{
    var target = new global::Lib.ContainerDto();
    target.Arrays = MapToElementDtoArray(src.Arrays);
    return target;
}
private static global::Lib.ElementDto MapToElementDto(global::Riok.Mapperly.Sample.Element source)
{
    var target = new global::Lib.ElementDto();
    target.Value = source.Value;
    return target;
}
private static global::Lib.ElementDto[] MapToElementDtoArray(global::Riok.Mapperly.Sample.Element[] source)
{
    var target = new global::Lib.ElementDto[source.Length];
    for (var i = 0; i < source.Length; i++)
    {
        target[i] = MapToElementDto(source[i]);
    }

    return target;
}

```

**Comment by TimothyMakkison** [comment]
I think I've fixed the issue. Looks like external array types treat the nullability of type arguments differently. Not sure if this is a roslyn bug 🤷 

I realised that the same issue wouldn't occur if the external collection is a list, despite having similar code generated.

```C#
// returns a `None` annotated generic type if type is an array
 if (type.ImplementsGeneric(types.Get(typeof(IEnumerable<>)), out var enumerableIntf))
            return enumerableIntf.TypeArguments[0];

// will have the correct nullability annotation
((IArrayTypeSymbol)type).ElementType;
``` 

>I'm strugglng to debug this. I can recreate the issue if I look at the generated code. Running it in debug mode generates the following code with no nullability issues 😭

I ended up creating a static `public static List<String> Logger {get:}` which would insert comments to the end of the final  `MemberDeclarationSyntax`  in `SourceEmitter`

**Comment by PaulVrugt** [comment]
Awesome! Hopefully this fixes it
