### ISSUE TITLE
MapDerivedType attribute can't map to a existing target

### ISSUE THREAD

**Issue by simo026q** [riok/mapperly#694]
**Describe the bug**
MapDerivedType attribute not working when mapping to a existing instance.
```cs
[MapDerivedType<DerivedDto, Derived>]
public partial void Map(BaseDto source, Base target);
```

**To Reproduce**
```cs
[Mapper]
public partial class Mapper
{
    [MapDerivedType<DerivedDto, Derived>]
    public partial void Map(BaseDto source, Base target);
}

public class Base
{
    public int Number { get; set; }
}

public class BaseDto
{
    public int Number { get; set; }
}

public class Derived : Base
{
    public string? Name { get; set; }
}

public class DerivedDto : BaseDto
{
    public string? Name { get; set; }
}
```

It generates this:

```cs
public partial class Mapper
{
    public partial void Map(global::BaseDto source, global::Base target)
    {
        target.Number = source.Number;
    }
}
```

**Expected behavior**
I expect it to do something like this:
```cs
public partial class Mapper
{
    public partial void Map(global::BaseDto source, global::Base target)
    {
        target.Number = source.Number;

        if (source is DerivedDto derivedSource && target is Derived derivedTarget)
        {
            derivedTarget.Name = derivedSource.Name;
        }
    }
}
```

**Environment (please complete the following information):**
- Mapperly Version: 3.1.0
- .NET Version: 7.0
- Target Framework: net7.0
- IDE: Visual Studio v17.6.6
- OS: Windows 11 Enterprise 22H2

**Comment by latonz** [comment]
Derived type mapping does currently only work for new instance mappings. Also supporting existing target objects would be a great enhancement.

**Comment by moxplod** [comment]
+1 
This would be a great enhancement and useful for me as well.

**Comment by cmeyertons** [comment]
Furthering the use case, it would be very nice if this worked with existing mappings to satisfy:

```csharp
public class SourceBase
{
    public int BaseId { get; set; }
}

public class Source : SourceBase
{
    public int Id { get; set; }
}

public class TargetBase // missing ID
{ }

public class Target : TargetBase
{ }

[Mapper]
internal static partial class TestMapper
{
    [MapDerivedType<Source, Target>]
    public static partial TargetBase ToTarget(this SourceBase source);

    private static partial Target MapToTarget(this Source source);

    [MapDerivedType<Source, Target>]
    [MapperIgnoreSource(nameof(SourceBase.BaseId))]
    private static partial void MapTarget(this SourceBase souce, TargetBase target);
}
```

In our real use case, we have many derived types and many `[Ignores]` on both source & target, which requires considerable duplication to resolve.

Being able to define the mapping logic of `Base New -> Derived New -> Base Existing` would alleviate this bloat.

**Comment by Lionel-Renaux** [comment]
+1
I also need this

**Comment by TimothyMakkison** [comment]
I'll have a go at this over the weekend. Should be able to adapt the current logic and generate a switch statement.

**Comment by latonz** [comment]
@Lionel-Renaux @moxplod please use the 👍 reaction to the issue instead of a +1 or `I also need this` comment.

**Comment by moxplod** [comment]
Works great! Thank you for this @TimothyMakkison
