### ISSUE TITLE
Nullable Enums not mapped correctly when passed to constructor

### ISSUE THREAD

**Issue by rickykaare** [riok/mapperly#744]
**Describe the bug**
When mapping nullable enums or struct values as a constructor parameter, the null values will be mapped to default instances of the enum or struct.

**To Reproduce**
Use this code snippit to gennerate a Mapper:
```csharp
using Riok.Mapperly.Abstractions;

enum SourceEnum { Value1, Value2 }
enum TargetEnum { Value1, Value2 }

struct SourceStruct { public int Value { get; set; } }
struct TargetStruct { public int Value { get; set; } }

record SourceRecord(SourceEnum? EnumValue, SourceStruct? StructValue);
record TargetRecord(TargetEnum? EnumValue, TargetStruct? StructValue);

[Mapper(EnumMappingStrategy = EnumMappingStrategy.ByName)]
static partial class Mapper
{
    public static partial TargetRecord Map(this SourceRecord record);
}
``` 

This will generate the following code for the Mapper:
```csharp
static partial class Mapper
{
    public static partial global::TargetRecord Map(this global::SourceRecord record)
    {
        var target = new global::TargetRecord(
            record.EnumValue != null ? MapToTargetEnum(record.EnumValue.Value) : default, 
            record.StructValue != null ? MapToTargetStruct(record.StructValue.Value) : default);
        return target;
    }

    //...
}
```

**Problem**
The issue is with the use of `default` which will infer the type from the `MapToTargetEnum()` and the `MapToTargetStruct()` functions, and create defaults of the non-nullable enum and structs.

**Expected behavior**
Use the type specific `default` to ensure nullability is preserved:
```csharp
static partial class Mapper
{
    public static partial global::TargetRecord Map(this global::SourceRecord record)
    {
        var target = new global::TargetRecord(
            record.EnumValue != null ? MapToTargetEnum(record.EnumValue.Value) : default(global::TargetEnum?),
            record.StructValue != null ? MapToTargetStruct(record.StructValue.Value) : default(global::TargetStruct?));
        return target;
    }

    //...
}
```

**Environment (please complete the following information):**
- Mapperly Version: 3.1.0
- .NET Version: 7.0.306
- Target Framework: net7.0
- IDE: VisualStudio Enterprise 2022 v17.6.5
- OS: Windows 11

**Comment by latonz** [comment]
Thank you for opening this issue, this definitely seems to be a bug.

**Comment by rickykaare** [comment]
I would love to do a PR, but I am struggling to figure out how the code-base works :-) 

Haven't found the code that generates the problematic null check and `default` value, yet.

**Comment by TimothyMakkison** [comment]
Would changing `NullSubstitute` to use `default(T)` work? Not sure if this would break something

**Comment by TimothyMakkison** [comment]
Iirc `!= null` is used in `NullMemberMapping`, I think it's used for constructor mappings

**Comment by latonz** [comment]
As @TimothyMakkison stated, I think the affected mapping here is `NullMemberMapping`. But I think the other `Null*Mapping`s need to be checked too. Probably only the `NullFallbackValue.Default` case of `SyntaxFactoryHelper.NullSubstitute` needs to be adjusted.

**Comment by rickykaare** [comment]
I've played around with `NullMemberMapping` and I can see the change to use type specific `default` might be a bigger change than simply casting the delegate like this:

```csharp
static partial class Mapper
{
    public static partial global::TargetRecord Map(this global::SourceRecord record)
    {
        var target = new global::TargetRecord(
            record.EnumValue != null ? (global::TargetEnum?)MapToTargetEnum(record.EnumValue.Value) : default,
            record.StructValue != null ? (global::TargetStruct?)MapToTargetStruct(record.StructValue.Value) : default);
        return target;
    }

    //...
}
```

I made the change in [this branch](https://github.com/riok/mapperly/compare/main...rickykaare:mapperly:fix/744), but it seems that the cast is not needed in all uses of the `NullMemberMapping`.

**Comment by latonz** [comment]
What do you mean by may be a bigger change? Doesn't your approach add the cast at several locations where it isn't needed at all?
I think changing the default literal would only touch some limited areas:
* Changing from `DefaultLiteral()` to `DefaultExpression(FullyQualifiedIdentifier(t))`
* Updating all callers of `NullSubstitute` to pass the correct type symbol
* Update existing tests and add new tests
But it should fix the same bug everywhere it can occur.

**Comment by rickykaare** [comment]
You are absolutely right. I was just intimidated by the changes needed to get the right type passed to `NullSubstitute`, and the amount of tests that suddenly failed :-)

I am not sure I have an overview of the changes required. Does any of you have time for looking at this? Otherwise, I can give it another shot later.

**Comment by rickykaare** [comment]
I've created 2 versions of the fix:
* #745 That adds type to all `default` statements produced by `NullSubstitute`
* #746 That only adds the type to `default` statements when the type is a nullable ValueType

The latter has a lot less impact, and I would expect this to be enough.

Let me know if any of these looks feasible.

**Comment by latonz** [comment]
Thank you for these PR's 😊 
IMO #746 should be ok as it should fix the bug with less impact while also keeping simpler generated code for reference types. I added my feedback there.
