### ISSUE TITLE
[Bug] Mapperly does not support C# language version 8.0

### ISSUE THREAD

**Issue by SupermindPT** [riok/mapperly#762]
**Describe the bug**
Xamarin Forms project does not compile, error message "error RMG046: Mapperly does not support the C# language version 8.0 but requires at C# least version 9.0", even when project language is set to C#9

**To Reproduce**
1. Create a Xamarin Forms project and install Mapperly nuget package
2. Change project to use .NET Standard 2.1 and to use C# 9
3. Try to compile the project

**Expected behavior**
The project compiles. The generated output methods by Mapperly do not contain errors.

**Environment (please complete the following information):**
- Mapperly Version: 3.2.0
- .NET Version: .Net Standard 2.1
- Target Framework: .Net Standard 2.1
- IDE: Visual Studio 2022 v. 17.7.4
- OS: Windows 11

![image](https://github.com/riok/mapperly/assets/24286072/bc21625a-654b-4dcd-99fa-c35951d77751)
![image](https://github.com/riok/mapperly/assets/24286072/a52e7f23-44ce-4b3a-889f-117b59a1ee9e)

**Comment by TimothyMakkison** [comment]
Hey,  thanks for making this bug report. Are you using C# 8? If so, the errors are intended as Mapperly requires `partial` methods added in C# 9

**Comment by TimothyMakkison** [comment]
> I changed the C# language version of the project to C# 9. Even then, I cannot build the project.
> The .NET Standard 2.1 project builds just fine, its just the Android project that throws the error.

Interesting, I'm not familiar with Xamarian forms but is it possible to change the language version in the android project? I'm not sure why Mapperly is running in the Android project unless you installed it there?
