### ISSUE TITLE
Always get error "Partial method 'method' must have an implementation part because it has accessibility modifiers"

### ISSUE THREAD

**Issue by Yang-ptp** [riok/mapperly#797]
**Describe the bug**
Always get error "Partial method 'method' must have an implementation part because it has accessibility modifiers" when adding mapper method

**To Reproduce**
1. Add a mapping method `CarDto CarToDto(Car car);`

**Environment (please complete the following information):**
- Mapperly Version: [e.g. 3.2.0]
- Target Framework: [e.g. .NET Framework 4.7.2]
- IDE: [e.g. Visual Studio v17.7.4]
- OS: [e.g. Windows 10 Pro]

**Comment by latonz** [comment]
Does your project fulfill the [requirements](https://mapperly.riok.app/docs/intro/#requirements)? Can you build the project on the command line?

**Comment by latonz** [comment]
Closing as no update is provided. Feel free to comment any updates.

**Comment by tosberg** [comment]
I am also receiving this error and I have met the requirements

Mapperly Version: 3.2.0
Target Framework. 4.7.2
Language Version: C# 9.0 (set in .csproj files and web.config /langVersion)
OS: Windows 11
Visuals  Studio Version: 17.7.6

Thoughts?

**Comment by TimothyMakkison** [comment]
Hey, have you tried restarting your IDE?

**Comment by tosberg** [comment]
> Hey, have you tried restarting your IDE?

I'll do a full reboot and see if that fixes anything.   I'll report back in a few minutes....

**Comment by tosberg** [comment]
![image](https://github.com/riok/mapperly/assets/25665396/24c8c74a-b528-4611-93ce-c8ef9517d7cc)

Nope.  Reboot didn't work.

**Comment by TimothyMakkison** [comment]
That's a shame, thanks for trying. Did you have the errors CS1029 and CS8304 before trying to use Mapperly? CS8304 looks a little suspicious tbh.

**Comment by tosberg** [comment]
> That's a shame, thanks for trying. Did you have the errors CS1029 and CS8304 before trying to use Mapperly? CS8304 looks a little suspicious tbh.

Oh, that.  yeah, I just put _#error version_ in my code just to validate that my compiler was using C# 9.0 language.

I'm going to setup a separate project here and try again.   If that works, I'm going to compare the differences with my main project and see if I can spot anything.  I'll share my code if I still have issues.  Thanks for helping me out so far, though!

**Comment by tosberg** [comment]
Yeah, same issue in the new simple project.  Setup a Web Application Project using the C# 9.0 Language and it still causes issues.  I wanted to use Mapperly in my project but it's looking like I'll have to go with someone else unless I can resolve this

Here are my current details w/files attached below:

Visual Studio 2022 Version: v17.7.6
Mapperly Version: 3.2.0
Framework Version: 4.7.2 (web application project)
Language Version: 9.0 (set in the /langVersion in the web.config and in the <LanguageVersion> element of the .csproj file)
OS Version: Windows 11
Roslyn Compiler Version: 4.7.0-3.23517.17 (9d4cc030)



[Mapperly4.zip](https://github.com/riok/mapperly/files/13127596/Mapperly4.zip)

**Comment by TimothyMakkison** [comment]
Weird, thanks for trying.

> Basically, I'm trying to use C# 9.0 with .NET Framework 9.0 Language and by all reports this SHOULD work 

Mapperly should support .NET 4.7.2, what happens if you create a .NET 6 project? I'll look at the project you sent in the morning 👍

**Comment by tosberg** [comment]
> Weird, thanks for trying.
> 
> > Basically, I'm trying to use C# 9.0 with .NET Framework 9.0 Language and by all reports this SHOULD work
> 
> Mapperly should support .NET 4.7.2, what happens if you create a .NET 6 project? I'll look at the project you sent in the morning 👍

I did create one and actually used .NET 7, not 6, and had no issues.  However, I can't convert my existing project to 6/7 at the moment as that would be a herculean task.

**Comment by TimothyMakkison** [comment]
Interesting, I wonder if 4.7.2 is broken then, I'll look into it.
