### ISSUE TITLE
AllowNullPropertyAssignment not respected when mapping from float? to decimal?

### ISSUE THREAD

**Issue by StefanoFiumara** [riok/mapperly#803]
**Describe the bug**
I am attempting to create a mapper between an OpenAPI DTO and an existing database entity, the database entity has a column with a type of `decimal?`, the corresponding property in the openAPI DTO is `float?`.

When the property on the DTO is `null`, this null value is not assigned to the entity's property, instead, a null check is generated, meaning the target property is not mapped.

**To Reproduce**
I have the following code:
```csharp
public class UpdateDto
{
    float? SomeProperty { get; set; }
}

public class Entity 
{
    decimal? SomeProperty { get; set; }
}

// In my static mapper
private static partial void MapToEntity(this UpdateDto dto, Entity existing);
```

in `Mapper.g.cs`, the code is generated as follows:

```csharp
if(dto.SomeProperty != null)
{
    existing.SomeProperty = new decimal(dto.SomeProperty.Value);
}
```

**Expected behavior**
Since both properties are nullable, I would expect this mapping to generate the following code, so that a null value in my DTO is properly mapped to my entity, rather than ignored.

```csharp
existing.SomeProperty = dto.SomeProperty.HasValue ? new decimal(dto.SomeProperty.Value) : null;
```

I can get around this behavior via a custom property mapper:
```csharp
private static decimal? FloatToDecimal(this float? source)
  {
    return source.HasValue ? new decimal(source.Value) : null;
  }
```

But I wasn't sure why this wasn't working at first, given the description of `AllowNullPropertyAssignment` in the documentation, I would have expected this to be default behavior, let me know if this is an incorrect assumption.

Really loving this library, thank you for all your effort!

**Environment (please complete the following information):**
- Mapperly Version: 3.2.0
- .NET Version: .NET 7.0.400
- Target Framework: .net6.0
- IDE: Rider 2023.2.1
- OS: Windows 11

**Comment by TimothyMakkison** [comment]
Hey, thanks for your bug report 👍

I've successfully recreated your bug and it looks that this issue applies to other types as well. For instance this will occur with `float?` -> `double?`
```C#
public A class { public float? Value { get; set; } }
public B class { public double? Value { get; set; } }

[Mapper]
public static partial class Mapper { public static partial void Map(A src, B dst); }

// generates
public partial void Map(global::A src, global::B dst)
{
    if (src.Value != null)
    {
        dst.Value = (double)src.Value.Value;
    }
}
```

This can also occur with reference types.
```C#
class A{ public float? Value { get; set; } };
class B{ public C? Value { get; set; } };
class C{ public C(float value){} };

[Mapper]
public static partial class Mapper { public static partial void Map(A src, B dst); }

 public partial void Map(global::A src, global::B dst)
{
    if (src.Value != null)
    {
        dst.Value = new global::C(src.Value.Value);
    }
}
```

It looks like Mapperly is using the null guard when it should be using a ternary operator or else block. I'll look into a solution.
Thanks again 😄
