### ISSUE TITLE
Unable to ignore nested member

### ISSUE THREAD

**Issue by rhwork** [riok/mapperly#814]
I am unable to ignore a nested source property if it does not exist in the destination.

I have the following analysers set up in my editor.config:

```
dotnet_diagnostic.RMG012.severity = warning # Unmapped target member
dotnet_diagnostic.RMG020.severity = warning # Unmapped source member
```

I have the following code:

```
public class A
{
    public B B1 { get; set; }

    public class B
    {
        public int Id { get; set; }
    }
}

public class ADto
{
    public BDto B1 { get; set; }

    public class BDto
    {
        
    }
}

[Mapper]
public static partial class AtoADtoMapper
{
    [MapperIgnoreSource("B1.Id")]
    public static partial ADto MapTo(A a);
}
```

The errors I am seeing are:

![image](https://github.com/riok/mapperly/assets/104686988/158cbdcb-1fb6-47ba-b7a4-2ce724fc5c20)

I have tried different path types but nothing resolves the issues.

**Comment by TimothyMakkison** [comment]
Hey, unfortunately Mapperly does not support nested ignores as this will cause issues with reusing mappers. Instead you can do the following:

```C#
[Mapper]
public static partial class AtoADtoMapper
{
    public static partial ADto MapTo(A a);

     [MapperIgnoreSource("Id")]
    public static partial BDto MapToB(B src);
} 
```

Here `MapTo` will use `MapToB` to map `B1` -> `B1`

**Comment by rhwork** [comment]
Ah Brill, thanks! :)
