### ISSUE TITLE
Add commented-out lines for unmapped members on the target or source

### ISSUE THREAD

**Issue by alrz** [riok/mapperly#825]
This self-documents when properties are being ignored, whether by accident or by design.
```cs
Target Map(Source)  {
  return new Target {
    // int Target.Property1
  };
  // int Source.Property2
}
```
Could be opt-in using a property on `[Mapper]`.

**Comment by CommonGuy** [comment]
Interesting idea! But I don't think we will implement this, as it adds a lot of technical complexity without much benefits for users.
