### ISSUE TITLE
PR More  example for use

### ISSUE THREAD

**Issue by Zombach** [riok/mapperly#830]
Is your feature request related to a problem? Please describe.
I believe there is an insufficient number of usage examples in the project sections.

Describe the solution you'd like
I suggest adding more variations of different implementations in the example sections.

Describe alternatives you've considered
As an alternative, I considered the possibility of creating one project that combines all the variations, as well as creating separate projects for each implementation option.

**Additional context**
<img width="796" alt="image" src="https://github.com/riok/mapperly/assets/52016832/ae5498de-def3-479e-b1e6-57f01ea11162">

**Comment by Zombach** [comment]
see Create simple di #828

**Comment by CommonGuy** [comment]
Thanks for creating this issue and the example project.

However, since Mapperly classes are just normal C# classes, I don't think we need additional documentation for DI. The classes can be registered and used as any other C# class.
