### ISSUE TITLE
Use of match expression in null guards

### ISSUE THREAD

**Issue by trejjam** [riok/mapperly#843]
**Is your feature request related to a problem? Please describe.**
The nullable check guard can be seen i.e. [here](https://github.com/riok/mapperly/blob/main/test/Riok.Mapperly.Tests/_snapshots/UnsafeAccessorTest.PrivateNestedNullableProperty%23Mapper.g.verified.cs) causes duplicated call for source value.
```cs
if (source.GetNested()?.GetValue() != null)
{
    target.SetValue(source.GetNested().GetValue().Value);
}
```

**Describe the solution you'd like**
I think use of match expression is better:
```cs
if (source.GetNested()?.GetValue() is {} sourceGetNestedGetValue)
{
    target.SetValue(sourceGetNestedGetValue);
}
```

**Comment by TimothyMakkison** [comment]
Should this also be applied to non `UnsafeAccessor` code ie:

```C#
if (source.Nested?.Value != null)
{
    target.Value = source.Nested.GetValue.Value);
}

if (source.Nested?.Value is {} sourceNestedValue)
{
    target.Value = sourceNestedValue);
}
```

**Comment by trejjam** [comment]
Yes, I think that it's good and safer.

You can have a custom getter in a property, and with the current solution, it's executed twice.

**Comment by trejjam** [comment]
The `UnsafeAccessorAttribute` is not really related to the issue. I just spot it there when looking for a new features :) (thank you for these btw)

**Comment by ni507** [comment]
Hi @trejjam

Thanks for your report.
IMO a property getter should always be "cheap" and not cause any problems here. Improving this would be nice, but not with high priority. We will look into it in the future.

In the meantime, a PR is always welcome, so don't hesitate to ask for hints on how to get started.
