### ISSUE TITLE
Projection for single object mapping to use it with IQuryable methods.

### ISSUE THREAD

**Issue by RandomTIP** [riok/mapperly#865]
As of now, if I have a mapper method `MapAToB` and I pass it to `Select` method of `IQueryable`, it will work as long as it follows EF restrictions, which are also mentioned in Mapperly documentations for [projection](https://mapperly.riok.app/docs/configuration/queryable-projections/). This means that some of the properties will not be mapped if mapping logic for them do not follow those rules. 

Consider this logic which was generated by Mapperly: 
```

public static partial global::Syllogia.InventoryManagement.DataTransfer.Documents.Order.Responses.OrderDocumentDetailResponse ToDetailResponse(this global::Syllogia.InventoryManagement.Domain.Documents.Order.OrderDocument orderDocument)
{
    var target = new global::Syllogia.InventoryManagement.DataTransfer.Documents.Order.Responses.OrderDocumentDetailResponse()
    {
        Id = orderDocument.Id,
        DocumentNumber = orderDocument.DocumentNumber,
        SourceWarehouseId = orderDocument.SourceWarehouseId,
        SourceWarehouseName = orderDocument.SourceWarehouse?.Name,
        ReceiverWarehouseId = orderDocument.ReceiverWarehouseId,
        ReceiverWarehouseName = orderDocument.ReceiverWarehouse?.Name,
        OrganizationId = orderDocument.OrganizationId,
        OrderDate = orderDocument.OrderDate,
        DeliveryDate = orderDocument.DeliveryDate,
        OrderStatusId = orderDocument.OrderStatusId,
        OrderStatusName = orderDocument.OrderStatus?.Name,
        DocumentItems = MapToIEnumerable(orderDocument.DocumentItems),
    };
    return target;
}
```

When I use this method inside Select: 

`_context.Orders.Select(x => x.ToDetailResponse());`

it maps everything except `SourceWarehouseName`, `ReceiverWarehouseName `, `OrderStatusName` and `DocumentItems` because first three use `?` operator for nullability check and the last one uses implementation which iterates over the source collection and maps each object using generated mapper.

I know I can just define Projection method as an extension of `IQueryable` and that would work perfectly. But in specific cases, like when you have a generic repository or specification pattern which would take in projection logic of a single object, it would be nice to be able to integrate generated mapper methods with those patterns.

In such cases something like this would be nice to have: 

```
[Projection]
public static partial Foo MapToFoo(this Bar);
```
Implementation behind this would take into consideration all the restrictions and rules of EF, just like `IQueryable` mappers.

And it would be easy to use it inside repository for example: 

`Foo singleFoo = await _barRepository.GetByIdAsync(predicate: x => x.Id == id, projection: x => x.MapToFoo());`

**Comment by latonz** [comment]
Couldn't this use case also be addressed with https://github.com/riok/mapperly/issues/733?

**Comment by RandomTIP** [comment]
My apologies for a duplicate feature request, I thought I saw everything. Is there any work in progress or PRs regarding this issue?

**Comment by latonz** [comment]
I don't think there is currently anyone working on it, but I would be happy to accept a PR for #733 if you would like to contribute 😊
