### ISSUE TITLE
Configurable Constructor Priority

### ISSUE THREAD

**Issue by connorivy** [riok/mapperly#885]
When trying to map properties to types that I don't own, it can be frustrating that Mapperly will always use the parameterless constructor. 

Here is an example that I've run into trying to map two nearly identical classes.

```c#
public class MyClass
{
    public string? Value1 { get; }
    public string? Value2 { get; }
    public string? Value3 { get; }
}

public class NotMyClass
{
    public NotMyClass() { }

    public NotMyClass(string? value1, string? value2, string? value3)
    {
        this.Value1 = value1;
        this.Value2 = value2;
        this.Value3 = value3;
    }

    public string? Value1 { get; }
    public string? Value2 { get; }
    public string? Value3 { get; }
}

[Mapper]
public static partial class MyClassMapper
{
    public static partial NotMyClass Map(MyClass myClass);
}
```

By default, the mapping of the above conversion from MyClass to NotMyClass will look like this:
```c#
public static partial class MyClassMapper
{
    public static partial global::Example.NotMyClass Map(global::Example.MyClass myClass)
    {
        var target = new global::Example.NotMyClass();
        return target;
    }
}
```
You can see that this conversation isn't really mapping anything, it's just creating an instance via the parameterless constructor. However, if I just comment out the default constructor, then all values are mapped perfectly.

```c#
public static partial class MyClassMapper
{
    public static partial global::Example.NotMyClass Map(global::Example.MyClass myClass)
    {
        var target = new global::Example.NotMyClass(myClass.Value1, myClass.Value2, myClass.Value3);
        return target;
    }
}
``` 

This behavior is well defined in the documentation:
```
Mapperly supports using parameterized constructors of mapping target types. Mapperly resolves the constructor to be used by the following priorities:
- accessible constructors annotated with MapperConstructor
- accessible parameterless constructors
- accessible constructors ordered in descending by their parameter count
- constructors with a System.ObsoleteAttribute attribute, unless they have a MapperConstructor attribute
```
The solution of either using the `MapperConstructor` or `Obsolete` attribute in order to use the desired constructor doesn't work in my case because I don't own the type that I'm mapping to.

Would it be possible to provide a mapper configuration that flips the second and the third bullet point so that I can prefer the constructor with the max number of parameters descending all the way down to zero parameters?

I'm happy to help work on this issue if that functionality sounds desirable and if you'd be able to point me to the correct area of the codebase.

**Comment by latonz** [comment]
Thank you for opening this issue. If I recall it correctly, we used this order of the constructor matching to not introduce a breaking change when we introduced the constructor parameter mapping feature. I think we should switch the order in the long term, probably with the next breaking change. For now, we could introduce a property `PreferParameterlessConstructors` on `MapperDefaultsAttribute` and `MapperAttribute` which defaults to true. With the next major release it could default to false, and with the next major release + 1 it could probably be removed completely (if we decide to not keep it).
If `PreferParameterlessConstructors` is set to true the current order of constructor matching would be applied.
If `PreferParameterlessConstructors` is set to false, `accessible parameterless constructors` wouldn't have any special handling and `accessible constructors ordered in descending by their parameter count` would apply (which would rank parameterless constructors last, just before obsolete constructors).

**Comment by latonz** [comment]
Would be very happy to accept a PR implementing this.
Code that probably needs to be adjusted:
* `Riok.Mapperly.Abstractions.MapperAttribute`
* `Riok.Mapperly.Abstractions.MapperDefaultsAttribute`
* `Riok.Mapperly.Configuration.MapperConfigurationMerger.Merge`
* `Riok.Mapperly.Descriptors.MappingBodyBuilders.NewInstanceObjectMemberMappingBodyBuilder.BuildConstructorMapping`
* Documentation
* Tests

I just noticed there is a regression bug in the constructor ordering: currently it is ordered descending by `MapperConstructorAttribute` then ascending by `MapperConstructorAttribute` which doesn't make any sense. The `ThenBy` should be the `ObsoleteAttribute`.

[Contributing docs](https://mapperly.riok.app/docs/contributing/) may give you a good introduction on how to contribute to Mapperly and about its tooling and architecture.
