### ISSUE TITLE
`IgnoreMappingMethodAttribute` to ignore user implemented mapping methods

### ISSUE THREAD

**Issue by latonz** [riok/mapperly#891]
Mapperly considers all user implemented methods which have a mapping method signature as a valid user implemented mapping method. A user may want to not use some methods (eg. implementation details of other user implemented mappings) as mapping methods. A new attribute `IgnoreMappingMethodAttribute` applied to methods tells Mapperly to not consider such a method as a user implemented mapping.

**Comment by ialexj** [comment]
Could we have a way to opt out of automatic by-type mapping methods altogether for a mapper? I'm happy for this sort of magic on projects that I own, but where the objects that are being mapped might be maintained by others that aren't familiar with the way Mapperly works, I'd rather have more explicit control.

Ideally, I would like to be able to turn off automatic mapping for a whole mapper, but then still be able to opt-in for specific methods. So something like 
`[Mapper AutomaticMappingMethods=false]`, but also a `[Mapping Automatic=true]` (false to ignore this method) on the method itself.

**Comment by latonz** [comment]
IMO a mapper should only do mappings and not contain unrelated code, therefore I think it should be the right approach to include any mapping methods by default unless explicitly ignored.

**Comment by latonz** [comment]
This is released on the next channel as version `3.5.0-next.2`. It can be used by applying `[UserMapping(Ignore = true)]`. Any feedback would be appreciated 😊

**Comment by ialexj** [comment]
Brilliant, thank you for your effort.
