### ISSUE TITLE
Report diagnostics on the method which triggered it

### ISSUE THREAD

**Issue by cmeyertons** [riok/mapperly#896]
**Is your feature request related to a problem? Please describe.**
Kind of -- with the current documentation, it's unclear how to properly share and distribute Mapperly map functionality (operate at scale).  

Due to perceived Mapperly limitations, we place all of our static Mapperly extension methods in shared static partial classes across the solution. This approach creates problems because IDEs have a tough time placing the Mapperly error with the offending code.

I was able to solve this problem by bringing in `UseStaticMapper` which allows selectively consuming other mappers functionality.  I found this attribute through exploration via the IDE (honestly stumbled upon it in a very lucky fashion)

**Describe the solution you'd like**
This functionality is incredibly useful and should be documented.  I might even go as far to add a new top level page "Sharing Mappings" as it solves that particular use case quite well.

**Describe alternatives you've considered**
n/a

**Additional context**
Thanks for all the great work on this repository, Mapperly is a fantastic library.

**Comment by latonz** [comment]
Thank you for your feedback!

The usage of `UseMapper` and `UseStaticMapper` is documented [here](https://mapperly.riok.app/docs/configuration/user-implemented-methods/#use-external-mappings).
It looks like you didn‘t find that documentation, probably we sgould move it to its own top level menu entry as you suggested 🤔

I‘m also interested in the Mapperly limitations you have refered to. Which limitations do you mean? How did they limit your use-case? And can you elaborate more on
> This approach creates problems because IDEs have a tough time placing the Mapperly error with the offending code.

? Is the IDE becoming laggy? Which IDE and which Mapperly version are you using?

**Comment by cmeyertons** [comment]
Ah thank you -- I did not expect the documentation to be on that page to be honest, i guess see if others come across the same issue.  I would've thought it would be a top level page.  I should've also used the search box at the top....

I'm on VS 17.7 (latest) and latest Mapperly (3.2.0)

What i was seeing was having numerous `static partial class MyMapper` distributed across numerous files resulted in opaque errors that were hard to trace (this problem was alleviated by not doing that at all and instead using `UseStaticMapper`)

I reproduced how I am getting the confusing error in a simplistic case:

```csharp
public class SourceBase
{
    public int Id { get; set; }
}

public class Source : SourceBase
{ }

public class TargetBase // missing ID
{ }

public class Target : TargetBase
{ }

[Mapper]
internal static partial class TestMapper
{
    [MapperIgnoreSource(nameof(SourceBase.Id))]
    public static partial TargetBase ToTarget(this SourceBase source);
}

internal static partial class TestMapper
{
    // there is an error here!  we don't have any derived type mapping for SourceBase.Id
    public static partial IEnumerable<Target> ToTarget(this IEnumerable<Source> source);
}
```

The error for the `IEnumerable` mapping shows up not at the method level, but at the class level:

![image](https://github.com/riok/mapperly/assets/19917677/79ea0ac6-b666-416a-8035-609f86887f8d)

It would be nice if this error cropped up at the method level(s) where this is problematic, rather than lifting to the class level where the `[Mapper]` is defined.

**Comment by latonz** [comment]
Ah thank you for the explanations. This is because Mapperly tries to report the diagnostic on the method it encountered the problem. However, this currently only works if there is a direct method context. In your case there is no direct method context as Mapperly generates a new method for the mapping from `Source` to `Target`. We should always report the diagnostic on the method which triggered it (`ToTarget`) in your sample.
