### ISSUE TITLE
Constructor mapping with `MapProperty` and `nameof`

### ISSUE THREAD

**Issue by trejjam** [riok/mapperly#952]
**Is your feature request related to a problem? Please describe.**
When configuring mapping, it's convenient to use `nameof`.

but the following code does not work:
```cs
public class Mapping
{
    [MapProperty(nameof(A.BId), nameof(B.Id))]
    private partial B Map(A source);
}

class A
{
    public long BId { get; }
}

class B
{
    public long Id { get; }

    public B(long id) { Id = id; }
}
```

To make it work it's necessary to use `[MapProperty(nameof(A.BId), "id")]`

**Describe the solution you'd like**
Search in [`MemberConfigsByRootTargetName`](https://github.com/riok/mapperly/blob/main/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs#L323) uses `ignoreCase`.

**Comment by latonz** [comment]
Thank you for opening this issue. This would be a nice improvement :+1: Note that the case-insensitivity should only apply to the constructor parameters but not everything else, except if `PropertyNameMappingStrategy.CaseInsensitive` is set on the mapper. Feel free to open a PR 😉

**Comment by trejjam** [comment]
Would you prefer to use LINQ to find a key as case insensitive or to create a second dictionary in the context with `StringComparer.InvariantCultureIgnoreCase`?

**Comment by latonz** [comment]
I think a secondary dictionary would be the better option as with a lot of members the linq option could get quite slow.
