### ISSUE TITLE
Support generic `IQueryable<T>` mapping

### ISSUE THREAD

**Issue by latonz** [riok/mapperly#968]
Support for generic `IQueryable<T>` mapping methods:
```c#
public static partial System.Linq.IQueryable<TTarget> Map<TSource, TTarget>(System.Linq.IQueryable<TSource> source);

private B Map(A source);
private D Map(C source);

// generates
public static partial System.Linq.IQueryable<TTarget> Map<TSource, TTarget>(System.Linq.IQueryable<TSource> source)
{
    return source switch
    {
        IQueryable<global::A> x when typeof(TTarget).IsAssignableFrom(typeof(global::B)) => source.Select(...),
        IQueryable<global::C> x when typeof(TTarget).IsAssignableFrom(typeof(global::D)) => source.Select(...),
        _ => throw new System.ArgumentException($"Cannot map {source.GetType()} to {typeof(IQueryable<TTarget>)} as there is no known type mapping", nameof(source)),
    };
}
```

Similar to the existing generic mapping methods ([docs](https://mapperly.riok.app/docs/configuration/generic-mapping/)), type constraints should also be supported.

Brought up by @19bartek92 in https://github.com/riok/mapperly/discussions/960#discussion-5910036

**Comment by latonz** [comment]
@TimothyMakkison The switch expression doesn't happen inside the `Expression`/`Select`, therefore I think it should work.
We should support the same feature set as we are supporting for regular [generic mappings](https://mapperly.riok.app/docs/configuration/generic-mapping/) (where possible), therefore we should support `IQueryable<T>` as well as `IQueryable<object>` as source.

**Comment by TimothyMakkison** [comment]
> @TimothyMakkison The switch expression doesn't happen inside the `Expression`/`Select`, therefore I think it should work. 

Gotcha, I was a little confused because the docs only mentioned the object source for generic mapping.

> We should support the same feature set as we are supporting for regular [generic mappings](https://mapperly.riok.app/docs/configuration/generic-mapping/) (where possible), therefore we should support `IQueryable<T>` as well as `IQueryable<object>` as source.

Might be worth creating an issue to track all the variants for this and existing target mapping. I have an idea for IQueryable<TSource> but haven't looked into the others

**Comment by latonz** [comment]
@TimothyMakkison I think existing target mapping isn't relevant for `IQueryable`, is it?

**Comment by TimothyMakkison** [comment]
Sorry, I was suggesting that an issue needs to track each variant of generic mapping for IQueryable and for generic existing target mapping
