### ISSUE TITLE
Update to VS 17.8.2 Professional breaks generated code visibility

### ISSUE THREAD

**Issue by felichsm** [riok/mapperly#978]
**Describe the bug**
Until I updated to Visual Studio 17.8.2, I was able to see & jump to the generated code by navigating on the partial method (as descibed here: https://mapperly.riok.app/docs/configuration/generated-source/).
With the update to VS 17.8.2 I'm no longer able to navigate to the source generated implementation of the partial method. 

Someone else had already filed a bug on VisualStudio developer community https://developercommunity.visualstudio.com/t/Unable-to-jump-to-the-implementation-of/10531890?sort=newest 
which got moved to the roslyn project https://github.com/dotnet/roslyn/issues/71075 and then closed. 

As the closing comment states that "the user is not using roslyn", I'm not sure whether this is:
- wrong usage of the mapperly nuget package user (in which case, I would suggest to add this to the documentation)
- mapperly using roslyn wrong 

What I noticed:
When I initially load the Solution, the Mapper code is (sometimes) visible (could not find a pattern). After saving the associated partial Mapper file, the generated mapping code disappears. 
I observed, that when initially, the mapping code is visible, the generated code **.g.cs file resides in the _C:\Users\XXXX\AppData\Local\Temp\VSGeneratedDocuments_ folder
After the save operation, the **.g.cs content is empty and the file moved to _C:\Users\XXXX\AppData\Local\Temp\ **VisualStudioSourceGeneratedDocuments** folder

**To Reproduce**
1. Install VS 17.8.2
2. Create a console project, referencing mapperly nuget package
3. Implement a partial mapper
4. Navigate to the generated code

**Expected behavior**
Navigating to the generated code shows the source generator implementation

**Environment (please complete the following information):**
- Mapperly Version: 3.2.0
- .NET Version: 8.0.100
- Target Framework: .net8 or .net7 (tried both)
- IDE: Visual Studio v17.8.2 (professional)
- OS: Windows

**Comments**
So far, I very much enjoy using mapperly! The described bug does not concern functionality. Compilation is still working and the generated code can be found by other means. It really just lowers usability, e.g. devs new to mapperly have a hard time finding the generated code.

**Comment by TimothyMakkison** [comment]
Thanks for bug report and research 👍 

Do you know if this happens with other source generators ie System.Text etc?

> the user is not using roslyn

Not sure 😕 I didn't think Mapperly emitted code in a strange way.

**Comment by Ajay100000** [comment]
VS 17.8.3 has just been released. Can you see if it has the issue? Thanks.

**Comment by Ajay100000** [comment]
VS has updated to VS 17.8.3 - can you try again.

It works for me, but I am not sure if I am doing the same steps you have done.

Basically, when I right click 'MapEntityToEquivalentProjection' in the code snippet below and right clicking 'Go To Implementation', I am getting both static partial classes, and I can go to the generated '.g.cs' file.

Code snippet:

[Mapper]
public static partial class MapEntityToEquivalentProjection
{ ... }

**Comment by latonz** [comment]
Could you please also try the latest pre release of Mapperly? (and don't forget to restart VS after updating the version of the dependency, VS sometimes doesn't reload the source generator correctly).

**Comment by TimothyMakkison** [comment]
Tested on Visual Studio Community 2022 `17.8.3` and was able to view the generated code for Mapperly `3.2.0` and `3.3.0-next.6` by using F12.

Perhaps this is issue is limited to VS professional or `17.8.2` I'm unable to test the former.

**Comment by cremor** [comment]
For me with VS 17.8.3 and Mapperly 3.2.0 F12 navigation also still works fine. It navigates to the generated source file in `C:\Users\<UserName>\AppData\Local\Temp\VSGeneratedDocuments\<Guid>`

Maybe the comment "user is not using roslyn" from @CyrusNajmabadi in https://github.com/dotnet/roslyn/issues/71075#issuecomment-1839224515 meant that the navigation itself is not done by Roslyn? (Independend on how the code was generated.) I suspect that because I don't recognize the popup in that screenshot.
@felichsm are you maybe using ReSharper or some other VS extension that might override the default VS code navigation?

**Comment by felichsm** [comment]
> For me with VS Enterprise 17.8.3 and Mapperly 3.2.0 F12 navigation also still works fine. It navigates to the generated source file in `C:\Users\<UserName>\AppData\Local\Temp\VSGeneratedDocuments\<Guid>`
> 
> Maybe the comment "user is not using roslyn" from @CyrusNajmabadi in [dotnet/roslyn#71075 (comment)](https://github.com/dotnet/roslyn/issues/71075#issuecomment-1839224515) meant that the navigation itself is not done by Roslyn? (Independend on how the code was generated.) I suspect that because I don't recognize the popup in that screenshot. @felichsm are you maybe using ReSharper or some other VS extension that might override the default VS code navigation?

Thanks for the hint with ReSharper. 
**I disabled ReSharper and now I can navigate fine to the generated code**! 

I remember having tried this, before filing this issue, but it did not work back then. 
Well, disabling Resharper seems to solve the problem, so I added this as a comment to the [issue on VisualStudio developer community](https://developercommunity.visualstudio.com/t/Unable-to-jump-to-the-implementation-of/10531890?sort=newest)

Next steps: 
I will update ReSharper and if that does not fix it, I will file an issue with JetBrains

Thanks for your help!

**Comment by felichsm** [comment]
FYI: 
Updating to Resharper 2023.3 fixed the issue.

The problem seems to only occure with Resharper **2023.2.3** and VS 17.8.2 & VS 17.8.3
